In [9]:
import pandas as pd
from datetime import datetime
import warnings
warnings.filterwarnings("ignore", category=UserWarning, module="openpyxl")

In [107]:
df_errores= pd.read_csv('c:/data/tabla_errores.txt', sep='\t', encoding='latin1')
df_errores.head(3)

,CODIGO_ERROR,DESCRIPCION_ERROR,DETALLE,SOLUCION,SOLUCION 2
0,1068,YA EXISTE UN PAGO CON LA MISMA FECHA DE INICIO...,YA EXISTE UN PAGO CON LA MISMA FECHA DE INICIO...,CONFIGURACION SAS,ANULAR MASIVAS
1,0003,ERROR EN CARGA DE TRAMA,ERROR EN CARGA DE TRAMA,ANALISIS EMISOR,NaN
2,1155,TRAMA REPETIDA O DUPLICADA,TRAMA REPETIDA O DUPLICADA,CONFIGURACION SAS,ANULAR MASIVAS

In [ ]:
#df_errores= df_errores.dropna(subset=['CODIGO_ERROR']) # Elimina filas con CODIGO_ERROR nulo

In [ ]:
df_errores= df_errores.rename(columns={'SOLUCION 2': 'SOLUCION_2'}) # cambiar nombre de las columnas
df_errores= df_errores.fillna({'SOLUCION_2':''})
df_errores= df_errores.drop_duplicates(subset=['CODIGO_ERROR'])

In [109]:
df_errores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64 entries, 0 to 63
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CODIGO_ERROR       55 non-null     object
 1   DESCRIPCION_ERROR  64 non-null     object
 2   DETALLE            63 non-null     object
 3   SOLUCION           64 non-null     object
 4   SOLUCION_2         64 non-null     object
dtypes: object(5)
memory usage: 2.6+ KB

In [195]:
# Se carga el dataset en excel de Accidentes mortales
df_desgravamen= pd.read_excel('C:/data/446 - Desgravamen Desempleo - BBVA - P3.xlsx', sheet_name='Hoja1', 
                              dtype={'COD DE CERTIFICADO': str, 'DESCRIPCION ERROR': str, 'IDELOTE': str})

In [159]:
df_desgravamen.head(2)

,NRO LOTE,LOTES ANTERIORES,FECHA CARGA,CODIGO PRODUCTO,PRODUCTO,CODIGO PLAN,NOMBRE DE PLAN,COD DE CERTIFICADO,FECINI_ALTA_CERTIFICADO,FECFIN_ALTA_CERTIFICADO,...,FECNACIMIENTO,TIPDOCUMENTO,NUMDOCUMENTO,NOMBRE DE ARCHIVO,IDELOTE,IDEDET.1,ORIGEN ERROR,CODIGO ERROR,DESCRIPCION ERROR,Unnamed: 32
0,205315,NaN,2019-04-02 10:26:07.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,20100130204_0157001_20190404_002.TXT,903001104868240007432580011048681020074429601U...,205315.0,289236134.0,Error canal,1155,Trama repetida o duplicada
1,205315,NaN,2019-04-02 10:26:07.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,20100130204_0157001_20190404_002.TXT,903001104264440000623340011042641020015853501P...,205315.0,289235584.0,Error canal,1155,Trama repetida o duplicada

In [160]:
df_desgravamen.columns = (
    df_desgravamen.columns
    .str.strip()  # quitar espacios al inicio/fin
    .str.upper()  # opcional: todo en mayúsculas
    .str.replace(r'[^A-Za-z0-9_]', '_', regex=True)  # reemplazar todo lo que no sea letra/número/_ por _
)

In [161]:
df_desgravamen= df_desgravamen.rename(columns={'CODIGO_ERROR': 'TIPO_ERROR',
                                               'DESCRIPCION_ERROR': 'CODIGO_ERROR',
                                               'IDELOTE': 'TRAMA'}) # cambiar nombre de las columnas

In [162]:
df_desgravamen= df_desgravamen[['CODIGO_PRODUCTO', 'LOTES_ANTERIORES','COD_DE_CERTIFICADO', 'FECINI_ALTA_CERTIFICADO', 
                                'FECFIN_ALTA_CERTIFICADO','IDEDET', 'TRAMA', 'TIPO_MOVIMIENTO', 'FEC__INICIO', 
                                'FEC__FIN', 'MONEDA', 'SUMA_ASEGURADA', 'TASA', 'PRIMABRUTACAN', 'PRIMANETACAN', 
                                'NOMBRE_DE_ARCHIVO', 'ORIGEN_ERROR', 'TIPO_ERROR', 'CODIGO_ERROR']]

In [163]:
df_desgravamen.head(3)  # Displaying the first five rows of the DataFrame

,CODIGO_PRODUCTO,LOTES_ANTERIORES,COD_DE_CERTIFICADO,FECINI_ALTA_CERTIFICADO,FECFIN_ALTA_CERTIFICADO,IDEDET,TRAMA,TIPO_MOVIMIENTO,FEC__INICIO,FEC__FIN,MONEDA,SUMA_ASEGURADA,TASA,PRIMABRUTACAN,PRIMANETACAN,NOMBRE_DE_ARCHIVO,ORIGEN_ERROR,TIPO_ERROR,CODIGO_ERROR
0,NaN,NaN,NaN,NaN,NaN,289236134.0,903001104868240007432580011048681020074429601U...,Sin Movimiento,2019-03-15 00:00:00,2019-04-15 00:00:00,USD,0,0.0,60.65,58.88,20100130204_0157001_20190404_002.TXT,289236134.0,Error canal,1155
1,NaN,NaN,NaN,NaN,NaN,289235584.0,903001104264440000623340011042641020015853501P...,Sin Movimiento,2019-03-01 00:00:00,2019-04-01 00:00:00,SOL,0,0.0,134.06,130.16,20100130204_0157001_20190404_002.TXT,289235584.0,Error canal,1155
2,NaN,NaN,NaN,NaN,NaN,289239811.0,903001108315440008473680011012373020027799501P...,Sin Movimiento,2019-03-01 00:00:00,2019-04-01 00:00:00,SOL,0,0.0,148.4,144.08,20100130204_0157001_20190404_002.TXT,289239811.0,Error canal,1155

In [164]:
df_desgravamen.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42019 entries, 0 to 42018
Data columns (total 19 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   CODIGO_PRODUCTO          6959 non-null   float64
 1   LOTES_ANTERIORES         183 non-null    object
 2   COD_DE_CERTIFICADO       6959 non-null   object
 3   FECINI_ALTA_CERTIFICADO  2866 non-null   object
 4   FECFIN_ALTA_CERTIFICADO  2866 non-null   object
 5   IDEDET                   42007 non-null  float64
 6   TRAMA                    42007 non-null  object
 7   TIPO_MOVIMIENTO          42007 non-null  object
 8   FEC__INICIO              41572 non-null  object
 9   FEC__FIN                 41572 non-null  object
 10  MONEDA                   42006 non-null  object
 11  SUMA_ASEGURADA           42007 non-null  object
 12  TASA                     42007 non-null  float64
 13  PRIMABRUTACAN            42007 non-null  object
 14  PRIMANETACAN             42007 non-null  float64
 15  NOMBRE_DE_ARCHIVO        42007 non-null  object
 16  ORIGEN_ERROR             41310 non-null  float64
 17  TIPO_ERROR               41310 non-null  object
 18  CODIGO_ERROR             40379 non-null  object
dtypes: float64(5), object(14)
memory usage: 6.1+ MB

In [165]:
df_desgravamen[df_desgravamen['CODIGO_PRODUCTO'].isnull()].head()

,CODIGO_PRODUCTO,LOTES_ANTERIORES,COD_DE_CERTIFICADO,FECINI_ALTA_CERTIFICADO,FECFIN_ALTA_CERTIFICADO,IDEDET,TRAMA,TIPO_MOVIMIENTO,FEC__INICIO,FEC__FIN,MONEDA,SUMA_ASEGURADA,TASA,PRIMABRUTACAN,PRIMANETACAN,NOMBRE_DE_ARCHIVO,ORIGEN_ERROR,TIPO_ERROR,CODIGO_ERROR
0,NaN,NaN,NaN,NaN,NaN,289236134.0,903001104868240007432580011048681020074429601U...,Sin Movimiento,2019-03-15 00:00:00,2019-04-15 00:00:00,USD,0,0.0,60.65,58.88,20100130204_0157001_20190404_002.TXT,289236134.0,Error canal,1155
1,NaN,NaN,NaN,NaN,NaN,289235584.0,903001104264440000623340011042641020015853501P...,Sin Movimiento,2019-03-01 00:00:00,2019-04-01 00:00:00,SOL,0,0.0,134.06,130.16,20100130204_0157001_20190404_002.TXT,289235584.0,Error canal,1155
2,NaN,NaN,NaN,NaN,NaN,289239811.0,903001108315440008473680011012373020027799501P...,Sin Movimiento,2019-03-01 00:00:00,2019-04-01 00:00:00,SOL,0,0.0,148.4,144.08,20100130204_0157001_20190404_002.TXT,289239811.0,Error canal,1155
3,NaN,NaN,NaN,NaN,NaN,289234182.0,903001103597540001035410011035974020021743001P...,Sin Movimiento,2019-03-26 00:00:00,2019-04-26 00:00:00,SOL,0,0.0,154.24,149.75,20100130204_0157001_20190404_002.TXT,289234182.0,Error canal,1155
4,NaN,NaN,NaN,NaN,NaN,289240842.0,903001108794240001079510011087946020006003201P...,Sin Movimiento,2019-03-04 00:00:00,2019-04-04 00:00:00,SOL,0,0.0,130,126.21,20100130204_0157001_20190404_002.TXT,289240842.0,Error canal,1155

In [166]:
df_desgravamen= df_desgravamen.fillna({'LOTES_ANTERIORES':'', 'SUMA_ASEGURADA':0, 'TASA':0, 'PRIMABRUTACAN':0, 'PRIMANETACAN':0,
                                       'MONEDA': 'SIN DATO'})

In [167]:
#df_desgravamen['COD_DE_CERTIFICADO'] = df_desgravamen['COD_DE_CERTIFICADO'].apply(lambda x: str(int(x)) if pd.notnull(x) else '0')
df_desgravamen['CODIGO_PRODUCTO'] = df_desgravamen['CODIGO_PRODUCTO'].fillna(0).astype('int')
df_desgravamen["LOTES_ANTERIORES"] = df_desgravamen["LOTES_ANTERIORES"].astype(str)
df_desgravamen['FECINI_ALTA_CERTIFICADO'] = pd.to_datetime(df_desgravamen['FECINI_ALTA_CERTIFICADO'], errors='coerce')
df_desgravamen['FECFIN_ALTA_CERTIFICADO'] = pd.to_datetime(df_desgravamen['FECFIN_ALTA_CERTIFICADO'], errors='coerce')
df_desgravamen['TIPO_MOVIMIENTO'] = df_desgravamen['TIPO_MOVIMIENTO'].astype(str)
df_desgravamen['FEC__INICIO'] = pd.to_datetime(df_desgravamen['FEC__INICIO'], format='%d/%m/%Y', errors='coerce')
df_desgravamen['FEC__FIN'] = pd.to_datetime(df_desgravamen['FEC__FIN'], format='%d/%m/%Y', errors='coerce')
df_desgravamen['MONEDA'] = df_desgravamen['MONEDA'].astype(str)
df_desgravamen['SUMA_ASEGURADA']= pd.to_numeric(df_desgravamen['SUMA_ASEGURADA'], errors='coerce')
df_desgravamen['TASA']= pd.to_numeric(df_desgravamen['TASA'], errors='coerce')
df_desgravamen['PRIMABRUTACAN']= pd.to_numeric(df_desgravamen['PRIMABRUTACAN'], errors='coerce')
df_desgravamen['PRIMANETACAN']= pd.to_numeric(df_desgravamen['PRIMANETACAN'], errors='coerce')
df_desgravamen['ORIGEN_ERROR'] = df_desgravamen['ORIGEN_ERROR'].fillna(0).astype('int')

In [168]:
df_desgravamen['MONEDA'] = df_desgravamen['MONEDA'].replace('nan', 'SIN DATO')

In [169]:
df_desgravamen.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42019 entries, 0 to 42018
Data columns (total 19 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   CODIGO_PRODUCTO          42019 non-null  int64
 1   LOTES_ANTERIORES         42019 non-null  object
 2   COD_DE_CERTIFICADO       6959 non-null   object
 3   FECINI_ALTA_CERTIFICADO  2866 non-null   datetime64[ns]
 4   FECFIN_ALTA_CERTIFICADO  2866 non-null   datetime64[ns]
 5   IDEDET                   42007 non-null  float64
 6   TRAMA                    42007 non-null  object
 7   TIPO_MOVIMIENTO          42019 non-null  object
 8   FEC__INICIO              41570 non-null  datetime64[ns]
 9   FEC__FIN                 41544 non-null  datetime64[ns]
 10  MONEDA                   42019 non-null  object
 11  SUMA_ASEGURADA           42005 non-null  float64
 12  TASA                     42019 non-null  float64
 13  PRIMABRUTACAN            42005 non-null  float64
 14  PRIMANETACAN             42019 non-null  float64
 15  NOMBRE_DE_ARCHIVO        42007 non-null  object
 16  ORIGEN_ERROR             42019 non-null  int64
 17  TIPO_ERROR               41310 non-null  object
 18  CODIGO_ERROR             40379 non-null  object
dtypes: datetime64[ns](4), float64(5), int64(2), object(8)
memory usage: 6.1+ MB

In [170]:
df_desgravamen.head(5)

,CODIGO_PRODUCTO,LOTES_ANTERIORES,COD_DE_CERTIFICADO,FECINI_ALTA_CERTIFICADO,FECFIN_ALTA_CERTIFICADO,IDEDET,TRAMA,TIPO_MOVIMIENTO,FEC__INICIO,FEC__FIN,MONEDA,SUMA_ASEGURADA,TASA,PRIMABRUTACAN,PRIMANETACAN,NOMBRE_DE_ARCHIVO,ORIGEN_ERROR,TIPO_ERROR,CODIGO_ERROR
0,0,,NaN,NaT,NaT,289236134.0,903001104868240007432580011048681020074429601U...,Sin Movimiento,2019-03-15,2019-04-15,USD,0.0,0.0,60.65,58.88,20100130204_0157001_20190404_002.TXT,289236134,Error canal,1155
1,0,,NaN,NaT,NaT,289235584.0,903001104264440000623340011042641020015853501P...,Sin Movimiento,2019-03-01,2019-04-01,SOL,0.0,0.0,134.06,130.16,20100130204_0157001_20190404_002.TXT,289235584,Error canal,1155
2,0,,NaN,NaT,NaT,289239811.0,903001108315440008473680011012373020027799501P...,Sin Movimiento,2019-03-01,2019-04-01,SOL,0.0,0.0,148.40,144.08,20100130204_0157001_20190404_002.TXT,289239811,Error canal,1155
3,0,,NaN,NaT,NaT,289234182.0,903001103597540001035410011035974020021743001P...,Sin Movimiento,2019-03-26,2019-04-26,SOL,0.0,0.0,154.24,149.75,20100130204_0157001_20190404_002.TXT,289234182,Error canal,1155
4,0,,NaN,NaT,NaT,289240842.0,903001108794240001079510011087946020006003201P...,Sin Movimiento,2019-03-04,2019-04-04,SOL,0.0,0.0,130.00,126.21,20100130204_0157001_20190404_002.TXT,289240842,Error canal,1155

In [171]:
df_desgravamen[df_desgravamen['FECINI_ALTA_CERTIFICADO'].isnull()]['FECINI_ALTA_CERTIFICADO'].value_counts()

Series([], Name: count, dtype: int64)

In [172]:
#TIPO MOVIMIENTO
df_desgravamen['FECINI_ALTA_CERTIFICADO'].value_counts()  # Counting occurrences of each unique value in the 'TIPO MOVIMIENTO' column

FECINI_ALTA_CERTIFICADO
2013-11-29    150
2014-08-29    121
2014-09-29     95
2014-07-31     80
2014-05-29     66
             ...
2018-08-15      1
2019-07-31      1
2014-05-14      1
2014-06-09      1
2019-09-09      1
Name: count, Length: 583, dtype: int64

In [173]:
#MONEDA
df_desgravamen['MONEDA'].value_counts()  # Counting occurrences of each unique value in the 'MONEDA' column

MONEDA
SOL         39438
USD          2568
SIN DATO       13
Name: count, dtype: int64

In [174]:
df_desgravamen[df_desgravamen['MONEDA']=='SIN DATO'].head()

,CODIGO_PRODUCTO,LOTES_ANTERIORES,COD_DE_CERTIFICADO,FECINI_ALTA_CERTIFICADO,FECFIN_ALTA_CERTIFICADO,IDEDET,TRAMA,TIPO_MOVIMIENTO,FEC__INICIO,FEC__FIN,MONEDA,SUMA_ASEGURADA,TASA,PRIMABRUTACAN,PRIMANETACAN,NOMBRE_DE_ARCHIVO,ORIGEN_ERROR,TIPO_ERROR,CODIGO_ERROR
1301,3827,,0,NaT,NaT,335465001.0,9030,Sin Movimiento,NaT,NaT,SIN DATO,0.0,0.0,0.0,0.0,20100130204_0157001_20191029_003.TXT,335465001,Error canal,10
4976,0,,NaN,NaT,NaT,NaN,NaN,nan,NaT,NaT,SIN DATO,0.0,0.0,0.0,0.0,NaN,0,NaN,NaN
4978,0,,NaN,NaT,NaT,NaN,NaN,nan,NaT,NaT,SIN DATO,0.0,0.0,0.0,0.0,NaN,0,NaN,NaN
4984,0,,NaN,NaT,NaT,NaN,NaN,nan,NaT,NaT,SIN DATO,0.0,0.0,0.0,0.0,NaN,0,NaN,NaN
4986,0,,NaN,NaT,NaT,NaN,NaN,nan,NaT,NaT,SIN DATO,0.0,0.0,0.0,0.0,NaN,0,NaN,NaN

In [175]:
def extraer_fecha(fecha):
    try:
        fecha_str = fecha.split("_")[2]
        return datetime.strptime(fecha_str, "%Y%m%d").date()
    except Exception:
        return None  # En caso de error

In [176]:
# Aplicar a la columna
df_desgravamen['FECHA_TRAMA'] = df_desgravamen['NOMBRE_DE_ARCHIVO'].apply(extraer_fecha)

In [177]:
df_desgravamen['FECHA_TRAMA']= pd.to_datetime(df_desgravamen['FECHA_TRAMA'], errors='coerce')

In [178]:
def clasificar(row):
    # Si lote no esta vacio
    if str(row['LOTES_ANTERIORES']).strip() != "":
        return 'Regularizacion'
    
    # Si último número del nombre de archivo > 100
    try:
        ultimo_numero = int(row['NOMBRE_DE_ARCHIVO'].split("_")[-1][:-4])
        if ultimo_numero > 100:
            return 'Regularizacion'
    except:
        pass
    
    # Si ninguna condición se cumple
    return 'Mes corriente'

In [91]:
nombre = '20100130204_0157001_20150409_001_41924.TXT'
numero= int(nombre.split("_")[-1][:-4])
print(numero)

41924

In [179]:
#df_desgravamen['REGULARIZACION']= df_desgravamen['LOTES ANTERIORES'].notnull()
df_desgravamen['STATUS']= df_desgravamen.apply(clasificar, axis=1)

In [180]:
df_desgravamen['STATUS'].value_counts()

STATUS
Mes corriente     41792
Regularizacion      227
Name: count, dtype: int64

In [181]:
df_desgravamen.head(5)

,CODIGO_PRODUCTO,LOTES_ANTERIORES,COD_DE_CERTIFICADO,FECINI_ALTA_CERTIFICADO,FECFIN_ALTA_CERTIFICADO,IDEDET,TRAMA,TIPO_MOVIMIENTO,FEC__INICIO,FEC__FIN,...,SUMA_ASEGURADA,TASA,PRIMABRUTACAN,PRIMANETACAN,NOMBRE_DE_ARCHIVO,ORIGEN_ERROR,TIPO_ERROR,CODIGO_ERROR,FECHA_TRAMA,STATUS
0,0,,NaN,NaT,NaT,289236134.0,903001104868240007432580011048681020074429601U...,Sin Movimiento,2019-03-15,2019-04-15,...,0.0,0.0,60.65,58.88,20100130204_0157001_20190404_002.TXT,289236134,Error canal,1155,2019-04-04,Mes corriente
1,0,,NaN,NaT,NaT,289235584.0,903001104264440000623340011042641020015853501P...,Sin Movimiento,2019-03-01,2019-04-01,...,0.0,0.0,134.06,130.16,20100130204_0157001_20190404_002.TXT,289235584,Error canal,1155,2019-04-04,Mes corriente
2,0,,NaN,NaT,NaT,289239811.0,903001108315440008473680011012373020027799501P...,Sin Movimiento,2019-03-01,2019-04-01,...,0.0,0.0,148.40,144.08,20100130204_0157001_20190404_002.TXT,289239811,Error canal,1155,2019-04-04,Mes corriente
3,0,,NaN,NaT,NaT,289234182.0,903001103597540001035410011035974020021743001P...,Sin Movimiento,2019-03-26,2019-04-26,...,0.0,0.0,154.24,149.75,20100130204_0157001_20190404_002.TXT,289234182,Error canal,1155,2019-04-04,Mes corriente
4,0,,NaN,NaT,NaT,289240842.0,903001108794240001079510011087946020006003201P...,Sin Movimiento,2019-03-04,2019-04-04,...,0.0,0.0,130.00,126.21,20100130204_0157001_20190404_002.TXT,289240842,Error canal,1155,2019-04-04,Mes corriente

In [182]:
df_desgravamen[df_desgravamen['STATUS']=='Mes corriente'].head(6)

,CODIGO_PRODUCTO,LOTES_ANTERIORES,COD_DE_CERTIFICADO,FECINI_ALTA_CERTIFICADO,FECFIN_ALTA_CERTIFICADO,IDEDET,TRAMA,TIPO_MOVIMIENTO,FEC__INICIO,FEC__FIN,...,SUMA_ASEGURADA,TASA,PRIMABRUTACAN,PRIMANETACAN,NOMBRE_DE_ARCHIVO,ORIGEN_ERROR,TIPO_ERROR,CODIGO_ERROR,FECHA_TRAMA,STATUS
0,0,,NaN,NaT,NaT,289236134.0,903001104868240007432580011048681020074429601U...,Sin Movimiento,2019-03-15,2019-04-15,...,0.0,0.0,60.65,58.88,20100130204_0157001_20190404_002.TXT,289236134,Error canal,1155,2019-04-04,Mes corriente
1,0,,NaN,NaT,NaT,289235584.0,903001104264440000623340011042641020015853501P...,Sin Movimiento,2019-03-01,2019-04-01,...,0.0,0.0,134.06,130.16,20100130204_0157001_20190404_002.TXT,289235584,Error canal,1155,2019-04-04,Mes corriente
2,0,,NaN,NaT,NaT,289239811.0,903001108315440008473680011012373020027799501P...,Sin Movimiento,2019-03-01,2019-04-01,...,0.0,0.0,148.40,144.08,20100130204_0157001_20190404_002.TXT,289239811,Error canal,1155,2019-04-04,Mes corriente
3,0,,NaN,NaT,NaT,289234182.0,903001103597540001035410011035974020021743001P...,Sin Movimiento,2019-03-26,2019-04-26,...,0.0,0.0,154.24,149.75,20100130204_0157001_20190404_002.TXT,289234182,Error canal,1155,2019-04-04,Mes corriente
4,0,,NaN,NaT,NaT,289240842.0,903001108794240001079510011087946020006003201P...,Sin Movimiento,2019-03-04,2019-04-04,...,0.0,0.0,130.00,126.21,20100130204_0157001_20190404_002.TXT,289240842,Error canal,1155,2019-04-04,Mes corriente
5,0,,NaN,NaT,NaT,289241047.0,903001108968240000484430011035225010001348101P...,Sin Movimiento,2019-03-15,2019-04-15,...,0.0,0.0,347.20,337.09,20100130204_0157001_20190404_002.TXT,289241047,Error canal,1155,2019-04-04,Mes corriente

In [183]:
df_errores['CODIGO_ERROR'].value_counts()

CODIGO_ERROR
1068    1
0003    1
1155    1
1150    1
1152    1
1116    1
0114    1
7578    1
0199    1
0011    1
2395    1
1137    1
0163    1
0177    1
1154    1
0155    1
1153    1
1157    1
0117    1
1151    1
9964    1
1608    1
0193    1
0039    1
0034    1
0050    1
0940    1
0035    1
1143    1
9963    1
1045    1
0010    1
9969    1
7460    1
9978    1
7440    1
0130    1
0757    1
0141    1
0317    1
0119    1
1140    1
0852    1
0061    1
1083    1
0022    1
0005    1
1195    1
1135    1
8023    1
1052    1
        1
1136    1
Name: count, dtype: int64

In [184]:
df_errores[df_errores['CODIGO_ERROR'].isna()].head(10)

,CODIGO_ERROR,DESCRIPCION_ERROR,DETALLE,SOLUCION,SOLUCION_2
11,NaN,ERROR EN CARGA DE TRAMA,NI ÃXITO NI ERROR,ANALISIS EMISOR,

In [185]:
df_errores[df_errores['CODIGO_ERROR'].isin({'2395','7440'})].head()

,CODIGO_ERROR,DESCRIPCION_ERROR,DETALLE,SOLUCION,SOLUCION_2
10,2395,ERROR DE TASA,TASA,ANALISIS EMISOR,CONFIGURACION SAS
42,7440,ERROR EDAD,EDAD - MANCOMUNO INEXISTENTE,CONFIGURACION SAS,REGLAS POR CAMBIAR

In [186]:
df_errores[df_errores['CODIGO_ERROR']==' '].head()

,CODIGO_ERROR,DESCRIPCION_ERROR,DETALLE,SOLUCION,SOLUCION_2
62,,SIN DETALLE DE ERROR,SIN DETALLE DE ERROR,ANALISIS EMISOR,VOLVER A CARGAR

In [187]:
df_desgravamen[df_desgravamen['CODIGO_ERROR'].isna()].head(10)

,CODIGO_PRODUCTO,LOTES_ANTERIORES,COD_DE_CERTIFICADO,FECINI_ALTA_CERTIFICADO,FECFIN_ALTA_CERTIFICADO,IDEDET,TRAMA,TIPO_MOVIMIENTO,FEC__INICIO,FEC__FIN,...,SUMA_ASEGURADA,TASA,PRIMABRUTACAN,PRIMANETACAN,NOMBRE_DE_ARCHIVO,ORIGEN_ERROR,TIPO_ERROR,CODIGO_ERROR,FECHA_TRAMA,STATUS
12,3070,,00110727584000239265,NaT,NaT,289247736.0,906001107275840002392650011048600020052715501U...,Renovacion,2019-03-29,2019-04-29,...,0.00,0.00,22.77,22.11,20100130204_0157001_20190404_002.TXT,0,NaN,NaN,2019-04-04,Mes corriente
13,3070,,00110252434000017945,NaT,NaT,289244884.0,906001102524340000179450011025248020008135901P...,Renovacion,2019-03-29,2019-04-29,...,0.00,0.00,70.20,68.16,20100130204_0157001_20190404_002.TXT,0,NaN,NaN,2019-04-04,Mes corriente
14,3070,,00110781244000183779,2014-02-27,2027-02-28,289238827.0,903001107812440001837790011014012020049982601P...,Renovacion,2019-03-11,2019-04-11,...,0.00,0.00,191.80,186.21,20100130204_0157001_20190404_002.TXT,0,NaN,NaN,2019-04-04,Mes corriente
26,3827,,00110130284010524337,NaT,NaT,295967400.0,972001101302840105243370011013023969011141601P...,Inclusion,2018-12-13,2021-01-02,...,10378.68,0.48,0.00,0.00,20100130204_0157001_20190311_002.TXT,295967400,Error Rimac,NaN,2019-03-11,Mes corriente
27,3827,,00110130284010524337,NaT,NaT,295967400.0,972001101302840105243370011013023969011141601P...,Inclusion,2018-12-13,2021-01-02,...,10378.68,0.48,0.00,0.00,20100130204_0157001_20190311_002.TXT,295967400,Error Rimac,NaN,2019-03-11,Mes corriente
28,3827,,00110130284010524337,NaT,NaT,295967400.0,972001101302840105243370011013023969011141601P...,Inclusion,2018-12-13,2021-01-02,...,10378.68,0.48,0.00,0.00,20100130204_0157001_20190311_002.TXT,295967400,Error Rimac,NaN,2019-03-11,Mes corriente
29,3827,,00110130284010524337,NaT,NaT,295967400.0,972001101302840105243370011013023969011141601P...,Inclusion,2018-12-13,2021-01-02,...,10378.68,0.48,0.00,0.00,20100130204_0157001_20190311_002.TXT,295967400,Error Rimac,NaN,2019-03-11,Mes corriente
42,3070,,00110252434000017945,NaT,NaT,313042743.0,906001102524340000179450011025248020008135901P...,Renovacion,2019-07-31,2019-08-31,...,0.00,0.00,70.20,68.16,20100130204_0157001_20190806_003.TXT,313042743,Error Rimac,NaN,2019-08-06,Mes corriente
43,3070,,00110252434000017945,NaT,NaT,313042743.0,906001102524340000179450011025248020008135901P...,Renovacion,2019-07-31,2019-08-31,...,0.00,0.00,70.20,68.16,20100130204_0157001_20190806_003.TXT,313042743,Error Rimac,NaN,2019-08-06,Mes corriente
44,3070,,00110252434000017945,NaT,NaT,313042743.0,906001102524340000179450011025248020008135901P...,Renovacion,2019-07-31,2019-08-31,...,0.00,0.00,70.20,68.16,20100130204_0157001_20190806_003.TXT,313042743,Error Rimac,NaN,2019-08-06,Mes corriente

In [188]:
df_desgravamen[df_desgravamen['CODIGO_ERROR']==''].head()

Empty DataFrame
Columns: [CODIGO_PRODUCTO, LOTES_ANTERIORES, COD_DE_CERTIFICADO, FECINI_ALTA_CERTIFICADO, FECFIN_ALTA_CERTIFICADO, IDEDET, TRAMA, TIPO_MOVIMIENTO, FEC__INICIO, FEC__FIN, MONEDA, SUMA_ASEGURADA, TASA, PRIMABRUTACAN, PRIMANETACAN, NOMBRE_DE_ARCHIVO, ORIGEN_ERROR, TIPO_ERROR, CODIGO_ERROR, FECHA_TRAMA, STATUS]
Index: []

[0 rows x 21 columns]

In [189]:
df_errores.info()

<class 'pandas.core.frame.DataFrame'>
Index: 54 entries, 0 to 63
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CODIGO_ERROR       53 non-null     object
 1   DESCRIPCION_ERROR  54 non-null     object
 2   DETALLE            54 non-null     object
 3   SOLUCION           54 non-null     object
 4   SOLUCION_2         54 non-null     object
dtypes: object(5)
memory usage: 2.5+ KB

In [190]:
df= df_desgravamen.merge(df_errores, on='CODIGO_ERROR', how='left')

In [192]:
df.head(3)

,CODIGO_PRODUCTO,LOTES_ANTERIORES,COD_DE_CERTIFICADO,FECINI_ALTA_CERTIFICADO,FECFIN_ALTA_CERTIFICADO,IDEDET,TRAMA,TIPO_MOVIMIENTO,FEC__INICIO,FEC__FIN,...,NOMBRE_DE_ARCHIVO,ORIGEN_ERROR,TIPO_ERROR,CODIGO_ERROR,FECHA_TRAMA,STATUS,DESCRIPCION_ERROR,DETALLE,SOLUCION,SOLUCION_2
0,0,,NaN,NaT,NaT,289236134.0,903001104868240007432580011048681020074429601U...,Sin Movimiento,2019-03-15,2019-04-15,...,20100130204_0157001_20190404_002.TXT,289236134,Error canal,1155,2019-04-04,Mes corriente,TRAMA REPETIDA O DUPLICADA,TRAMA REPETIDA O DUPLICADA,CONFIGURACION SAS,ANULAR MASIVAS
1,0,,NaN,NaT,NaT,289235584.0,903001104264440000623340011042641020015853501P...,Sin Movimiento,2019-03-01,2019-04-01,...,20100130204_0157001_20190404_002.TXT,289235584,Error canal,1155,2019-04-04,Mes corriente,TRAMA REPETIDA O DUPLICADA,TRAMA REPETIDA O DUPLICADA,CONFIGURACION SAS,ANULAR MASIVAS
2,0,,NaN,NaT,NaT,289239811.0,903001108315440008473680011012373020027799501P...,Sin Movimiento,2019-03-01,2019-04-01,...,20100130204_0157001_20190404_002.TXT,289239811,Error canal,1155,2019-04-04,Mes corriente,TRAMA REPETIDA O DUPLICADA,TRAMA REPETIDA O DUPLICADA,CONFIGURACION SAS,ANULAR MASIVAS

In [193]:
df[df['CODIGO_ERROR'].isna()].head(10)

,CODIGO_PRODUCTO,LOTES_ANTERIORES,COD_DE_CERTIFICADO,FECINI_ALTA_CERTIFICADO,FECFIN_ALTA_CERTIFICADO,IDEDET,TRAMA,TIPO_MOVIMIENTO,FEC__INICIO,FEC__FIN,...,NOMBRE_DE_ARCHIVO,ORIGEN_ERROR,TIPO_ERROR,CODIGO_ERROR,FECHA_TRAMA,STATUS,DESCRIPCION_ERROR,DETALLE,SOLUCION,SOLUCION_2
12,3070,,00110727584000239265,NaT,NaT,289247736.0,906001107275840002392650011048600020052715501U...,Renovacion,2019-03-29,2019-04-29,...,20100130204_0157001_20190404_002.TXT,0,NaN,NaN,2019-04-04,Mes corriente,ERROR EN CARGA DE TRAMA,NI ÃXITO NI ERROR,ANALISIS EMISOR,
13,3070,,00110252434000017945,NaT,NaT,289244884.0,906001102524340000179450011025248020008135901P...,Renovacion,2019-03-29,2019-04-29,...,20100130204_0157001_20190404_002.TXT,0,NaN,NaN,2019-04-04,Mes corriente,ERROR EN CARGA DE TRAMA,NI ÃXITO NI ERROR,ANALISIS EMISOR,
14,3070,,00110781244000183779,2014-02-27,2027-02-28,289238827.0,903001107812440001837790011014012020049982601P...,Renovacion,2019-03-11,2019-04-11,...,20100130204_0157001_20190404_002.TXT,0,NaN,NaN,2019-04-04,Mes corriente,ERROR EN CARGA DE TRAMA,NI ÃXITO NI ERROR,ANALISIS EMISOR,
26,3827,,00110130284010524337,NaT,NaT,295967400.0,972001101302840105243370011013023969011141601P...,Inclusion,2018-12-13,2021-01-02,...,20100130204_0157001_20190311_002.TXT,295967400,Error Rimac,NaN,2019-03-11,Mes corriente,ERROR EN CARGA DE TRAMA,NI ÃXITO NI ERROR,ANALISIS EMISOR,
27,3827,,00110130284010524337,NaT,NaT,295967400.0,972001101302840105243370011013023969011141601P...,Inclusion,2018-12-13,2021-01-02,...,20100130204_0157001_20190311_002.TXT,295967400,Error Rimac,NaN,2019-03-11,Mes corriente,ERROR EN CARGA DE TRAMA,NI ÃXITO NI ERROR,ANALISIS EMISOR,
28,3827,,00110130284010524337,NaT,NaT,295967400.0,972001101302840105243370011013023969011141601P...,Inclusion,2018-12-13,2021-01-02,...,20100130204_0157001_20190311_002.TXT,295967400,Error Rimac,NaN,2019-03-11,Mes corriente,ERROR EN CARGA DE TRAMA,NI ÃXITO NI ERROR,ANALISIS EMISOR,
29,3827,,00110130284010524337,NaT,NaT,295967400.0,972001101302840105243370011013023969011141601P...,Inclusion,2018-12-13,2021-01-02,...,20100130204_0157001_20190311_002.TXT,295967400,Error Rimac,NaN,2019-03-11,Mes corriente,ERROR EN CARGA DE TRAMA,NI ÃXITO NI ERROR,ANALISIS EMISOR,
42,3070,,00110252434000017945,NaT,NaT,313042743.0,906001102524340000179450011025248020008135901P...,Renovacion,2019-07-31,2019-08-31,...,20100130204_0157001_20190806_003.TXT,313042743,Error Rimac,NaN,2019-08-06,Mes corriente,ERROR EN CARGA DE TRAMA,NI ÃXITO NI ERROR,ANALISIS EMISOR,
43,3070,,00110252434000017945,NaT,NaT,313042743.0,906001102524340000179450011025248020008135901P...,Renovacion,2019-07-31,2019-08-31,...,20100130204_0157001_20190806_003.TXT,313042743,Error Rimac,NaN,2019-08-06,Mes corriente,ERROR EN CARGA DE TRAMA,NI ÃXITO NI ERROR,ANALISIS EMISOR,
44,3070,,00110252434000017945,NaT,NaT,313042743.0,906001102524340000179450011025248020008135901P...,Renovacion,2019-07-31,2019-08-31,...,20100130204_0157001_20190806_003.TXT,313042743,Error Rimac,NaN,2019-08-06,Mes corriente,ERROR EN CARGA DE TRAMA,NI ÃXITO NI ERROR,ANALISIS EMISOR,

In [194]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42019 entries, 0 to 42018
Data columns (total 25 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   CODIGO_PRODUCTO          42019 non-null  int64
 1   LOTES_ANTERIORES         42019 non-null  object
 2   COD_DE_CERTIFICADO       6959 non-null   object
 3   FECINI_ALTA_CERTIFICADO  2866 non-null   datetime64[ns]
 4   FECFIN_ALTA_CERTIFICADO  2866 non-null   datetime64[ns]
 5   IDEDET                   42007 non-null  float64
 6   TRAMA                    42007 non-null  object
 7   TIPO_MOVIMIENTO          42019 non-null  object
 8   FEC__INICIO              41570 non-null  datetime64[ns]
 9   FEC__FIN                 41544 non-null  datetime64[ns]
 10  MONEDA                   42019 non-null  object
 11  SUMA_ASEGURADA           42005 non-null  float64
 12  TASA                     42019 non-null  float64
 13  PRIMABRUTACAN            42005 non-null  float64
 14  PRIMANETACAN             42019 non-null  float64
 15  NOMBRE_DE_ARCHIVO        42007 non-null  object
 16  ORIGEN_ERROR             42019 non-null  int64
 17  TIPO_ERROR               41310 non-null  object
 18  CODIGO_ERROR             40379 non-null  object
 19  FECHA_TRAMA              42007 non-null  datetime64[ns]
 20  STATUS                   42019 non-null  object
 21  DESCRIPCION_ERROR        2541 non-null   object
 22  DETALLE                  2541 non-null   object
 23  SOLUCION                 2541 non-null   object
 24  SOLUCION_2               2541 non-null   object
dtypes: datetime64[ns](5), float64(5), int64(2), object(13)
memory usage: 8.0+ MB