In [7]:
import pandas as pd
from datetime import datetime
import warnings
warnings.filterwarnings("ignore", category=UserWarning, module="openpyxl")

In [100]:
df_errores= pd.read_csv('c:/data/tabla_errores.txt', sep='\t', encoding='latin1')
df_errores.head(3)

,CODIGO_ERROR,DESCRIPCION_ERROR,DETALLE,SOLUCION,SOLUCION 2
0,1068,YA EXISTE UN PAGO CON LA MISMA FECHA DE INICIO...,YA EXISTE UN PAGO CON LA MISMA FECHA DE INICIO...,CONFIGURACION SAS,ANULAR MASIVAS
1,0003,ERROR EN CARGA DE TRAMA,ERROR EN CARGA DE TRAMA,ANALISIS EMISOR,NaN
2,1155,TRAMA REPETIDA O DUPLICADA,TRAMA REPETIDA O DUPLICADA,CONFIGURACION SAS,ANULAR MASIVAS

In [101]:
df_errores= df_errores.dropna(subset=['CODIGO_ERROR']) # Elimina filas con CODIGO_ERROR nulo

In [104]:
df_errores= df_errores.rename(columns={'SOLUCION 2': 'SOLUCION_2'}) # cambiar nombre de las columnas
df_errores= df_errores.fillna({'SOLUCION_2':''})

In [105]:
df_errores.info()

<class 'pandas.core.frame.DataFrame'>
Index: 55 entries, 0 to 63
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CODIGO_ERROR       55 non-null     object
 1   DESCRIPCION_ERROR  55 non-null     object
 2   DETALLE            55 non-null     object
 3   SOLUCION           55 non-null     object
 4   SOLUCION_2         55 non-null     object
dtypes: object(5)
memory usage: 2.6+ KB

In [63]:
# Se carga el dataset en excel de Accidentes mortales
df_desgravamen= pd.read_excel('C:/data/446 - Desgravamen Desempleo - BBVA - P1.xlsx', sheet_name='Hoja1')

In [64]:
df_desgravamen.columns = (
    df_desgravamen.columns
    .str.strip()  # quitar espacios al inicio/fin
    .str.upper()  # opcional: todo en mayúsculas
    .str.replace(r'[^A-Za-z0-9_]', '_', regex=True)  # reemplazar todo lo que no sea letra/número/_ por _
)

In [65]:
df_desgravamen= df_desgravamen.rename(columns={'CODIGO_ERROR': 'TIPO_ERROR','DESCRIPCION_ERROR': 'CODIGO_ERROR'}) # cambiar nombre de las columnas

In [66]:
df_desgravamen= df_desgravamen[['CODIGO_PRODUCTO', 'LOTES_ANTERIORES','COD_DE_CERTIFICADO', 'FECINI_ALTA_CERTIFICADO', 
                                'FECFIN_ALTA_CERTIFICADO','IDEDET', 'TIPO_MOVIMIENTO', 'FEC__INICIO', 'FEC__FIN', 'MONEDA', 
                                'SUMA_ASEGURADA', 'TASA', 'PRIMABRUTACAN', 'PRIMANETACAN', 'NOMBRE_DE_ARCHIVO', 
                                'ORIGEN_ERROR', 'TIPO_ERROR', 'CODIGO_ERROR']]

In [67]:
df_desgravamen.head(3)  # Displaying the first five rows of the DataFrame

,CODIGO_PRODUCTO,LOTES_ANTERIORES,COD_DE_CERTIFICADO,FECINI_ALTA_CERTIFICADO,FECFIN_ALTA_CERTIFICADO,IDEDET,TIPO_MOVIMIENTO,FEC__INICIO,FEC__FIN,MONEDA,SUMA_ASEGURADA,TASA,PRIMABRUTACAN,PRIMANETACAN,NOMBRE_DE_ARCHIVO,ORIGEN_ERROR,TIPO_ERROR,CODIGO_ERROR
0,3070.0,41924|41960,1.102912e+17,NaN,NaN,76792662,Renovacion,2015-03-26 00:00:00,2015-04-26 00:00:00,SOL,0,0,1.53,1.49,20100130204_0157001_20150409_001_41924.TXT,76792662.0,Error canal,1150.0
1,3070.0,41924|41960,1.102771e+17,NaN,NaN,76792295,Renovacion,2015-03-20 00:00:00,2015-04-20 00:00:00,SOL,0,0,13.13,12.75,20100130204_0157001_20150409_001_41924.TXT,76792295.0,Error canal,1150.0
2,3070.0,41924|41960,1.103549e+17,NaN,NaN,76795338,Renovacion,2015-03-12 00:00:00,2015-04-12 00:00:00,SOL,0,0,6.23,6.05,20100130204_0157001_20150409_001_41924.TXT,76795338.0,Error canal,1150.0

In [68]:
df_desgravamen.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50659 entries, 0 to 50658
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   CODIGO_PRODUCTO          48852 non-null  float64
 1   LOTES_ANTERIORES         91 non-null     object
 2   COD_DE_CERTIFICADO       48852 non-null  float64
 3   FECINI_ALTA_CERTIFICADO  33562 non-null  object
 4   FECFIN_ALTA_CERTIFICADO  33562 non-null  object
 5   IDEDET                   50659 non-null  int64
 6   TIPO_MOVIMIENTO          50659 non-null  object
 7   FEC__INICIO              50658 non-null  object
 8   FEC__FIN                 50658 non-null  object
 9   MONEDA                   50658 non-null  object
 10  SUMA_ASEGURADA           50659 non-null  object
 11  TASA                     50659 non-null  object
 12  PRIMABRUTACAN            50659 non-null  object
 13  PRIMANETACAN             50659 non-null  float64
 14  NOMBRE_DE_ARCHIVO        50659 non-null  object
 15  ORIGEN_ERROR             28833 non-null  float64
 16  TIPO_ERROR               28833 non-null  object
 17  CODIGO_ERROR             26946 non-null  float64
dtypes: float64(5), int64(1), object(12)
memory usage: 7.0+ MB

In [70]:
df_desgravamen[df_desgravamen['CODIGO_PRODUCTO'].isnull()].head()

,CODIGO_PRODUCTO,LOTES_ANTERIORES,COD_DE_CERTIFICADO,FECINI_ALTA_CERTIFICADO,FECFIN_ALTA_CERTIFICADO,IDEDET,TIPO_MOVIMIENTO,FEC__INICIO,FEC__FIN,MONEDA,SUMA_ASEGURADA,TASA,PRIMABRUTACAN,PRIMANETACAN,NOMBRE_DE_ARCHIVO,ORIGEN_ERROR,TIPO_ERROR,CODIGO_ERROR
7,NaN,NaN,NaN,NaN,NaN,142337287,Sin Movimiento,2016-06-30 00:00:00,2016-07-31 00:00:00,SOL,0,0,330.67,321.04,20100130204_0157001_20160706_002.TXT,142337287.0,Error canal,1155.0
9,NaN,NaN,NaN,NaN,NaN,142268938,Sin Movimiento,2016-06-30 00:00:00,2016-07-31 00:00:00,SOL,0,0,57.96,56.27,20100130204_0157001_20160706_002.TXT,142268938.0,Error canal,1155.0
21,NaN,NaN,NaN,NaN,NaN,132976876,Sin Movimiento,2010-07-20 00:00:00,2015-07-02 00:00:00,SOL,54032.75,0.27,14.59,14.17,20100130204_0157001_20160519_005.TXT,132976876.0,Error canal,1155.0
22,NaN,NaN,NaN,NaN,NaN,132976877,Sin Movimiento,2016-03-31 00:00:00,2031-03-31 00:00:00,USD,300000,0.52,156,151.46,20100130204_0157001_20160519_005.TXT,132976877.0,Error canal,193.0
23,NaN,NaN,NaN,NaN,NaN,132976878,Sin Movimiento,2016-03-31 00:00:00,2031-03-31 00:00:00,USD,300000,0.52,156,151.46,20100130204_0157001_20160519_005.TXT,132976878.0,Error canal,1155.0

In [71]:
df_desgravamen= df_desgravamen.fillna({'LOTES_ANTERIORES':'', 'SUMA_ASEGURADA':0, 'TASA':0, 'PRIMABRUTACAN':0, 'PRIMANETACAN':0,
                                       'MONEDA': 'SIN DATO'})

In [72]:
df_desgravamen['COD_DE_CERTIFICADO'] = df_desgravamen['COD_DE_CERTIFICADO'].apply(lambda x: str(int(x)) if pd.notnull(x) else '0')
df_desgravamen['CODIGO_PRODUCTO'] = df_desgravamen['CODIGO_PRODUCTO'].fillna(0).astype('int')
df_desgravamen["LOTES_ANTERIORES"] = df_desgravamen["LOTES_ANTERIORES"].astype(str)
df_desgravamen['FECINI_ALTA_CERTIFICADO'] = pd.to_datetime(df_desgravamen['FECINI_ALTA_CERTIFICADO'], errors='coerce')
df_desgravamen['FECFIN_ALTA_CERTIFICADO'] = pd.to_datetime(df_desgravamen['FECFIN_ALTA_CERTIFICADO'], errors='coerce')
df_desgravamen['TIPO_MOVIMIENTO'] = df_desgravamen['TIPO_MOVIMIENTO'].astype(str)
df_desgravamen['FEC__INICIO'] = pd.to_datetime(df_desgravamen['FEC__INICIO'], format='%d/%m/%Y', errors='coerce')
df_desgravamen['FEC__FIN'] = pd.to_datetime(df_desgravamen['FEC__FIN'], format='%d/%m/%Y', errors='coerce')
df_desgravamen['MONEDA'] = df_desgravamen['MONEDA'].astype(str)
df_desgravamen['SUMA_ASEGURADA']= pd.to_numeric(df_desgravamen['SUMA_ASEGURADA'], errors='coerce')
df_desgravamen['TASA']= pd.to_numeric(df_desgravamen['TASA'], errors='coerce')
df_desgravamen['PRIMABRUTACAN']= pd.to_numeric(df_desgravamen['PRIMABRUTACAN'], errors='coerce')
df_desgravamen['PRIMANETACAN']= pd.to_numeric(df_desgravamen['PRIMANETACAN'], errors='coerce')
df_desgravamen['ORIGEN_ERROR'] = df_desgravamen['ORIGEN_ERROR'].fillna(0).astype('int')
df_desgravamen['CODIGO_ERROR'] = df_desgravamen['CODIGO_ERROR'].fillna(0).astype('int')

In [73]:
df_desgravamen['MONEDA'] = df_desgravamen['MONEDA'].replace('nan', 'SIN DATO')

In [74]:
df_desgravamen.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50659 entries, 0 to 50658
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   CODIGO_PRODUCTO          50659 non-null  int64
 1   LOTES_ANTERIORES         50659 non-null  object
 2   COD_DE_CERTIFICADO       50659 non-null  object
 3   FECINI_ALTA_CERTIFICADO  33562 non-null  datetime64[ns]
 4   FECFIN_ALTA_CERTIFICADO  33562 non-null  datetime64[ns]
 5   IDEDET                   50659 non-null  int64
 6   TIPO_MOVIMIENTO          50659 non-null  object
 7   FEC__INICIO              50142 non-null  datetime64[ns]
 8   FEC__FIN                 50142 non-null  datetime64[ns]
 9   MONEDA                   50659 non-null  object
 10  SUMA_ASEGURADA           50146 non-null  float64
 11  TASA                     50657 non-null  float64
 12  PRIMABRUTACAN            50151 non-null  float64
 13  PRIMANETACAN             50659 non-null  float64
 14  NOMBRE_DE_ARCHIVO        50659 non-null  object
 15  ORIGEN_ERROR             50659 non-null  int64
 16  TIPO_ERROR               28833 non-null  object
 17  CODIGO_ERROR             50659 non-null  int64
dtypes: datetime64[ns](4), float64(4), int64(4), object(6)
memory usage: 7.0+ MB

In [75]:
df_desgravamen.head(5)

,CODIGO_PRODUCTO,LOTES_ANTERIORES,COD_DE_CERTIFICADO,FECINI_ALTA_CERTIFICADO,FECFIN_ALTA_CERTIFICADO,IDEDET,TIPO_MOVIMIENTO,FEC__INICIO,FEC__FIN,MONEDA,SUMA_ASEGURADA,TASA,PRIMABRUTACAN,PRIMANETACAN,NOMBRE_DE_ARCHIVO,ORIGEN_ERROR,TIPO_ERROR,CODIGO_ERROR
0,3070,41924|41960,110291214000143008,NaT,NaT,76792662,Renovacion,2015-03-26,2015-04-26,SOL,0.0,0.0,1.53,1.49,20100130204_0157001_20150409_001_41924.TXT,76792662,Error canal,1150
1,3070,41924|41960,110277104000246000,NaT,NaT,76792295,Renovacion,2015-03-20,2015-04-20,SOL,0.0,0.0,13.13,12.75,20100130204_0157001_20150409_001_41924.TXT,76792295,Error canal,1150
2,3070,41924|41960,110354884000092000,NaT,NaT,76795338,Renovacion,2015-03-12,2015-04-12,SOL,0.0,0.0,6.23,6.05,20100130204_0157001_20150409_001_41924.TXT,76795338,Error canal,1150
3,3070,41924|41960,110195594000396992,NaT,NaT,76787274,Renovacion,2015-03-18,2015-04-18,SOL,0.0,0.0,0.44,0.43,20100130204_0157001_20150409_001_41924.TXT,76787274,Error canal,1150
4,3827,,110960264000002000,NaT,NaT,142143999,Renovacion,2016-06-06,2016-07-06,USD,0.0,0.0,8.99,8.73,20100130204_0157001_20160706_002.TXT,142143999,Error canal,1152

In [76]:
df_desgravamen[df_desgravamen['FECINI_ALTA_CERTIFICADO'].isnull()]['FECINI_ALTA_CERTIFICADO'].value_counts()

Series([], Name: count, dtype: int64)

In [77]:
#TIPO MOVIMIENTO
df_desgravamen['FECINI_ALTA_CERTIFICADO'].value_counts()  # Counting occurrences of each unique value in the 'TIPO MOVIMIENTO' column

FECINI_ALTA_CERTIFICADO
2015-03-31    134
2014-12-30    124
2015-05-29    114
2015-10-30    106
2015-07-31    105
             ...
2012-08-23      1
2013-01-08      1
2013-05-08      1
2013-03-11      1
2017-01-15      1
Name: count, Length: 1161, dtype: int64

In [78]:
#MONEDA
df_desgravamen['MONEDA'].value_counts()  # Counting occurrences of each unique value in the 'MONEDA' column

MONEDA
SOL         46356
USD          4302
SIN DATO        1
Name: count, dtype: int64

In [79]:
df_desgravamen[df_desgravamen['MONEDA']=='SIN DATO'].head()

,CODIGO_PRODUCTO,LOTES_ANTERIORES,COD_DE_CERTIFICADO,FECINI_ALTA_CERTIFICADO,FECFIN_ALTA_CERTIFICADO,IDEDET,TIPO_MOVIMIENTO,FEC__INICIO,FEC__FIN,MONEDA,SUMA_ASEGURADA,TASA,PRIMABRUTACAN,PRIMANETACAN,NOMBRE_DE_ARCHIVO,ORIGEN_ERROR,TIPO_ERROR,CODIGO_ERROR
46033,0,,0,NaT,NaT,132857441,Sin Movimiento,NaT,NaT,SIN DATO,0.0,0.0,0.0,0.0,20100130204_0157001_20160511_001.TXT,132857441,Error canal,193

In [80]:
def extraer_fecha(fecha):
    try:
        fecha_str = fecha.split("_")[2]
        return datetime.strptime(fecha_str, "%Y%m%d").date()
    except Exception:
        return None  # En caso de error

In [81]:
# Aplicar a la columna
df_desgravamen['FECHA_TRAMA'] = df_desgravamen['NOMBRE_DE_ARCHIVO'].apply(extraer_fecha)

In [82]:
df_desgravamen['FECHA_TRAMA']= pd.to_datetime(df_desgravamen['FECHA_TRAMA'], errors='coerce')

In [83]:
def clasificar(row):
    # Si lote no es nulo
    if str(row['LOTES_ANTERIORES']).strip() != "":
        return 'Regularizacion'
    
    # Si último número del nombre de archivo > 100
    try:
        ultimo_numero = int(row['NOMBRE_DE_ARCHIVO'].split("_")[-1][:-4])
        if ultimo_numero > 100:
            return 'Regularizacion'
    except:
        pass
    
    # Si ninguna condición se cumple
    return 'Mes corriente'

In [84]:
nombre = '20100130204_0157001_20150409_001_41924.TXT'
numero= int(nombre.split("_")[-1][:-4])
print(numero)

41924

In [85]:
#df_desgravamen['REGULARIZACION']= df_desgravamen['LOTES ANTERIORES'].notnull()
df_desgravamen['STATUS']= df_desgravamen.apply(clasificar, axis=1)

In [86]:
df_desgravamen['STATUS'].value_counts()

STATUS
Mes corriente     50541
Regularizacion      118
Name: count, dtype: int64

In [87]:
df_desgravamen.head(6)

,CODIGO_PRODUCTO,LOTES_ANTERIORES,COD_DE_CERTIFICADO,FECINI_ALTA_CERTIFICADO,FECFIN_ALTA_CERTIFICADO,IDEDET,TIPO_MOVIMIENTO,FEC__INICIO,FEC__FIN,MONEDA,SUMA_ASEGURADA,TASA,PRIMABRUTACAN,PRIMANETACAN,NOMBRE_DE_ARCHIVO,ORIGEN_ERROR,TIPO_ERROR,CODIGO_ERROR,FECHA_TRAMA,STATUS
0,3070,41924|41960,110291214000143008,NaT,NaT,76792662,Renovacion,2015-03-26,2015-04-26,SOL,0.0,0.0,1.53,1.49,20100130204_0157001_20150409_001_41924.TXT,76792662,Error canal,1150,2015-04-09,Regularizacion
1,3070,41924|41960,110277104000246000,NaT,NaT,76792295,Renovacion,2015-03-20,2015-04-20,SOL,0.0,0.0,13.13,12.75,20100130204_0157001_20150409_001_41924.TXT,76792295,Error canal,1150,2015-04-09,Regularizacion
2,3070,41924|41960,110354884000092000,NaT,NaT,76795338,Renovacion,2015-03-12,2015-04-12,SOL,0.0,0.0,6.23,6.05,20100130204_0157001_20150409_001_41924.TXT,76795338,Error canal,1150,2015-04-09,Regularizacion
3,3070,41924|41960,110195594000396992,NaT,NaT,76787274,Renovacion,2015-03-18,2015-04-18,SOL,0.0,0.0,0.44,0.43,20100130204_0157001_20150409_001_41924.TXT,76787274,Error canal,1150,2015-04-09,Regularizacion
4,3827,,110960264000002000,NaT,NaT,142143999,Renovacion,2016-06-06,2016-07-06,USD,0.0,0.0,8.99,8.73,20100130204_0157001_20160706_002.TXT,142143999,Error canal,1152,2016-07-06,Mes corriente
5,3827,,110554314000032992,NaT,NaT,142049999,Renovacion,2016-06-10,2016-07-10,SOL,0.0,0.0,183.03,177.70,20100130204_0157001_20160706_002.TXT,142049999,Error canal,1152,2016-07-06,Mes corriente

In [88]:
df_desgravamen[df_desgravamen['STATUS']=='Mes corriente'].head(6)

,CODIGO_PRODUCTO,LOTES_ANTERIORES,COD_DE_CERTIFICADO,FECINI_ALTA_CERTIFICADO,FECFIN_ALTA_CERTIFICADO,IDEDET,TIPO_MOVIMIENTO,FEC__INICIO,FEC__FIN,MONEDA,SUMA_ASEGURADA,TASA,PRIMABRUTACAN,PRIMANETACAN,NOMBRE_DE_ARCHIVO,ORIGEN_ERROR,TIPO_ERROR,CODIGO_ERROR,FECHA_TRAMA,STATUS
4,3827,,110960264000002000,NaT,NaT,142143999,Renovacion,2016-06-06,2016-07-06,USD,0.0,0.0,8.99,8.73,20100130204_0157001_20160706_002.TXT,142143999,Error canal,1152,2016-07-06,Mes corriente
5,3827,,110554314000032992,NaT,NaT,142049999,Renovacion,2016-06-10,2016-07-10,SOL,0.0,0.0,183.03,177.70,20100130204_0157001_20160706_002.TXT,142049999,Error canal,1152,2016-07-06,Mes corriente
6,3827,,110285464000440992,NaT,NaT,141890380,Renovacion,2016-06-30,2016-07-31,USD,0.0,0.0,29.07,28.22,20100130204_0157001_20160706_002.TXT,141890380,Error canal,1152,2016-07-06,Mes corriente
7,0,,0,NaT,NaT,142337287,Sin Movimiento,2016-06-30,2016-07-31,SOL,0.0,0.0,330.67,321.04,20100130204_0157001_20160706_002.TXT,142337287,Error canal,1155,2016-07-06,Mes corriente
8,3827,,110358914000162000,2016-03-18,2016-06-18,142328819,Renovacion,2016-06-20,2016-07-20,SOL,0.0,0.0,490.04,475.77,20100130204_0157001_20160706_002.TXT,142328819,Error canal,1140,2016-07-06,Mes corriente
9,0,,0,NaT,NaT,142268938,Sin Movimiento,2016-06-30,2016-07-31,SOL,0.0,0.0,57.96,56.27,20100130204_0157001_20160706_002.TXT,142268938,Error canal,1155,2016-07-06,Mes corriente

In [106]:
df_errores['CODIGO_ERROR'].value_counts()

CODIGO_ERROR
2395    2
7440    2
0003    1
1150    1
1155    1
1152    1
1116    1
7578    1
0114    1
0199    1
0011    1
1137    1
0163    1
0177    1
1154    1
0155    1
1153    1
1157    1
0117    1
1151    1
1068    1
9964    1
1608    1
0039    1
0193    1
0050    1
0940    1
0035    1
0034    1
1143    1
9963    1
0010    1
1045    1
9969    1
7460    1
9978    1
0130    1
0757    1
0141    1
0317    1
0119    1
1140    1
0852    1
0061    1
1083    1
0022    1
0005    1
1195    1
1135    1
8023    1
1052    1
        1
1136    1
Name: count, dtype: int64

In [107]:
df_errores[df_errores['CODIGO_ERROR'].isin({'2395','7440'})].head()

,CODIGO_ERROR,DESCRIPCION_ERROR,DETALLE,SOLUCION,SOLUCION_2
10,2395,ERROR DE TASA,TASA,ANALISIS EMISOR,CONFIGURACION SAS
23,2395,ERROR DE TASA,TASA (EN BLANCO) (PROD VIEJO),ANALISIS EMISOR,CONFIGURACION SAS
42,7440,ERROR EDAD,EDAD - MANCOMUNO INEXISTENTE,CONFIGURACION SAS,REGLAS POR CAMBIAR
44,7440,ERROR EDAD,EDAD - MANCOMUNO,CONFIGURACION SAS,REGLAS POR CAMBIAR

In [108]:
df_errores= df_errores.drop_duplicates(subset=['CODIGO_ERROR'])

In [109]:
df_errores[df_errores['CODIGO_ERROR'].isin({'2395','7440'})].head()

,CODIGO_ERROR,DESCRIPCION_ERROR,DETALLE,SOLUCION,SOLUCION_2
10,2395,ERROR DE TASA,TASA,ANALISIS EMISOR,CONFIGURACION SAS
42,7440,ERROR EDAD,EDAD - MANCOMUNO INEXISTENTE,CONFIGURACION SAS,REGLAS POR CAMBIAR

In [110]:
df_errores[df_errores['CODIGO_ERROR']==' '].head()

,CODIGO_ERROR,DESCRIPCION_ERROR,DETALLE,SOLUCION,SOLUCION_2
62,,SIN DETALLE DE ERROR,SIN DETALLE DE ERROR,ANALISIS EMISOR,VOLVER A CARGAR

In [111]:
df_errores[df_errores['CODIGO_ERROR']==' '] = 0

In [112]:
df_errores.info()

<class 'pandas.core.frame.DataFrame'>
Index: 53 entries, 0 to 63
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CODIGO_ERROR       53 non-null     object
 1   DESCRIPCION_ERROR  53 non-null     object
 2   DETALLE            53 non-null     object
 3   SOLUCION           53 non-null     object
 4   SOLUCION_2         53 non-null     object
dtypes: object(5)
memory usage: 2.5+ KB

In [113]:
df_errores['CODIGO_ERROR']= df_errores['CODIGO_ERROR'].astype('int')

In [114]:
df= df_desgravamen.merge(df_errores, on='CODIGO_ERROR', how='left')

In [115]:
df.head(10)

,CODIGO_PRODUCTO,LOTES_ANTERIORES,COD_DE_CERTIFICADO,FECINI_ALTA_CERTIFICADO,FECFIN_ALTA_CERTIFICADO,IDEDET,TIPO_MOVIMIENTO,FEC__INICIO,FEC__FIN,MONEDA,...,NOMBRE_DE_ARCHIVO,ORIGEN_ERROR,TIPO_ERROR,CODIGO_ERROR,FECHA_TRAMA,STATUS,DESCRIPCION_ERROR,DETALLE,SOLUCION,SOLUCION_2
0,3070,41924|41960,110291214000143008,NaT,NaT,76792662,Renovacion,2015-03-26,2015-04-26,SOL,...,20100130204_0157001_20150409_001_41924.TXT,76792662,Error canal,1150,2015-04-09,Regularizacion,ERROR EN ALTA,EL ALTA DEL NRO. CERTIFICADO EXTERNO SE ENCUEN...,ANALISIS EMISOR,
1,3070,41924|41960,110277104000246000,NaT,NaT,76792295,Renovacion,2015-03-20,2015-04-20,SOL,...,20100130204_0157001_20150409_001_41924.TXT,76792295,Error canal,1150,2015-04-09,Regularizacion,ERROR EN ALTA,EL ALTA DEL NRO. CERTIFICADO EXTERNO SE ENCUEN...,ANALISIS EMISOR,
2,3070,41924|41960,110354884000092000,NaT,NaT,76795338,Renovacion,2015-03-12,2015-04-12,SOL,...,20100130204_0157001_20150409_001_41924.TXT,76795338,Error canal,1150,2015-04-09,Regularizacion,ERROR EN ALTA,EL ALTA DEL NRO. CERTIFICADO EXTERNO SE ENCUEN...,ANALISIS EMISOR,
3,3070,41924|41960,110195594000396992,NaT,NaT,76787274,Renovacion,2015-03-18,2015-04-18,SOL,...,20100130204_0157001_20150409_001_41924.TXT,76787274,Error canal,1150,2015-04-09,Regularizacion,ERROR EN ALTA,EL ALTA DEL NRO. CERTIFICADO EXTERNO SE ENCUEN...,ANALISIS EMISOR,
4,3827,,110960264000002000,NaT,NaT,142143999,Renovacion,2016-06-06,2016-07-06,USD,...,20100130204_0157001_20160706_002.TXT,142143999,Error canal,1152,2016-07-06,Mes corriente,ERROR EN ALTA,NO EXISTE ALTA PARA EL CERTIFICADO O TIENE BAJ...,ANALISIS EMISOR,
5,3827,,110554314000032992,NaT,NaT,142049999,Renovacion,2016-06-10,2016-07-10,SOL,...,20100130204_0157001_20160706_002.TXT,142049999,Error canal,1152,2016-07-06,Mes corriente,ERROR EN ALTA,NO EXISTE ALTA PARA EL CERTIFICADO O TIENE BAJ...,ANALISIS EMISOR,
6,3827,,110285464000440992,NaT,NaT,141890380,Renovacion,2016-06-30,2016-07-31,USD,...,20100130204_0157001_20160706_002.TXT,141890380,Error canal,1152,2016-07-06,Mes corriente,ERROR EN ALTA,NO EXISTE ALTA PARA EL CERTIFICADO O TIENE BAJ...,ANALISIS EMISOR,
7,0,,0,NaT,NaT,142337287,Sin Movimiento,2016-06-30,2016-07-31,SOL,...,20100130204_0157001_20160706_002.TXT,142337287,Error canal,1155,2016-07-06,Mes corriente,TRAMA REPETIDA O DUPLICADA,TRAMA REPETIDA O DUPLICADA,CONFIGURACION SAS,ANULAR MASIVAS
8,3827,,110358914000162000,2016-03-18,2016-06-18,142328819,Renovacion,2016-06-20,2016-07-20,SOL,...,20100130204_0157001_20160706_002.TXT,142328819,Error canal,1140,2016-07-06,Mes corriente,ERROR VIGENCIA,ERROR VIGENCIA,ANALISIS EMISOR,
9,0,,0,NaT,NaT,142268938,Sin Movimiento,2016-06-30,2016-07-31,SOL,...,20100130204_0157001_20160706_002.TXT,142268938,Error canal,1155,2016-07-06,Mes corriente,TRAMA REPETIDA O DUPLICADA,TRAMA REPETIDA O DUPLICADA,CONFIGURACION SAS,ANULAR MASIVAS