In [2]:
import pandas as pd
from datetime import datetime
import warnings
warnings.filterwarnings("ignore", category=UserWarning, module="openpyxl")
import os
import numpy as np
pd.set_option('display.max_columns', None)

In [26]:
df_errores= pd.read_excel('c:/data/tabla_errores2.xlsx', sheet_name='Sheet1', dtype={'CODIGO_ERROR': str, 'IDEERROR': str})
df_errores.head(3)

,IDEERROR,CODIGO_ERROR,DESCRIPCION_ERROR,DETALLE,SOLUCION,SOLUCION_2
0,0974,1068,YA EXISTE UN PAGO CON LA MISMA FECHA DE INICIO...,YA EXISTE UN PAGO CON LA MISMA FECHA DE INICIO...,CONFIGURACION SAS,ANULAR MASIVAS
1,0005,0003,ERROR EN CARGA DE TRAMA,ERROR EN CARGA DE TRAMA,ANALISIS EMISOR,NaN
2,1158,1155,TRAMA REPETIDA O DUPLICADA,TRAMA REPETIDA O DUPLICADA,CONFIGURACION SAS,ANULAR MASIVAS

In [27]:
df_errores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   IDEERROR           53 non-null     object
 1   CODIGO_ERROR       53 non-null     object
 2   DESCRIPCION_ERROR  54 non-null     object
 3   DETALLE            54 non-null     object
 4   SOLUCION           54 non-null     object
 5   SOLUCION_2         19 non-null     object
dtypes: object(6)
memory usage: 2.7+ KB

In [ ]:
#df_equivalencias= pd.read_excel('c:/data/Tabla_equivalencias.xlsx', sheet_name='Sheet1', dtype={'IDEERROR': str, 'CODERROR': str})
#df_equivalencias= df_equivalencias[['IDEERROR', 'CODERROR']]
#df_equivalencias.rename(columns={'CODERROR': 'CODIGO_ERROR'}, inplace=True)
#df_equivalencias.head(3)

  IDEERROR CODIGO_ERROR
0     0092         0050
1     0097         0114
2     0101         0117

In [ ]:
#df_errores = df_errores.merge(df_equivalencias, on='CODIGO_ERROR', how='left')
#col = df_errores.pop("IDEERROR")          # Sacamos la columna
#df_errores.insert(0, "IDEERROR", col)     # La insertamos en la primera posición
#df_errores.head(2)

,IDEERROR,CODIGO_ERROR,DESCRIPCION_ERROR,DETALLE,SOLUCION,SOLUCION_2
0,0974,1068,YA EXISTE UN PAGO CON LA MISMA FECHA DE INICIO...,YA EXISTE UN PAGO CON LA MISMA FECHA DE INICIO...,CONFIGURACION SAS,ANULAR MASIVAS
1,0005,0003,ERROR EN CARGA DE TRAMA,ERROR EN CARGA DE TRAMA,ANALISIS EMISOR,NaN

In [ ]:
#df_errores.to_excel('c:/data/tabla_errores2.xlsx', index=False)

In [115]:
# Se carga el dataset en excel de Accidentes mortales
df_desgravamen= pd.read_excel('C:/data/Reporte de errores/446 - Desgravamen - 03.xlsx', sheet_name='Sheet1', 
                              dtype={'COD DE CERTIFICADO': str, 'DESCRIPCION ERROR': str, 'IDELOTE': str, 'CODIGO ERROR': str})

In [116]:
df_desgravamen.head(3)

,NRO LOTE,LOTES ANTERIORES,FECHA CARGA,CODIGO PRODUCTO,PRODUCTO,CODIGO PLAN,NOMBRE DE PLAN,COD DE CERTIFICADO,fecini_alta_CERTIFICADO,fecfin_alta_CERTIFICADO,IDEDET,TIPO MOVIMIENTO,FEC. INICIO,FEC. FIN,MONEDA,SUMA ASEGURADA,TASA,TASA RECARGO,PRIMABRUTACAN,PRIMANETACAN,NOMCOMPLETO,APEPATERNO,APEMATERNO,FECNACIMIENTO,TIPDOCUMENTO,NUMDOCUMENTO,NOMBRE DE ARCHIVO,LINEA TRAMA,IDELOTE,IDEDET.1,ORIGEN ERROR,CODIGO ERROR,DESCRIPCION ERROR
0,872654,NaN,2022-10-25 17:52:43,3827.0,Desgravamen + Desempleo BBVA,89705.0,Plan Contifacil,00110814174001203143,2019-12-30,2022-12-30,556035505,Exclusion,30/12/2019,30/12/2022,SOL,2800.0,0.35,0.35,0.98,0.95,NEISER,IPARRAGUIRRE,MU?OZ,19880329.0,2.0,44994753,20100130204_0157001_20201122_101.TXT,901001108141740012031430011081410960091807101P...,872654,556035505,Error canal,986,EL NUMERO DE CERTIFICADO [00110814174001203143...
1,872654,NaN,2022-10-25 17:52:43,3827.0,Desgravamen + Desempleo BBVA,89705.0,Plan Contifacil,00110814174001203143,2019-12-30,2022-12-30,556035505,Exclusion,30/12/2019,30/12/2022,SOL,2800.0,0.35,0.35,0.98,0.95,NEISER,IPARRAGUIRRE,MU?OZ,19880329.0,2.0,44994753,20100130204_0157001_20201122_101.TXT,901001108141740012031430011081410960091807101P...,872654,556035505,Error canal,2025,EL CAMPO FECEXCLUSION DEL(A) CERTIFICADO DEBE ...
2,872654,NaN,2022-10-25 17:52:43,3827.0,Desgravamen + Desempleo BBVA,89705.0,Plan Contifacil,00110814184000055299,2016-09-26,2020-09-28,556035940,Exclusion,26/09/2016,28/09/2020,SOL,6200.0,0.35,0.35,2.17,2.11,JAIRO LUIS,FEIJOO,DEL ROSARIO,19821102.0,2.0,41618166,20100130204_0157001_20201122_101.TXT,901001108141840000552990011081416960004645701P...,872654,556035940,Error canal,843,EL CAMPO NRO CERTIFICADO CANAL/CORREDOR SE ENC...

In [117]:
df_desgravamen.columns = (
    df_desgravamen.columns
    .str.strip()  # quitar espacios al inicio/fin
    .str.upper()  # opcional: todo en mayúsculas
    .str.replace(r'[^A-Za-z0-9]', '_', regex=True)  # reemplazar todo lo que no sea letra/número/_ por _
)

In [118]:
df_desgravamen.drop(['IDELOTE','IDEDET_1','DESCRIPCION_ERROR'], axis=1, inplace=True)

In [119]:
df_desgravamen= df_desgravamen.rename(columns={'CODIGO_ERROR': 'IDEERROR'})

In [ ]:
#df_desgravamen= df_desgravamen[['CODIGO_PRODUCTO', 'LOTES_ANTERIORES','COD_DE_CERTIFICADO', 'FECINI_ALTA_CERTIFICADO', 
 #                               'FECFIN_ALTA_CERTIFICADO','IDEDET', 'TRAMA', 'TIPO_MOVIMIENTO', 'FEC__INICIO', 
  #                              'FEC__FIN', 'MONEDA', 'SUMA_ASEGURADA', 'TASA', 'PRIMABRUTACAN', 'PRIMANETACAN', 
   #                             'NOMBRE_DE_ARCHIVO', 'ORIGEN_ERROR', 'TIPO_ERROR', 'CODIGO_ERROR']]

In [120]:
df_desgravamen[df_desgravamen['IDEERROR'].isna()].head(3)

Empty DataFrame
Columns: [NRO_LOTE, LOTES_ANTERIORES, FECHA_CARGA, CODIGO_PRODUCTO, PRODUCTO, CODIGO_PLAN, NOMBRE_DE_PLAN, COD_DE_CERTIFICADO, FECINI_ALTA_CERTIFICADO, FECFIN_ALTA_CERTIFICADO, IDEDET, TIPO_MOVIMIENTO, FEC__INICIO, FEC__FIN, MONEDA, SUMA_ASEGURADA, TASA, TASA_RECARGO, PRIMABRUTACAN, PRIMANETACAN, NOMCOMPLETO, APEPATERNO, APEMATERNO, FECNACIMIENTO, TIPDOCUMENTO, NUMDOCUMENTO, NOMBRE_DE_ARCHIVO, LINEA_TRAMA, ORIGEN_ERROR, IDEERROR]
Index: []

In [36]:
df_desgravamen['MONEDA'].value_counts()

MONEDA
SOL    118616
USD       925
Name: count, dtype: int64

In [ ]:
#df_desgravamen= df_desgravamen.fillna({'LOTES_ANTERIORES':'', 'SUMA_ASEGURADA':0, 'TASA':0, 'PRIMABRUTACAN':0, 'PRIMANETACAN':0,
 #                                      'MONEDA': 'SIN DATO'})

In [121]:
df_desgravamen= df_desgravamen.fillna({'LOTES_ANTERIORES':'', 'MONEDA': 'SIN DATO', 'ORIGEN_ERROR': 'SIN DATO', 'TIPDOCUMENTO':'SIN DATO'})
df_desgravamen.loc[df_desgravamen['MONEDA'] == 'nan', 'MONEDA'] = 'SIN DATO'
df_desgravamen.loc[df_desgravamen['ORIGEN_ERROR'] == 'nan', 'ORIGEN_ERROR'] = 'SIN DATO'

In [122]:
def limpiar_fecha(columna):
    col = columna.astype(str) # Convertir a string
    col = col.str.strip()  # Eliminar espacios
    # Quitar decimales tipo '19880329.0'
    col = col.str.replace(r"\.0$", "", regex=True)
    col = col.str[:8] # Mantener solo los 8 primeros caracteres
    # Reemplazar valores inválidos (que no tengan 8 dígitos) por NaN
    col = col.where(col.str.match(r"^\d{8}$"), np.nan)
    return pd.to_datetime(col, format="%Y%m%d", errors="coerce")  # Convertir a fecha

In [123]:
df_desgravamen["LOTES_ANTERIORES"] = df_desgravamen["LOTES_ANTERIORES"].astype(str)
df_desgravamen['FECHA_CARGA'] = pd.to_datetime(df_desgravamen['FECHA_CARGA'], errors='coerce')
df_desgravamen['CODIGO_PRODUCTO'] = df_desgravamen['CODIGO_PRODUCTO'].fillna(0).astype('int')
df_desgravamen["PRODUCTO"] = df_desgravamen["PRODUCTO"].astype(str)
df_desgravamen['CODIGO_PLAN'] = df_desgravamen['CODIGO_PLAN'].fillna(0).astype('int')
df_desgravamen["NOMBRE_DE_PLAN"] = df_desgravamen["NOMBRE_DE_PLAN"].astype(str)
df_desgravamen["COD_DE_CERTIFICADO"] = df_desgravamen["COD_DE_CERTIFICADO"].astype(str)
df_desgravamen['FECINI_ALTA_CERTIFICADO'] = pd.to_datetime(df_desgravamen['FECINI_ALTA_CERTIFICADO'], errors='coerce')
df_desgravamen['FECFIN_ALTA_CERTIFICADO'] = pd.to_datetime(df_desgravamen['FECFIN_ALTA_CERTIFICADO'], errors='coerce')
df_desgravamen["TIPO_MOVIMIENTO"] = df_desgravamen["TIPO_MOVIMIENTO"].astype(str)
df_desgravamen['FEC__INICIO'] = pd.to_datetime(df_desgravamen['FEC__INICIO'], format='%d/%m/%Y', errors='coerce')
df_desgravamen['FEC__FIN'] = pd.to_datetime(df_desgravamen['FEC__FIN'], format='%d/%m/%Y', errors='coerce')
df_desgravamen['MONEDA'] = df_desgravamen['MONEDA'].astype(str)
df_desgravamen['TASA_RECARGO'] = pd.to_numeric(df_desgravamen['TASA_RECARGO'], errors='coerce')
df_desgravamen['NOMCOMPLETO'] = df_desgravamen['NOMCOMPLETO'].astype(str)
df_desgravamen['APEPATERNO'] = df_desgravamen['APEPATERNO'].astype(str)
df_desgravamen['APEMATERNO'] = df_desgravamen['APEMATERNO'].astype(str)
df_desgravamen["FECNACIMIENTO"] = limpiar_fecha(df_desgravamen["FECNACIMIENTO"])
df_desgravamen["TIPDOCUMENTO"] = df_desgravamen["TIPDOCUMENTO"].astype(str)
df_desgravamen['NUMDOCUMENTO'] = df_desgravamen['NUMDOCUMENTO'].astype(str)
df_desgravamen['NOMBRE_DE_ARCHIVO'] = df_desgravamen['NOMBRE_DE_ARCHIVO'].astype(str)
df_desgravamen['LINEA_TRAMA'] = df_desgravamen['LINEA_TRAMA'].astype(str)
df_desgravamen['ORIGEN_ERROR'] = df_desgravamen['ORIGEN_ERROR'].astype(str)
df_desgravamen['IDEERROR'] = df_desgravamen['IDEERROR'].apply(lambda x: str(int(x)).zfill(4) if pd.notnull(x) else np.nan)

In [124]:
df_desgravamen.head(2)

,NRO_LOTE,LOTES_ANTERIORES,FECHA_CARGA,CODIGO_PRODUCTO,PRODUCTO,CODIGO_PLAN,NOMBRE_DE_PLAN,COD_DE_CERTIFICADO,FECINI_ALTA_CERTIFICADO,FECFIN_ALTA_CERTIFICADO,IDEDET,TIPO_MOVIMIENTO,FEC__INICIO,FEC__FIN,MONEDA,SUMA_ASEGURADA,TASA,TASA_RECARGO,PRIMABRUTACAN,PRIMANETACAN,NOMCOMPLETO,APEPATERNO,APEMATERNO,FECNACIMIENTO,TIPDOCUMENTO,NUMDOCUMENTO,NOMBRE_DE_ARCHIVO,LINEA_TRAMA,ORIGEN_ERROR,IDEERROR
0,872654,,2022-10-25 17:52:43,3827,Desgravamen + Desempleo BBVA,89705,Plan Contifacil,00110814174001203143,2019-12-30,2022-12-30,556035505,Exclusion,2019-12-30,2022-12-30,SOL,2800.0,0.35,0.35,0.98,0.95,NEISER,IPARRAGUIRRE,MU?OZ,1988-03-29,2.0,44994753,20100130204_0157001_20201122_101.TXT,901001108141740012031430011081410960091807101P...,Error canal,0986
1,872654,,2022-10-25 17:52:43,3827,Desgravamen + Desempleo BBVA,89705,Plan Contifacil,00110814174001203143,2019-12-30,2022-12-30,556035505,Exclusion,2019-12-30,2022-12-30,SOL,2800.0,0.35,0.35,0.98,0.95,NEISER,IPARRAGUIRRE,MU?OZ,1988-03-29,2.0,44994753,20100130204_0157001_20201122_101.TXT,901001108141740012031430011081410960091807101P...,Error canal,2025

In [125]:
df_desgravamen.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119541 entries, 0 to 119540
Data columns (total 30 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   NRO_LOTE                 119541 non-null  int64
 1   LOTES_ANTERIORES         119541 non-null  object
 2   FECHA_CARGA              119541 non-null  datetime64[ns]
 3   CODIGO_PRODUCTO          119541 non-null  int64
 4   PRODUCTO                 119541 non-null  object
 5   CODIGO_PLAN              119541 non-null  int64
 6   NOMBRE_DE_PLAN           119541 non-null  object
 7   COD_DE_CERTIFICADO       119541 non-null  object
 8   FECINI_ALTA_CERTIFICADO  117979 non-null  datetime64[ns]
 9   FECFIN_ALTA_CERTIFICADO  117979 non-null  datetime64[ns]
 10  IDEDET                   119541 non-null  int64
 11  TIPO_MOVIMIENTO          119541 non-null  object
 12  FEC__INICIO              118964 non-null  datetime64[ns]
 13  FEC__FIN                 118964 non-null  datetime64[ns]
 14  MONEDA                   119541 non-null  object
 15  SUMA_ASEGURADA           119541 non-null  float64
 16  TASA                     119541 non-null  float64
 17  TASA_RECARGO             119541 non-null  float64
 18  PRIMABRUTACAN            119541 non-null  float64
 19  PRIMANETACAN             119541 non-null  float64
 20  NOMCOMPLETO              119541 non-null  object
 21  APEPATERNO               119541 non-null  object
 22  APEMATERNO               119541 non-null  object
 23  FECNACIMIENTO            118964 non-null  datetime64[ns]
 24  TIPDOCUMENTO             119541 non-null  object
 25  NUMDOCUMENTO             119541 non-null  object
 26  NOMBRE_DE_ARCHIVO        119541 non-null  object
 27  LINEA_TRAMA              119541 non-null  object
 28  ORIGEN_ERROR             119541 non-null  object
 29  IDEERROR                 119541 non-null  object
dtypes: datetime64[ns](6), float64(5), int64(4), object(15)
memory usage: 27.4+ MB

In [65]:
df= df_desgravamen.copy()

In [126]:
df_desgravamen[df_desgravamen['LOTES_ANTERIORES']==""].head(3)

,NRO_LOTE,LOTES_ANTERIORES,FECHA_CARGA,CODIGO_PRODUCTO,PRODUCTO,CODIGO_PLAN,NOMBRE_DE_PLAN,COD_DE_CERTIFICADO,FECINI_ALTA_CERTIFICADO,FECFIN_ALTA_CERTIFICADO,IDEDET,TIPO_MOVIMIENTO,FEC__INICIO,FEC__FIN,MONEDA,SUMA_ASEGURADA,TASA,TASA_RECARGO,PRIMABRUTACAN,PRIMANETACAN,NOMCOMPLETO,APEPATERNO,APEMATERNO,FECNACIMIENTO,TIPDOCUMENTO,NUMDOCUMENTO,NOMBRE_DE_ARCHIVO,LINEA_TRAMA,ORIGEN_ERROR,IDEERROR
0,872654,,2022-10-25 17:52:43,3827,Desgravamen + Desempleo BBVA,89705,Plan Contifacil,00110814174001203143,2019-12-30,2022-12-30,556035505,Exclusion,2019-12-30,2022-12-30,SOL,2800.0,0.35,0.35,0.98,0.95,NEISER,IPARRAGUIRRE,MU?OZ,1988-03-29,2.0,44994753,20100130204_0157001_20201122_101.TXT,901001108141740012031430011081410960091807101P...,Error canal,0986
1,872654,,2022-10-25 17:52:43,3827,Desgravamen + Desempleo BBVA,89705,Plan Contifacil,00110814174001203143,2019-12-30,2022-12-30,556035505,Exclusion,2019-12-30,2022-12-30,SOL,2800.0,0.35,0.35,0.98,0.95,NEISER,IPARRAGUIRRE,MU?OZ,1988-03-29,2.0,44994753,20100130204_0157001_20201122_101.TXT,901001108141740012031430011081410960091807101P...,Error canal,2025
2,872654,,2022-10-25 17:52:43,3827,Desgravamen + Desempleo BBVA,89705,Plan Contifacil,00110814184000055299,2016-09-26,2020-09-28,556035940,Exclusion,2016-09-26,2020-09-28,SOL,6200.0,0.35,0.35,2.17,2.11,JAIRO LUIS,FEIJOO,DEL ROSARIO,1982-11-02,2.0,41618166,20100130204_0157001_20201122_101.TXT,901001108141840000552990011081416960004645701P...,Error canal,0843

In [127]:
df_desgravamen['ORIGEN_ERROR'].value_counts()

ORIGEN_ERROR
Error Rimac    115901
Error canal      3640
Name: count, dtype: int64

In [128]:
df_desgravamen.head(3)

,NRO_LOTE,LOTES_ANTERIORES,FECHA_CARGA,CODIGO_PRODUCTO,PRODUCTO,CODIGO_PLAN,NOMBRE_DE_PLAN,COD_DE_CERTIFICADO,FECINI_ALTA_CERTIFICADO,FECFIN_ALTA_CERTIFICADO,IDEDET,TIPO_MOVIMIENTO,FEC__INICIO,FEC__FIN,MONEDA,SUMA_ASEGURADA,TASA,TASA_RECARGO,PRIMABRUTACAN,PRIMANETACAN,NOMCOMPLETO,APEPATERNO,APEMATERNO,FECNACIMIENTO,TIPDOCUMENTO,NUMDOCUMENTO,NOMBRE_DE_ARCHIVO,LINEA_TRAMA,ORIGEN_ERROR,IDEERROR
0,872654,,2022-10-25 17:52:43,3827,Desgravamen + Desempleo BBVA,89705,Plan Contifacil,00110814174001203143,2019-12-30,2022-12-30,556035505,Exclusion,2019-12-30,2022-12-30,SOL,2800.0,0.35,0.35,0.98,0.95,NEISER,IPARRAGUIRRE,MU?OZ,1988-03-29,2.0,44994753,20100130204_0157001_20201122_101.TXT,901001108141740012031430011081410960091807101P...,Error canal,0986
1,872654,,2022-10-25 17:52:43,3827,Desgravamen + Desempleo BBVA,89705,Plan Contifacil,00110814174001203143,2019-12-30,2022-12-30,556035505,Exclusion,2019-12-30,2022-12-30,SOL,2800.0,0.35,0.35,0.98,0.95,NEISER,IPARRAGUIRRE,MU?OZ,1988-03-29,2.0,44994753,20100130204_0157001_20201122_101.TXT,901001108141740012031430011081410960091807101P...,Error canal,2025
2,872654,,2022-10-25 17:52:43,3827,Desgravamen + Desempleo BBVA,89705,Plan Contifacil,00110814184000055299,2016-09-26,2020-09-28,556035940,Exclusion,2016-09-26,2020-09-28,SOL,6200.0,0.35,0.35,2.17,2.11,JAIRO LUIS,FEIJOO,DEL ROSARIO,1982-11-02,2.0,41618166,20100130204_0157001_20201122_101.TXT,901001108141840000552990011081416960004645701P...,Error canal,0843

In [192]:
#df_desgravamen['COD_DE_CERTIFICADO'] = df_desgravamen['COD_DE_CERTIFICADO'].apply(lambda x: str(int(x)) if pd.notnull(x) else '0')
"""df_desgravamen['CODIGO_PRODUCTO'] = df_desgravamen['CODIGO_PRODUCTO'].fillna(0).astype('int')
df_desgravamen["LOTES_ANTERIORES"] = df_desgravamen["LOTES_ANTERIORES"].astype(str)

df_desgravamen['FECINI_ALTA_CERTIFICADO'] = pd.to_datetime(df_desgravamen['FECINI_ALTA_CERTIFICADO'], errors='coerce')
df_desgravamen['FECFIN_ALTA_CERTIFICADO'] = pd.to_datetime(df_desgravamen['FECFIN_ALTA_CERTIFICADO'], errors='coerce')
df_desgravamen['TIPO_MOVIMIENTO'] = df_desgravamen['TIPO_MOVIMIENTO'].astype(str)
df_desgravamen['FEC__INICIO'] = pd.to_datetime(df_desgravamen['FEC__INICIO'], format='%d/%m/%Y', errors='coerce')
df_desgravamen['FEC__FIN'] = pd.to_datetime(df_desgravamen['FEC__FIN'], format='%d/%m/%Y', errors='coerce')
df_desgravamen['MONEDA'] = df_desgravamen['MONEDA'].astype(str)
df_desgravamen['SUMA_ASEGURADA']= pd.to_numeric(df_desgravamen['SUMA_ASEGURADA'], errors='coerce')
df_desgravamen['TASA']= pd.to_numeric(df_desgravamen['TASA'], errors='coerce')
df_desgravamen['PRIMABRUTACAN']= pd.to_numeric(df_desgravamen['PRIMABRUTACAN'], errors='coerce')
df_desgravamen['PRIMANETACAN']= pd.to_numeric(df_desgravamen['PRIMANETACAN'], errors='coerce')
df_desgravamen['ORIGEN_ERROR'] = df_desgravamen['ORIGEN_ERROR'].fillna(0).astype('int')
"""

'df_desgravamen[\'CODIGO_PRODUCTO\'] = df_desgravamen[\'CODIGO_PRODUCTO\'].fillna(0).astype(\'int\')\ndf_desgravamen["LOTES_ANTERIORES"] = df_desgravamen["LOTES_ANTERIORES"].astype(str)\n\ndf_desgravamen[\'FECINI_ALTA_CERTIFICADO\'] = pd.to_datetime(df_desgravamen[\'FECINI_ALTA_CERTIFICADO\'], errors=\'coerce\')\ndf_desgravamen[\'FECFIN_ALTA_CERTIFICADO\'] = pd.to_datetime(df_desgravamen[\'FECFIN_ALTA_CERTIFICADO\'], errors=\'coerce\')\ndf_desgravamen[\'TIPO_MOVIMIENTO\'] = df_desgravamen[\'TIPO_MOVIMIENTO\'].astype(str)\ndf_desgravamen[\'FEC__INICIO\'] = pd.to_datetime(df_desgravamen[\'FEC__INICIO\'], format=\'%d/%m/%Y\', errors=\'coerce\')\ndf_desgravamen[\'FEC__FIN\'] = pd.to_datetime(df_desgravamen[\'FEC__FIN\'], format=\'%d/%m/%Y\', errors=\'coerce\')\ndf_desgravamen[\'MONEDA\'] = df_desgravamen[\'MONEDA\'].astype(str)\ndf_desgravamen[\'SUMA_ASEGURADA\']= pd.to_numeric(df_desgravamen[\'SUMA_ASEGURADA\'], errors=\'coerce\')\ndf_desgravamen[\'TASA\']= pd.to_numeric(df_desgravamen[\'TASA\'], errors=\'coerce\')\ndf_desgravamen[\'PRIMABRUTACAN\']= pd.to_numeric(df_desgravamen[\'PRIMABRUTACAN\'], errors=\'coerce\')\ndf_desgravamen[\'PRIMANETACAN\']= pd.to_numeric(df_desgravamen[\'PRIMANETACAN\'], errors=\'coerce\')\ndf_desgravamen[\'ORIGEN_ERROR\'] = df_desgravamen[\'ORIGEN_ERROR\'].fillna(0).astype(\'int\')\n'

In [129]:
#TIPO MOVIMIENTO
df_desgravamen['FECINI_ALTA_CERTIFICADO'].value_counts()  # Counting occurrences of each unique value in the 'TIPO MOVIMIENTO' column

FECINI_ALTA_CERTIFICADO
2019-09-30    480
2019-09-27    460
2019-09-16    432
2017-09-28    348
2021-07-21    344
             ...
2014-06-02      1
2013-11-14      1
2014-11-12      1
2014-09-11      1
2014-10-15      1
Name: count, Length: 2095, dtype: int64

In [130]:
df_desgravamen[df_desgravamen['FEC__INICIO'].isna()].head(3)

,NRO_LOTE,LOTES_ANTERIORES,FECHA_CARGA,CODIGO_PRODUCTO,PRODUCTO,CODIGO_PLAN,NOMBRE_DE_PLAN,COD_DE_CERTIFICADO,FECINI_ALTA_CERTIFICADO,FECFIN_ALTA_CERTIFICADO,IDEDET,TIPO_MOVIMIENTO,FEC__INICIO,FEC__FIN,MONEDA,SUMA_ASEGURADA,TASA,TASA_RECARGO,PRIMABRUTACAN,PRIMANETACAN,NOMCOMPLETO,APEPATERNO,APEMATERNO,FECNACIMIENTO,TIPDOCUMENTO,NUMDOCUMENTO,NOMBRE_DE_ARCHIVO,LINEA_TRAMA,ORIGEN_ERROR,IDEERROR
90586,873197,,2022-10-26 13:08:22,3827,Desgravamen + Desempleo BBVA,80799,Plan Contiauto,00110226814000465105,2021-10-28,2027-10-28,556187092,Exclusion,NaT,NaT,SOL,0.0,0.0,0.0,0.0,0.0,nan,711896 L42272745 PEN0000000,00219E20220128I1,NaT,SIN DATO,nan,20100130204_0157001_20210403_103.TXT,902001102268140004651050011022688960019248103P...,Error canal,0014
90587,873197,,2022-10-26 13:08:22,3827,Desgravamen + Desempleo BBVA,80799,Plan Contiauto,00110226814000465105,2021-10-28,2027-10-28,556187092,Exclusion,NaT,NaT,SOL,0.0,0.0,0.0,0.0,0.0,nan,711896 L42272745 PEN0000000,00219E20220128I1,NaT,SIN DATO,nan,20100130204_0157001_20210403_103.TXT,902001102268140004651050011022688960019248103P...,Error canal,0035
90588,873197,,2022-10-26 13:08:22,3827,Desgravamen + Desempleo BBVA,80799,Plan Contiauto,00110245884000372674,2021-10-27,2026-10-27,556187108,Exclusion,NaT,NaT,SOL,0.0,0.0,0.0,0.0,0.0,nan,670559 L72271326 PEN0000000,00084G20220127I1,NaT,SIN DATO,nan,20100130204_0157001_20210403_103.TXT,902001102458840003726740011024585960013379903P...,Error canal,0014

In [70]:
#MONEDA
df_desgravamen['MONEDA'].value_counts()  # Counting occurrences of each unique value in the 'MONEDA' column

MONEDA
SOL    118616
USD       925
Name: count, dtype: int64

In [131]:
df_desgravamen['TIPO_MOVIMIENTO'].value_counts()

TIPO_MOVIMIENTO
Exclusion         119437
Sin Movimiento       104
Name: count, dtype: int64

In [132]:
df_desgravamen[df_desgravamen['TIPO_MOVIMIENTO'].isna()].head(3)

Empty DataFrame
Columns: [NRO_LOTE, LOTES_ANTERIORES, FECHA_CARGA, CODIGO_PRODUCTO, PRODUCTO, CODIGO_PLAN, NOMBRE_DE_PLAN, COD_DE_CERTIFICADO, FECINI_ALTA_CERTIFICADO, FECFIN_ALTA_CERTIFICADO, IDEDET, TIPO_MOVIMIENTO, FEC__INICIO, FEC__FIN, MONEDA, SUMA_ASEGURADA, TASA, TASA_RECARGO, PRIMABRUTACAN, PRIMANETACAN, NOMCOMPLETO, APEPATERNO, APEMATERNO, FECNACIMIENTO, TIPDOCUMENTO, NUMDOCUMENTO, NOMBRE_DE_ARCHIVO, LINEA_TRAMA, ORIGEN_ERROR, IDEERROR]
Index: []

In [32]:
df_desgravamen[df_desgravamen['MONEDA']=='SIN DATO'].head()

,NRO_LOTE,LOTES_ANTERIORES,FECHA_CARGA,CODIGO_PRODUCTO,PRODUCTO,CODIGO_PLAN,NOMBRE_DE_PLAN,COD_DE_CERTIFICADO,FECINI_ALTA_CERTIFICADO,FECFIN_ALTA_CERTIFICADO,IDEDET,TIPO_MOVIMIENTO,FEC__INICIO,FEC__FIN,MONEDA,SUMA_ASEGURADA,TASA,TASA_RECARGO,PRIMABRUTACAN,PRIMANETACAN,NOMCOMPLETO,APEPATERNO,APEMATERNO,FECNACIMIENTO,TIPDOCUMENTO,NUMDOCUMENTO,NOMBRE_DE_ARCHIVO,LINEA_TRAMA,ORIGEN_ERROR,CODIGO_ERROR,DESCRIPCION_ERROR
27604,70140,,2016-05-11 13:00:14,0,nan,0,nan,nan,NaT,NaT,132857441,Sin Movimiento,NaT,NaT,SIN DATO,0.0,0.0,0,0.0,0.0,nan,nan,nan,NaT,NaN,nan,20100130204_0157001_20160511_001.TXT,906001102755540002830710011027558960038589901P...,Error canal,983,"ERROR, Al ser tipo de titular mancomuno debe h..."
81303,130634,,2018-04-20 17:54:46,0,nan,0,nan,nan,NaT,NaT,230834148,Sin Movimiento,NaT,NaT,SIN DATO,0.0,0.0,0,0.0,0.0,nan,nan,nan,NaT,NaN,nan,20100130204_0157001_20180420_005.TXT,903001103357340001273260011033574960008761301P...,Error canal,983,"ERROR, Al ser tipo de titular mancomuno debe h..."
125160,285763,,2019-10-29 10:48:36,3827,Desgravamen + Desempleo BBVA,157903,PAN AMERICAN SILVER PERU TS BASE,0,NaT,NaT,335465001,Sin Movimiento,NaT,NaT,SIN DATO,0.0,0.0,0,0.0,0.0,nan,nan,nan,NaT,NaN,nan,20100130204_0157001_20191029_003.TXT,9030,Error canal,12,ERROR EN CAMPO: TIPO MOVIMIENTO DEL(A) DEFECTO...

In [133]:
def extraer_fecha(fecha):
    try:
        fecha_str = fecha.split("_")[2]
        return datetime.strptime(fecha_str, "%Y%m%d").date()
    except Exception:
        return None  # En caso de error

In [134]:
# Aplicar a la columna
df_desgravamen['FECHA_TRAMA'] = df_desgravamen['NOMBRE_DE_ARCHIVO'].apply(extraer_fecha)

In [135]:
df_desgravamen.head(2)

,NRO_LOTE,LOTES_ANTERIORES,FECHA_CARGA,CODIGO_PRODUCTO,PRODUCTO,CODIGO_PLAN,NOMBRE_DE_PLAN,COD_DE_CERTIFICADO,FECINI_ALTA_CERTIFICADO,FECFIN_ALTA_CERTIFICADO,IDEDET,TIPO_MOVIMIENTO,FEC__INICIO,FEC__FIN,MONEDA,SUMA_ASEGURADA,TASA,TASA_RECARGO,PRIMABRUTACAN,PRIMANETACAN,NOMCOMPLETO,APEPATERNO,APEMATERNO,FECNACIMIENTO,TIPDOCUMENTO,NUMDOCUMENTO,NOMBRE_DE_ARCHIVO,LINEA_TRAMA,ORIGEN_ERROR,IDEERROR,FECHA_TRAMA
0,872654,,2022-10-25 17:52:43,3827,Desgravamen + Desempleo BBVA,89705,Plan Contifacil,00110814174001203143,2019-12-30,2022-12-30,556035505,Exclusion,2019-12-30,2022-12-30,SOL,2800.0,0.35,0.35,0.98,0.95,NEISER,IPARRAGUIRRE,MU?OZ,1988-03-29,2.0,44994753,20100130204_0157001_20201122_101.TXT,901001108141740012031430011081410960091807101P...,Error canal,0986,2020-11-22
1,872654,,2022-10-25 17:52:43,3827,Desgravamen + Desempleo BBVA,89705,Plan Contifacil,00110814174001203143,2019-12-30,2022-12-30,556035505,Exclusion,2019-12-30,2022-12-30,SOL,2800.0,0.35,0.35,0.98,0.95,NEISER,IPARRAGUIRRE,MU?OZ,1988-03-29,2.0,44994753,20100130204_0157001_20201122_101.TXT,901001108141740012031430011081410960091807101P...,Error canal,2025,2020-11-22

In [136]:
df_desgravamen['FECHA_TRAMA'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 119541 entries, 0 to 119540
Series name: FECHA_TRAMA
Non-Null Count   Dtype
--------------   -----
119541 non-null  object
dtypes: object(1)
memory usage: 934.0+ KB

In [137]:
df_desgravamen['FECHA_TRAMA']= pd.to_datetime(df_desgravamen['FECHA_TRAMA'], errors='coerce')

In [138]:
def clasificar(row):
    # Si lote no esta vacio
    if str(row['LOTES_ANTERIORES']).strip() != "":
        return 'Regularizacion no Exitosa'
    
    # Si último número del nombre de archivo > 100
    try:
        ultimo_numero = int(row['NOMBRE_DE_ARCHIVO'].split("_")[-1][:-4])
        if ultimo_numero > 100:
            return 'Regularizacion no Exitosa'
    except:
        pass
    
    # Si ninguna condición se cumple
    return 'Mes corriente'

In [80]:
nombre = '20100130204_0157001_20150409_001_41924.TXT'
numero= int(nombre.split("_")[-1][:-4])
print(numero)

41924

In [139]:
#df_desgravamen['REGULARIZACION']= df_desgravamen['LOTES ANTERIORES'].notnull()
df_desgravamen['STATUS']= df_desgravamen.apply(clasificar, axis=1)

In [140]:
df_desgravamen['STATUS'].value_counts()

STATUS
Regularizacion no Exitosa    119541
Name: count, dtype: int64

In [141]:
df_desgravamen[df_desgravamen['STATUS']=='Mes corriente'].head(6)

Empty DataFrame
Columns: [NRO_LOTE, LOTES_ANTERIORES, FECHA_CARGA, CODIGO_PRODUCTO, PRODUCTO, CODIGO_PLAN, NOMBRE_DE_PLAN, COD_DE_CERTIFICADO, FECINI_ALTA_CERTIFICADO, FECFIN_ALTA_CERTIFICADO, IDEDET, TIPO_MOVIMIENTO, FEC__INICIO, FEC__FIN, MONEDA, SUMA_ASEGURADA, TASA, TASA_RECARGO, PRIMABRUTACAN, PRIMANETACAN, NOMCOMPLETO, APEPATERNO, APEMATERNO, FECNACIMIENTO, TIPDOCUMENTO, NUMDOCUMENTO, NOMBRE_DE_ARCHIVO, LINEA_TRAMA, ORIGEN_ERROR, IDEERROR, FECHA_TRAMA, STATUS]
Index: []

In [102]:
df_errores[df_errores['CODIGO_ERROR'].isna()].head(10)

,IDEERROR,CODIGO_ERROR,DESCRIPCION_ERROR,DETALLE,SOLUCION,SOLUCION_2
12,NaN,NaN,ERROR EN CARGA DE TRAMA,NI ÉXITO NI ERROR,ANALISIS EMISOR,NaN

In [103]:
df_errores[df_errores['CODIGO_ERROR'].isin({'2395','7440'})].head()

,IDEERROR,CODIGO_ERROR,DESCRIPCION_ERROR,DETALLE,SOLUCION,SOLUCION_2
11,2048,2395,ERROR DE TASA,TASA,ANALISIS EMISOR,CONFIGURACION SAS
37,1566,7440,ERROR EDAD,EDAD - MANCOMUNO INEXISTENTE,CONFIGURACION SAS,REGLAS POR CAMBIAR

In [104]:
df_errores[df_errores['CODIGO_ERROR']==' '].head()

Empty DataFrame
Columns: [IDEERROR, CODIGO_ERROR, DESCRIPCION_ERROR, DETALLE, SOLUCION, SOLUCION_2]
Index: []

In [105]:
df_desgravamen[df_desgravamen['IDEERROR'].isna()].head(10)

Empty DataFrame
Columns: [NRO_LOTE, LOTES_ANTERIORES, FECHA_CARGA, CODIGO_PRODUCTO, PRODUCTO, CODIGO_PLAN, NOMBRE_DE_PLAN, COD_DE_CERTIFICADO, FECINI_ALTA_CERTIFICADO, FECFIN_ALTA_CERTIFICADO, IDEDET, TIPO_MOVIMIENTO, FEC__INICIO, FEC__FIN, MONEDA, SUMA_ASEGURADA, TASA, TASA_RECARGO, PRIMABRUTACAN, PRIMANETACAN, NOMCOMPLETO, APEPATERNO, APEMATERNO, FECNACIMIENTO, TIPDOCUMENTO, NUMDOCUMENTO, NOMBRE_DE_ARCHIVO, LINEA_TRAMA, ORIGEN_ERROR, IDEERROR, FECHA_TRAMA, STATUS]
Index: []

In [107]:
df_desgravamen[df_desgravamen['IDEERROR']==''].head()

Empty DataFrame
Columns: [NRO_LOTE, LOTES_ANTERIORES, FECHA_CARGA, CODIGO_PRODUCTO, PRODUCTO, CODIGO_PLAN, NOMBRE_DE_PLAN, COD_DE_CERTIFICADO, FECINI_ALTA_CERTIFICADO, FECFIN_ALTA_CERTIFICADO, IDEDET, TIPO_MOVIMIENTO, FEC__INICIO, FEC__FIN, MONEDA, SUMA_ASEGURADA, TASA, TASA_RECARGO, PRIMABRUTACAN, PRIMANETACAN, NOMCOMPLETO, APEPATERNO, APEMATERNO, FECNACIMIENTO, TIPDOCUMENTO, NUMDOCUMENTO, NOMBRE_DE_ARCHIVO, LINEA_TRAMA, ORIGEN_ERROR, IDEERROR, FECHA_TRAMA, STATUS]
Index: []

In [108]:
df_errores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   IDEERROR           53 non-null     object
 1   CODIGO_ERROR       53 non-null     object
 2   DESCRIPCION_ERROR  54 non-null     object
 3   DETALLE            54 non-null     object
 4   SOLUCION           54 non-null     object
 5   SOLUCION_2         19 non-null     object
dtypes: object(6)
memory usage: 2.7+ KB

In [142]:
df= df_desgravamen.merge(df_errores, on='IDEERROR', how='left')

In [143]:
df['DESCRIPCION_ERROR'].value_counts()

DESCRIPCION_ERROR
VALIDACIONES CONSECUENCIA ACSEL E    115762
TRAMA REPETIDA O DUPLICADA              853
CAMPOS EN BLANCO                        235
TIPO PERSONA                            233
ERROR EN CARGA DE TRAMA                 104
NI ÉXITO NI ERROR                        91
SIN POLIZA                               48
Name: count, dtype: int64

In [144]:
df['CODIGO_ERROR'].value_counts()

CODIGO_ERROR
0177    115762
0130       853
0011       235
0022       233
0193       104
0117        91
0163        48
Name: count, dtype: int64

In [145]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119541 entries, 0 to 119540
Data columns (total 37 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   NRO_LOTE                 119541 non-null  int64
 1   LOTES_ANTERIORES         119541 non-null  object
 2   FECHA_CARGA              119541 non-null  datetime64[ns]
 3   CODIGO_PRODUCTO          119541 non-null  int64
 4   PRODUCTO                 119541 non-null  object
 5   CODIGO_PLAN              119541 non-null  int64
 6   NOMBRE_DE_PLAN           119541 non-null  object
 7   COD_DE_CERTIFICADO       119541 non-null  object
 8   FECINI_ALTA_CERTIFICADO  117979 non-null  datetime64[ns]
 9   FECFIN_ALTA_CERTIFICADO  117979 non-null  datetime64[ns]
 10  IDEDET                   119541 non-null  int64
 11  TIPO_MOVIMIENTO          119541 non-null  object
 12  FEC__INICIO              118964 non-null  datetime64[ns]
 13  FEC__FIN                 118964 non-null  datetime64[ns]
 14  MONEDA                   119541 non-null  object
 15  SUMA_ASEGURADA           119541 non-null  float64
 16  TASA                     119541 non-null  float64
 17  TASA_RECARGO             119541 non-null  float64
 18  PRIMABRUTACAN            119541 non-null  float64
 19  PRIMANETACAN             119541 non-null  float64
 20  NOMCOMPLETO              119541 non-null  object
 21  APEPATERNO               119541 non-null  object
 22  APEMATERNO               119541 non-null  object
 23  FECNACIMIENTO            118964 non-null  datetime64[ns]
 24  TIPDOCUMENTO             119541 non-null  object
 25  NUMDOCUMENTO             119541 non-null  object
 26  NOMBRE_DE_ARCHIVO        119541 non-null  object
 27  LINEA_TRAMA              119541 non-null  object
 28  ORIGEN_ERROR             119541 non-null  object
 29  IDEERROR                 119541 non-null  object
 30  FECHA_TRAMA              119541 non-null  datetime64[ns]
 31  STATUS                   119541 non-null  object
 32  CODIGO_ERROR             117326 non-null  object
 33  DESCRIPCION_ERROR        117326 non-null  object
 34  DETALLE                  117326 non-null  object
 35  SOLUCION                 117326 non-null  object
 36  SOLUCION_2               992 non-null     object
dtypes: datetime64[ns](7), float64(5), int64(4), object(21)
memory usage: 33.7+ MB