In [1]:
import pandas as pd
from datetime import datetime
import warnings
warnings.filterwarnings("ignore", category=UserWarning, module="openpyxl")
import unicodedata
import os
pd.set_option('display.max_columns', None)

In [221]:
df_errores= pd.read_excel('c:/data/tabla_errores.xlsx', sheet_name='Sheet1', dtype={'CODIGO_ERROR': str})
df_errores.head(3)

,CODIGO_ERROR,DESCRIPCION_ERROR,DETALLE,SOLUCION,SOLUCION_2
0,1068,YA EXISTE UN PAGO CON LA MISMA FECHA DE INICIO...,YA EXISTE UN PAGO CON LA MISMA FECHA DE INICIO...,CONFIGURACION SAS,ANULAR MASIVAS
1,0003,ERROR EN CARGA DE TRAMA,ERROR EN CARGA DE TRAMA,ANALISIS EMISOR,NaN
2,1155,TRAMA REPETIDA O DUPLICADA,TRAMA REPETIDA O DUPLICADA,CONFIGURACION SAS,ANULAR MASIVAS

In [222]:
df_errores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53 entries, 0 to 52
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CODIGO_ERROR       52 non-null     object
 1   DESCRIPCION_ERROR  53 non-null     object
 2   DETALLE            53 non-null     object
 3   SOLUCION           53 non-null     object
 4   SOLUCION_2         19 non-null     object
dtypes: object(5)
memory usage: 2.2+ KB

In [ ]:
#df_errores.to_excel('c:/data/tabla_errores.xlsx', index=False)

In [224]:
# Se carga el dataset en excel de Accidentes mortales
df_desgravamen= pd.read_excel('C:/data/Reporte de errores/446 - Desgravamen - 02.xlsx', sheet_name='Sheet1', 
                              dtype={'COD DE CERTIFICADO': str, 'DESCRIPCION ERROR': str, 'IDELOTE': str, 'CODIGO ERROR': str})

In [225]:
df_desgravamen.head(2)

,NRO LOTE,LOTES ANTERIORES,FECHA CARGA,CODIGO PRODUCTO,PRODUCTO,CODIGO PLAN,NOMBRE DE PLAN,COD DE CERTIFICADO,fecini_alta_CERTIFICADO,fecfin_alta_CERTIFICADO,IDEDET,TIPO MOVIMIENTO,FEC. INICIO,FEC. FIN,MONEDA,SUMA ASEGURADA,TASA,TASA RECARGO,PRIMABRUTACAN,PRIMANETACAN,NOMCOMPLETO,APEPATERNO,APEMATERNO,FECNACIMIENTO,TIPDOCUMENTO,NUMDOCUMENTO,NOMBRE DE ARCHIVO,LINEA TRAMA,IDELOTE,IDEDET.1,ORIGEN ERROR,CODIGO ERROR,DESCRIPCION ERROR
0,872611,NaN,2022-10-25 17:10:46,NaN,NaN,NaN,NaN,NaN,NaT,NaT,555862169,Sin Movimiento,03/03/2020,17/06/2024,SOL,5000.00,0.35,0.35,1.75,1.70,GABRIEL,SALINAS,LORA,19790130,2,40227891,20100130204_0157001_20201122_100.TXT,901001101062040002365100011010629960014659201P...,872611,555862169,Error canal,1158,Trama repetida o duplicada
1,872611,NaN,2022-10-25 17:10:46,NaN,NaN,NaN,NaN,NaN,NaT,NaT,555862263,Sin Movimiento,30/04/2018,05/04/2021,SOL,63892.89,0.35,0.35,22.36,21.71,JUAN,SANTILLANA,CALLIRGOS,19491019,2,09295733,20100130204_0157001_20201122_100.TXT,901001101062940001863270011010626960011202701P...,872611,555862263,Error canal,1158,Trama repetida o duplicada

In [226]:
df_desgravamen.columns = (
    df_desgravamen.columns
    .str.strip()  # quitar espacios al inicio/fin
    .str.upper()  # opcional: todo en mayúsculas
    .str.replace(r'[^A-Za-z0-9]', '_', regex=True)  # reemplazar todo lo que no sea letra/número/_ por _
)

In [227]:
df_desgravamen.drop(['IDELOTE','IDEDET_1'], axis=1, inplace=True)

In [ ]:
#df_desgravamen= df_desgravamen.rename(columns={'CODIGO_ERROR': 'TIPO_ERROR',
 #                                              'DESCRIPCION_ERROR': 'CODIGO_ERROR',
  #                                             'IDELOTE': 'TRAMA'}) # cambiar nombre de las columnas

In [ ]:
#df_desgravamen= df_desgravamen[['CODIGO_PRODUCTO', 'LOTES_ANTERIORES','COD_DE_CERTIFICADO', 'FECINI_ALTA_CERTIFICADO', 
 #                               'FECFIN_ALTA_CERTIFICADO','IDEDET', 'TRAMA', 'TIPO_MOVIMIENTO', 'FEC__INICIO', 
  #                              'FEC__FIN', 'MONEDA', 'SUMA_ASEGURADA', 'TASA', 'PRIMABRUTACAN', 'PRIMANETACAN', 
   #                             'NOMBRE_DE_ARCHIVO', 'ORIGEN_ERROR', 'TIPO_ERROR', 'CODIGO_ERROR']]

In [228]:
df_desgravamen.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97770 entries, 0 to 97769
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   NRO_LOTE                 97770 non-null  int64
 1   LOTES_ANTERIORES         4 non-null      float64
 2   FECHA_CARGA              97770 non-null  datetime64[ns]
 3   CODIGO_PRODUCTO          97337 non-null  float64
 4   PRODUCTO                 97337 non-null  object
 5   CODIGO_PLAN              97337 non-null  float64
 6   NOMBRE_DE_PLAN           97337 non-null  object
 7   COD_DE_CERTIFICADO       97337 non-null  object
 8   FECINI_ALTA_CERTIFICADO  95773 non-null  datetime64[ns]
 9   FECFIN_ALTA_CERTIFICADO  95773 non-null  datetime64[ns]
 10  IDEDET                   97770 non-null  int64
 11  TIPO_MOVIMIENTO          97770 non-null  object
 12  FEC__INICIO              97770 non-null  object
 13  FEC__FIN                 97770 non-null  object
 14  MONEDA                   97770 non-null  object
 15  SUMA_ASEGURADA           97770 non-null  float64
 16  TASA                     97770 non-null  float64
 17  TASA_RECARGO             97770 non-null  float64
 18  PRIMABRUTACAN            97770 non-null  float64
 19  PRIMANETACAN             97770 non-null  float64
 20  NOMCOMPLETO              97770 non-null  object
 21  APEPATERNO               97770 non-null  object
 22  APEMATERNO               97770 non-null  object
 23  FECNACIMIENTO            97770 non-null  int64
 24  TIPDOCUMENTO             97770 non-null  int64
 25  NUMDOCUMENTO             97770 non-null  object
 26  NOMBRE_DE_ARCHIVO        97770 non-null  object
 27  LINEA_TRAMA              97770 non-null  object
 28  ORIGEN_ERROR             97770 non-null  object
 29  CODIGO_ERROR             97770 non-null  object
 30  DESCRIPCION_ERROR        97770 non-null  object
dtypes: datetime64[ns](3), float64(8), int64(4), object(16)
memory usage: 23.1+ MB

In [229]:
df_desgravamen[df_desgravamen['CODIGO_ERROR'].isna()].head(3)

Empty DataFrame
Columns: [NRO_LOTE, LOTES_ANTERIORES, FECHA_CARGA, CODIGO_PRODUCTO, PRODUCTO, CODIGO_PLAN, NOMBRE_DE_PLAN, COD_DE_CERTIFICADO, FECINI_ALTA_CERTIFICADO, FECFIN_ALTA_CERTIFICADO, IDEDET, TIPO_MOVIMIENTO, FEC__INICIO, FEC__FIN, MONEDA, SUMA_ASEGURADA, TASA, TASA_RECARGO, PRIMABRUTACAN, PRIMANETACAN, NOMCOMPLETO, APEPATERNO, APEMATERNO, FECNACIMIENTO, TIPDOCUMENTO, NUMDOCUMENTO, NOMBRE_DE_ARCHIVO, LINEA_TRAMA, ORIGEN_ERROR, CODIGO_ERROR, DESCRIPCION_ERROR]
Index: []

In [148]:
df_desgravamen[df_desgravamen['COD_DE_CERTIFICADO'].notnull()].head(3)

,NRO_LOTE,LOTES_ANTERIORES,FECHA_CARGA,CODIGO_PRODUCTO,PRODUCTO,CODIGO_PLAN,NOMBRE_DE_PLAN,COD_DE_CERTIFICADO,FECINI_ALTA_CERTIFICADO,FECFIN_ALTA_CERTIFICADO,IDEDET,TIPO_MOVIMIENTO,FEC__INICIO,FEC__FIN,MONEDA,SUMA_ASEGURADA,TASA,TASA_RECARGO,PRIMABRUTACAN,PRIMANETACAN,NOMCOMPLETO,APEPATERNO,APEMATERNO,FECNACIMIENTO,TIPDOCUMENTO,NUMDOCUMENTO,NOMBRE_DE_ARCHIVO,LINEA_TRAMA,ORIGEN_ERROR,CODIGO_ERROR,DESCRIPCION_ERROR
433,872611,NaN,2022-10-25 17:10:46,3827.0,Desgravamen + Desempleo BBVA,80908.0,Plan Conticasa,00110358944000291156,2020-01-22,2039-03-29,555923543,Exclusion,22/01/2020,30/03/2039,SOL,639100.0,0.28,50.28,268.43,260.61,ELBERT,AGURTO,MOGOLLON,19590330,2,06103897,20100130204_0157001_20201122_100.TXT,903001103589440002911560011035895960021558701P...,Error Rimac,101,No se identifico IdeAcuerdo IAA para el Acuerd...
434,872611,NaN,2022-10-25 17:10:46,3827.0,Desgravamen + Desempleo BBVA,80908.0,Plan Conticasa,00110358944000291156,2020-01-22,2039-03-29,555923543,Exclusion,22/01/2020,30/03/2039,SOL,639100.0,0.28,50.28,268.43,260.61,ELBERT,AGURTO,MOGOLLON,19590330,2,06103897,20100130204_0157001_20201122_100.TXT,903001103589440002911560011035895960021558701P...,Error Rimac,101,No se identifico IdeAcuerdo IAA para el Acuerd...
435,872611,NaN,2022-10-25 17:10:46,3827.0,Desgravamen + Desempleo BBVA,80908.0,Plan Conticasa,00110732524000101058,2020-05-28,2031-07-26,555924360,Exclusion,28/05/2020,02/09/2031,SOL,489887.2,0.28,0.28,137.17,133.17,GUIDO EDMUNDO,MORENO,COLLAZOS,19510727,2,06760705,20100130204_0157001_20201122_100.TXT,903001107325240001010580011073257960005563901P...,Error Rimac,101,No se identifico IdeAcuerdo IAA para el Acuerd...

In [162]:
df_desgravamen.head(3)

,NRO_LOTE,LOTES_ANTERIORES,FECHA_CARGA,CODIGO_PRODUCTO,PRODUCTO,CODIGO_PLAN,NOMBRE_DE_PLAN,COD_DE_CERTIFICADO,FECINI_ALTA_CERTIFICADO,FECFIN_ALTA_CERTIFICADO,IDEDET,TIPO_MOVIMIENTO,FEC__INICIO,FEC__FIN,MONEDA,SUMA_ASEGURADA,TASA,TASA_RECARGO,PRIMABRUTACAN,PRIMANETACAN,NOMCOMPLETO,APEPATERNO,APEMATERNO,FECNACIMIENTO,TIPDOCUMENTO,NUMDOCUMENTO,NOMBRE_DE_ARCHIVO,LINEA_TRAMA,ORIGEN_ERROR,CODIGO_ERROR,DESCRIPCION_ERROR
0,872611,NaN,2022-10-25 17:10:46,NaN,NaN,NaN,NaN,NaN,NaT,NaT,555862169,Sin Movimiento,03/03/2020,17/06/2024,SOL,5000.00,0.35,0.35,1.75,1.70,GABRIEL,SALINAS,LORA,19790130,2,40227891,20100130204_0157001_20201122_100.TXT,901001101062040002365100011010629960014659201P...,Error canal,1158,Trama repetida o duplicada
1,872611,NaN,2022-10-25 17:10:46,NaN,NaN,NaN,NaN,NaN,NaT,NaT,555862263,Sin Movimiento,30/04/2018,05/04/2021,SOL,63892.89,0.35,0.35,22.36,21.71,JUAN,SANTILLANA,CALLIRGOS,19491019,2,09295733,20100130204_0157001_20201122_100.TXT,901001101062940001863270011010626960011202701P...,Error canal,1158,Trama repetida o duplicada
2,872611,NaN,2022-10-25 17:10:46,NaN,NaN,NaN,NaN,NaN,NaT,NaT,555862419,Sin Movimiento,06/03/2018,02/03/2021,SOL,6200.00,0.35,0.35,2.17,2.11,JESUS EDUARDO,LOPEZ,FERREYRA,19920328,2,46923835,20100130204_0157001_20201122_100.TXT,901001101096240003050550011010969960024944401P...,Error canal,1158,Trama repetida o duplicada

In [163]:
df_desgravamen['MONEDA'].value_counts()

MONEDA
SOL    96880
USD      890
Name: count, dtype: int64

In [ ]:
#df_desgravamen= df_desgravamen.fillna({'LOTES_ANTERIORES':'', 'SUMA_ASEGURADA':0, 'TASA':0, 'PRIMABRUTACAN':0, 'PRIMANETACAN':0,
 #                                      'MONEDA': 'SIN DATO'})

In [164]:
df_desgravamen= df_desgravamen.fillna({'LOTES_ANTERIORES':''})

In [ ]:
df_desgravamen["LOTES_ANTERIORES"] = df_desgravamen["LOTES_ANTERIORES"].astype(str)
df_desgravamen['FECHA_CARGA'] = pd.to_datetime(df_desgravamen['FECHA_CARGA'], errors='coerce')
df_desgravamen['CODIGO_PRODUCTO'] = df_desgravamen['CODIGO_PRODUCTO'].fillna(0).astype('int')
df_desgravamen["PRODUCTO"] = df_desgravamen["PRODUCTO"].astype(str)
df_desgravamen['CODIGO_PLAN'] = df_desgravamen['CODIGO_PLAN'].fillna(0).astype('int')
df_desgravamen["NOMBRE_DE_PLAN"] = df_desgravamen["NOMBRE_DE_PLAN"].astype(str)
df_desgravamen["COD_DE_CERTIFICADO"] = df_desgravamen["COD_DE_CERTIFICADO"].astype(str)
df_desgravamen['FECINI_ALTA_CERTIFICADO'] = pd.to_datetime(df_desgravamen['FECINI_ALTA_CERTIFICADO'], errors='coerce')
df_desgravamen['FECFIN_ALTA_CERTIFICADO'] = pd.to_datetime(df_desgravamen['FECFIN_ALTA_CERTIFICADO'], errors='coerce')
df_desgravamen["TIPO_MOVIMIENTO"] = df_desgravamen["TIPO_MOVIMIENTO"].astype(str)
df_desgravamen['FEC__INICIO'] = pd.to_datetime(df_desgravamen['FEC__INICIO'], format='%d/%m/%Y', errors='coerce')
df_desgravamen['FEC__FIN'] = pd.to_datetime(df_desgravamen['FEC__FIN'], format='%d/%m/%Y', errors='coerce')
df_desgravamen['MONEDA'] = df_desgravamen['MONEDA'].astype(str)
df_desgravamen['NOMCOMPLETO'] = df_desgravamen['NOMCOMPLETO'].astype(str)
df_desgravamen['APEPATERNO'] = df_desgravamen['APEPATERNO'].astype(str)
df_desgravamen['APEMATERNO'] = df_desgravamen['APEMATERNO'].astype(str)
df_desgravamen['FECNACIMIENTO'] = df_desgravamen['FECNACIMIENTO'].astype(str)
df_desgravamen['FECNACIMIENTO'] = pd.to_datetime(df_desgravamen['FECNACIMIENTO'], errors='coerce').dt.date
df_desgravamen['NUMDOCUMENTO'] = df_desgravamen['NUMDOCUMENTO'].astype(str)
df_desgravamen['NOMBRE_DE_ARCHIVO'] = df_desgravamen['NOMBRE_DE_ARCHIVO'].astype(str)
df_desgravamen['LINEA_TRAMA'] = df_desgravamen['LINEA_TRAMA'].astype(str)
df_desgravamen['ORIGEN_ERROR'] = df_desgravamen['ORIGEN_ERROR'].astype(str)
#df_desgravamen['CODIGO_ERROR'] = df_desgravamen['CODIGO_ERROR'].astype(str)
df_desgravamen['DESCRIPCION_ERROR'] = df_desgravamen['DESCRIPCION_ERROR'].astype(str)

In [193]:
df_desgravamen.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97770 entries, 0 to 97769
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   NRO_LOTE                 97770 non-null  int64
 1   LOTES_ANTERIORES         97770 non-null  object
 2   FECHA_CARGA              97770 non-null  datetime64[ns]
 3   CODIGO_PRODUCTO          97770 non-null  int64
 4   PRODUCTO                 97770 non-null  object
 5   CODIGO_PLAN              97770 non-null  int64
 6   NOMBRE_DE_PLAN           97770 non-null  object
 7   COD_DE_CERTIFICADO       97770 non-null  object
 8   FECINI_ALTA_CERTIFICADO  95773 non-null  datetime64[ns]
 9   FECFIN_ALTA_CERTIFICADO  95773 non-null  datetime64[ns]
 10  IDEDET                   97770 non-null  int64
 11  TIPO_MOVIMIENTO          97770 non-null  object
 12  FEC__INICIO              97770 non-null  datetime64[ns]
 13  FEC__FIN                 97770 non-null  datetime64[ns]
 14  MONEDA                   97770 non-null  object
 15  SUMA_ASEGURADA           97770 non-null  float64
 16  TASA                     97770 non-null  float64
 17  TASA_RECARGO             97770 non-null  float64
 18  PRIMABRUTACAN            97770 non-null  float64
 19  PRIMANETACAN             97770 non-null  float64
 20  NOMCOMPLETO              97770 non-null  object
 21  APEPATERNO               97770 non-null  object
 22  APEMATERNO               97770 non-null  object
 23  FECNACIMIENTO            97770 non-null  object
 24  TIPDOCUMENTO             97770 non-null  int64
 25  NUMDOCUMENTO             97770 non-null  object
 26  NOMBRE_DE_ARCHIVO        97770 non-null  object
 27  LINEA_TRAMA              97770 non-null  object
 28  ORIGEN_ERROR             97770 non-null  object
 29  CODIGO_ERROR             97770 non-null  object
 30  DESCRIPCION_ERROR        97770 non-null  object
dtypes: datetime64[ns](5), float64(5), int64(5), object(16)
memory usage: 23.1+ MB

In [173]:
df= df_desgravamen.copy()

In [188]:
df_desgravamen[df_desgravamen['ORIGEN_ERROR'].isna()].head(3)

Empty DataFrame
Columns: [NRO_LOTE, LOTES_ANTERIORES, FECHA_CARGA, CODIGO_PRODUCTO, PRODUCTO, CODIGO_PLAN, NOMBRE_DE_PLAN, COD_DE_CERTIFICADO, FECINI_ALTA_CERTIFICADO, FECFIN_ALTA_CERTIFICADO, IDEDET, TIPO_MOVIMIENTO, FEC__INICIO, FEC__FIN, MONEDA, SUMA_ASEGURADA, TASA, TASA_RECARGO, PRIMABRUTACAN, PRIMANETACAN, NOMCOMPLETO, APEPATERNO, APEMATERNO, FECNACIMIENTO, TIPDOCUMENTO, NUMDOCUMENTO, NOMBRE_DE_ARCHIVO, LINEA_TRAMA, ORIGEN_ERROR, CODIGO_ERROR, DESCRIPCION_ERROR]
Index: []

In [189]:
df_desgravamen['ORIGEN_ERROR'].value_counts()

ORIGEN_ERROR
Error Rimac    95896
Error canal     1874
Name: count, dtype: int64

In [176]:
df_desgravamen.head(3)

,NRO_LOTE,LOTES_ANTERIORES,FECHA_CARGA,CODIGO_PRODUCTO,PRODUCTO,CODIGO_PLAN,NOMBRE_DE_PLAN,COD_DE_CERTIFICADO,FECINI_ALTA_CERTIFICADO,FECFIN_ALTA_CERTIFICADO,IDEDET,TIPO_MOVIMIENTO,FEC__INICIO,FEC__FIN,MONEDA,SUMA_ASEGURADA,TASA,TASA_RECARGO,PRIMABRUTACAN,PRIMANETACAN,NOMCOMPLETO,APEPATERNO,APEMATERNO,FECNACIMIENTO,TIPDOCUMENTO,NUMDOCUMENTO,NOMBRE_DE_ARCHIVO,LINEA_TRAMA,ORIGEN_ERROR,CODIGO_ERROR,DESCRIPCION_ERROR
0,872611,,2022-10-25 17:10:46,0,nan,0,nan,nan,NaT,NaT,555862169,Sin Movimiento,2020-03-03,2024-06-17,SOL,5000.00,0.35,0.35,1.75,1.70,GABRIEL,SALINAS,LORA,19790130,2,40227891,20100130204_0157001_20201122_100.TXT,901001101062040002365100011010629960014659201P...,Error canal,1158,Trama repetida o duplicada
1,872611,,2022-10-25 17:10:46,0,nan,0,nan,nan,NaT,NaT,555862263,Sin Movimiento,2018-04-30,2021-04-05,SOL,63892.89,0.35,0.35,22.36,21.71,JUAN,SANTILLANA,CALLIRGOS,19491019,2,09295733,20100130204_0157001_20201122_100.TXT,901001101062940001863270011010626960011202701P...,Error canal,1158,Trama repetida o duplicada
2,872611,,2022-10-25 17:10:46,0,nan,0,nan,nan,NaT,NaT,555862419,Sin Movimiento,2018-03-06,2021-03-02,SOL,6200.00,0.35,0.35,2.17,2.11,JESUS EDUARDO,LOPEZ,FERREYRA,19920328,2,46923835,20100130204_0157001_20201122_100.TXT,901001101096240003050550011010969960024944401P...,Error canal,1158,Trama repetida o duplicada

In [192]:
#df_desgravamen['COD_DE_CERTIFICADO'] = df_desgravamen['COD_DE_CERTIFICADO'].apply(lambda x: str(int(x)) if pd.notnull(x) else '0')
"""df_desgravamen['CODIGO_PRODUCTO'] = df_desgravamen['CODIGO_PRODUCTO'].fillna(0).astype('int')
df_desgravamen["LOTES_ANTERIORES"] = df_desgravamen["LOTES_ANTERIORES"].astype(str)

df_desgravamen['FECINI_ALTA_CERTIFICADO'] = pd.to_datetime(df_desgravamen['FECINI_ALTA_CERTIFICADO'], errors='coerce')
df_desgravamen['FECFIN_ALTA_CERTIFICADO'] = pd.to_datetime(df_desgravamen['FECFIN_ALTA_CERTIFICADO'], errors='coerce')
df_desgravamen['TIPO_MOVIMIENTO'] = df_desgravamen['TIPO_MOVIMIENTO'].astype(str)
df_desgravamen['FEC__INICIO'] = pd.to_datetime(df_desgravamen['FEC__INICIO'], format='%d/%m/%Y', errors='coerce')
df_desgravamen['FEC__FIN'] = pd.to_datetime(df_desgravamen['FEC__FIN'], format='%d/%m/%Y', errors='coerce')
df_desgravamen['MONEDA'] = df_desgravamen['MONEDA'].astype(str)
df_desgravamen['SUMA_ASEGURADA']= pd.to_numeric(df_desgravamen['SUMA_ASEGURADA'], errors='coerce')
df_desgravamen['TASA']= pd.to_numeric(df_desgravamen['TASA'], errors='coerce')
df_desgravamen['PRIMABRUTACAN']= pd.to_numeric(df_desgravamen['PRIMABRUTACAN'], errors='coerce')
df_desgravamen['PRIMANETACAN']= pd.to_numeric(df_desgravamen['PRIMANETACAN'], errors='coerce')
df_desgravamen['ORIGEN_ERROR'] = df_desgravamen['ORIGEN_ERROR'].fillna(0).astype('int')
"""

'df_desgravamen[\'CODIGO_PRODUCTO\'] = df_desgravamen[\'CODIGO_PRODUCTO\'].fillna(0).astype(\'int\')\ndf_desgravamen["LOTES_ANTERIORES"] = df_desgravamen["LOTES_ANTERIORES"].astype(str)\n\ndf_desgravamen[\'FECINI_ALTA_CERTIFICADO\'] = pd.to_datetime(df_desgravamen[\'FECINI_ALTA_CERTIFICADO\'], errors=\'coerce\')\ndf_desgravamen[\'FECFIN_ALTA_CERTIFICADO\'] = pd.to_datetime(df_desgravamen[\'FECFIN_ALTA_CERTIFICADO\'], errors=\'coerce\')\ndf_desgravamen[\'TIPO_MOVIMIENTO\'] = df_desgravamen[\'TIPO_MOVIMIENTO\'].astype(str)\ndf_desgravamen[\'FEC__INICIO\'] = pd.to_datetime(df_desgravamen[\'FEC__INICIO\'], format=\'%d/%m/%Y\', errors=\'coerce\')\ndf_desgravamen[\'FEC__FIN\'] = pd.to_datetime(df_desgravamen[\'FEC__FIN\'], format=\'%d/%m/%Y\', errors=\'coerce\')\ndf_desgravamen[\'MONEDA\'] = df_desgravamen[\'MONEDA\'].astype(str)\ndf_desgravamen[\'SUMA_ASEGURADA\']= pd.to_numeric(df_desgravamen[\'SUMA_ASEGURADA\'], errors=\'coerce\')\ndf_desgravamen[\'TASA\']= pd.to_numeric(df_desgravamen[\'TASA\'], errors=\'coerce\')\ndf_desgravamen[\'PRIMABRUTACAN\']= pd.to_numeric(df_desgravamen[\'PRIMABRUTACAN\'], errors=\'coerce\')\ndf_desgravamen[\'PRIMANETACAN\']= pd.to_numeric(df_desgravamen[\'PRIMANETACAN\'], errors=\'coerce\')\ndf_desgravamen[\'ORIGEN_ERROR\'] = df_desgravamen[\'ORIGEN_ERROR\'].fillna(0).astype(\'int\')\n'

In [18]:
df_desgravamen[df_desgravamen['FECINI_ALTA_CERTIFICADO'].isnull()]['FECINI_ALTA_CERTIFICADO'].value_counts()

Series([], Name: count, dtype: int64)

In [19]:
#TIPO MOVIMIENTO
df_desgravamen['FECINI_ALTA_CERTIFICADO'].value_counts()  # Counting occurrences of each unique value in the 'TIPO MOVIMIENTO' column

FECINI_ALTA_CERTIFICADO
2015-03-31    134
2014-12-30    124
2015-05-29    114
2015-10-30    106
2015-07-31    105
             ...
2012-08-23      1
2013-01-08      1
2013-05-08      1
2013-03-11      1
2017-01-15      1
Name: count, Length: 1161, dtype: int64

In [22]:
#MONEDA
df_desgravamen['MONEDA'].value_counts()  # Counting occurrences of each unique value in the 'MONEDA' column

MONEDA
SOL         46356
USD          4302
SIN DATO        1
Name: count, dtype: int64

In [23]:
df_desgravamen[df_desgravamen['MONEDA']=='SIN DATO'].head()

,CODIGO_PRODUCTO,LOTES_ANTERIORES,COD_DE_CERTIFICADO,FECINI_ALTA_CERTIFICADO,FECFIN_ALTA_CERTIFICADO,IDEDET,TRAMA,TIPO_MOVIMIENTO,FEC__INICIO,FEC__FIN,MONEDA,SUMA_ASEGURADA,TASA,PRIMABRUTACAN,PRIMANETACAN,NOMBRE_DE_ARCHIVO,ORIGEN_ERROR,TIPO_ERROR,CODIGO_ERROR
46033,0,,NaN,NaT,NaT,132857441,906001102755540002830710011027558960038589901P...,Sin Movimiento,NaT,NaT,SIN DATO,0.0,0.0,0.0,0.0,20100130204_0157001_20160511_001.TXT,132857441,Error canal,193

In [194]:
def extraer_fecha(fecha):
    try:
        fecha_str = fecha.split("_")[2]
        return datetime.strptime(fecha_str, "%Y%m%d").date()
    except Exception:
        return None  # En caso de error

In [195]:
# Aplicar a la columna
df_desgravamen['FECHA_TRAMA'] = df_desgravamen['NOMBRE_DE_ARCHIVO'].apply(extraer_fecha)

In [200]:
df_desgravamen.head(2)

,NRO_LOTE,LOTES_ANTERIORES,FECHA_CARGA,CODIGO_PRODUCTO,PRODUCTO,CODIGO_PLAN,NOMBRE_DE_PLAN,COD_DE_CERTIFICADO,FECINI_ALTA_CERTIFICADO,FECFIN_ALTA_CERTIFICADO,IDEDET,TIPO_MOVIMIENTO,FEC__INICIO,FEC__FIN,MONEDA,SUMA_ASEGURADA,TASA,TASA_RECARGO,PRIMABRUTACAN,PRIMANETACAN,NOMCOMPLETO,APEPATERNO,APEMATERNO,FECNACIMIENTO,TIPDOCUMENTO,NUMDOCUMENTO,NOMBRE_DE_ARCHIVO,LINEA_TRAMA,ORIGEN_ERROR,CODIGO_ERROR,DESCRIPCION_ERROR,FECHA_TRAMA
0,872611,,2022-10-25 17:10:46,0,nan,0,nan,nan,NaT,NaT,555862169,Sin Movimiento,2020-03-03,2024-06-17,SOL,5000.00,0.35,0.35,1.75,1.70,GABRIEL,SALINAS,LORA,19790130,2,40227891,20100130204_0157001_20201122_100.TXT,901001101062040002365100011010629960014659201P...,Error canal,1158,Trama repetida o duplicada,2020-11-22
1,872611,,2022-10-25 17:10:46,0,nan,0,nan,nan,NaT,NaT,555862263,Sin Movimiento,2018-04-30,2021-04-05,SOL,63892.89,0.35,0.35,22.36,21.71,JUAN,SANTILLANA,CALLIRGOS,19491019,2,09295733,20100130204_0157001_20201122_100.TXT,901001101062940001863270011010626960011202701P...,Error canal,1158,Trama repetida o duplicada,2020-11-22

In [199]:
df_desgravamen['FECHA_TRAMA'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 97770 entries, 0 to 97769
Series name: FECHA_TRAMA
Non-Null Count  Dtype
--------------  -----
97770 non-null  datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 764.0 KB

In [198]:
df_desgravamen['FECHA_TRAMA']= pd.to_datetime(df_desgravamen['FECHA_TRAMA'], errors='coerce')

In [203]:
def clasificar(row):
    # Si lote no esta vacio
    if str(row['LOTES_ANTERIORES']).strip() != "":
        return 'Regularizacion no Exitosa'
    
    # Si último número del nombre de archivo > 100
    try:
        ultimo_numero = int(row['NOMBRE_DE_ARCHIVO'].split("_")[-1][:-4])
        if ultimo_numero > 100:
            return 'Regularizacion no Exitosa'
    except:
        pass
    
    # Si ninguna condición se cumple
    return 'Mes corriente'

In [202]:
nombre = '20100130204_0157001_20150409_001_41924.TXT'
numero= int(nombre.split("_")[-1][:-4])
print(numero)

41924

In [204]:
#df_desgravamen['REGULARIZACION']= df_desgravamen['LOTES ANTERIORES'].notnull()
df_desgravamen['STATUS']= df_desgravamen.apply(clasificar, axis=1)

In [205]:
df_desgravamen['STATUS'].value_counts()

STATUS
Mes corriente                97766
Regularizacion no Exitosa        4
Name: count, dtype: int64

In [206]:
df_desgravamen.head(5)

,NRO_LOTE,LOTES_ANTERIORES,FECHA_CARGA,CODIGO_PRODUCTO,PRODUCTO,CODIGO_PLAN,NOMBRE_DE_PLAN,COD_DE_CERTIFICADO,FECINI_ALTA_CERTIFICADO,FECFIN_ALTA_CERTIFICADO,IDEDET,TIPO_MOVIMIENTO,FEC__INICIO,FEC__FIN,MONEDA,SUMA_ASEGURADA,TASA,TASA_RECARGO,PRIMABRUTACAN,PRIMANETACAN,NOMCOMPLETO,APEPATERNO,APEMATERNO,FECNACIMIENTO,TIPDOCUMENTO,NUMDOCUMENTO,NOMBRE_DE_ARCHIVO,LINEA_TRAMA,ORIGEN_ERROR,CODIGO_ERROR,DESCRIPCION_ERROR,FECHA_TRAMA,STATUS
0,872611,,2022-10-25 17:10:46,0,nan,0,nan,nan,NaT,NaT,555862169,Sin Movimiento,2020-03-03,2024-06-17,SOL,5000.00,0.35,0.35,1.75,1.70,GABRIEL,SALINAS,LORA,19790130,2,40227891,20100130204_0157001_20201122_100.TXT,901001101062040002365100011010629960014659201P...,Error canal,1158,Trama repetida o duplicada,2020-11-22,Mes corriente
1,872611,,2022-10-25 17:10:46,0,nan,0,nan,nan,NaT,NaT,555862263,Sin Movimiento,2018-04-30,2021-04-05,SOL,63892.89,0.35,0.35,22.36,21.71,JUAN,SANTILLANA,CALLIRGOS,19491019,2,09295733,20100130204_0157001_20201122_100.TXT,901001101062940001863270011010626960011202701P...,Error canal,1158,Trama repetida o duplicada,2020-11-22,Mes corriente
2,872611,,2022-10-25 17:10:46,0,nan,0,nan,nan,NaT,NaT,555862419,Sin Movimiento,2018-03-06,2021-03-02,SOL,6200.00,0.35,0.35,2.17,2.11,JESUS EDUARDO,LOPEZ,FERREYRA,19920328,2,46923835,20100130204_0157001_20201122_100.TXT,901001101096240003050550011010969960024944401P...,Error canal,1158,Trama repetida o duplicada,2020-11-22,Mes corriente
3,872611,,2022-10-25 17:10:46,0,nan,0,nan,nan,NaT,NaT,555862092,Sin Movimiento,2020-01-16,2020-07-16,SOL,1000.00,0.35,0.35,0.35,0.34,LESLIE,QUISPE,SANTIVA EZ,19970319,2,60246361,20100130204_0157001_20201122_100.TXT,901001101039840005891070011010397960026766001P...,Error canal,1158,Trama repetida o duplicada,2020-11-22,Mes corriente
4,872611,,2022-10-25 17:10:46,0,nan,0,nan,nan,NaT,NaT,555862236,Sin Movimiento,2019-12-10,2021-10-04,SOL,16800.00,0.35,0.35,5.88,5.71,ARTURO FABRICIO,SALAZAR,LACA,19781022,2,17457015,20100130204_0157001_20201122_100.TXT,901001101062640002320000011010621960014102701P...,Error canal,1158,Trama repetida o duplicada,2020-11-22,Mes corriente

In [207]:
df_desgravamen[df_desgravamen['STATUS']=='Mes corriente'].head(6)

,NRO_LOTE,LOTES_ANTERIORES,FECHA_CARGA,CODIGO_PRODUCTO,PRODUCTO,CODIGO_PLAN,NOMBRE_DE_PLAN,COD_DE_CERTIFICADO,FECINI_ALTA_CERTIFICADO,FECFIN_ALTA_CERTIFICADO,IDEDET,TIPO_MOVIMIENTO,FEC__INICIO,FEC__FIN,MONEDA,SUMA_ASEGURADA,TASA,TASA_RECARGO,PRIMABRUTACAN,PRIMANETACAN,NOMCOMPLETO,APEPATERNO,APEMATERNO,FECNACIMIENTO,TIPDOCUMENTO,NUMDOCUMENTO,NOMBRE_DE_ARCHIVO,LINEA_TRAMA,ORIGEN_ERROR,CODIGO_ERROR,DESCRIPCION_ERROR,FECHA_TRAMA,STATUS
0,872611,,2022-10-25 17:10:46,0,nan,0,nan,nan,NaT,NaT,555862169,Sin Movimiento,2020-03-03,2024-06-17,SOL,5000.00,0.35,0.35,1.75,1.70,GABRIEL,SALINAS,LORA,19790130,2,40227891,20100130204_0157001_20201122_100.TXT,901001101062040002365100011010629960014659201P...,Error canal,1158,Trama repetida o duplicada,2020-11-22,Mes corriente
1,872611,,2022-10-25 17:10:46,0,nan,0,nan,nan,NaT,NaT,555862263,Sin Movimiento,2018-04-30,2021-04-05,SOL,63892.89,0.35,0.35,22.36,21.71,JUAN,SANTILLANA,CALLIRGOS,19491019,2,09295733,20100130204_0157001_20201122_100.TXT,901001101062940001863270011010626960011202701P...,Error canal,1158,Trama repetida o duplicada,2020-11-22,Mes corriente
2,872611,,2022-10-25 17:10:46,0,nan,0,nan,nan,NaT,NaT,555862419,Sin Movimiento,2018-03-06,2021-03-02,SOL,6200.00,0.35,0.35,2.17,2.11,JESUS EDUARDO,LOPEZ,FERREYRA,19920328,2,46923835,20100130204_0157001_20201122_100.TXT,901001101096240003050550011010969960024944401P...,Error canal,1158,Trama repetida o duplicada,2020-11-22,Mes corriente
3,872611,,2022-10-25 17:10:46,0,nan,0,nan,nan,NaT,NaT,555862092,Sin Movimiento,2020-01-16,2020-07-16,SOL,1000.00,0.35,0.35,0.35,0.34,LESLIE,QUISPE,SANTIVA EZ,19970319,2,60246361,20100130204_0157001_20201122_100.TXT,901001101039840005891070011010397960026766001P...,Error canal,1158,Trama repetida o duplicada,2020-11-22,Mes corriente
4,872611,,2022-10-25 17:10:46,0,nan,0,nan,nan,NaT,NaT,555862236,Sin Movimiento,2019-12-10,2021-10-04,SOL,16800.00,0.35,0.35,5.88,5.71,ARTURO FABRICIO,SALAZAR,LACA,19781022,2,17457015,20100130204_0157001_20201122_100.TXT,901001101062640002320000011010621960014102701P...,Error canal,1158,Trama repetida o duplicada,2020-11-22,Mes corriente
5,872611,,2022-10-25 17:10:46,0,nan,0,nan,nan,NaT,NaT,555861551,Sin Movimiento,2019-08-05,2020-08-05,SOL,1000.00,0.35,0.35,0.35,0.34,YESSULY MINORKA,PAUCAR,USCACHI,19940208,2,73743507,20100130204_0157001_20201122_100.TXT,901001100833640001640010011008330960003910501P...,Error canal,1158,Trama repetida o duplicada,2020-11-22,Mes corriente

In [208]:
df_errores['CODIGO_ERROR'].value_counts()

CODIGO_ERROR
1068    1
0003    1
1155    1
1150    1
1152    1
1116    1
0114    1
7578    1
0199    1
0011    1
2395    1
1137    1
0163    1
0177    1
1154    1
0155    1
1153    1
1157    1
0117    1
1151    1
9964    1
1608    1
0193    1
0039    1
0034    1
0050    1
0940    1
0035    1
1143    1
9963    1
1045    1
0010    1
9969    1
7460    1
9978    1
7440    1
0130    1
0757    1
0141    1
0317    1
0119    1
1140    1
0852    1
0061    1
1083    1
0022    1
0005    1
1195    1
1135    1
8023    1
1052    1
        1
1136    1
Name: count, dtype: int64

In [61]:
df_errores[df_errores['CODIGO_ERROR'].isna()].head(10)

,CODIGO_ERROR,DESCRIPCION_ERROR,DETALLE,SOLUCION,SOLUCION_2
11,NaN,ERROR EN CARGA DE TRAMA,NI Ãâ°XITO NI ERROR,ANALISIS EMISOR,

In [185]:
df_errores[df_errores['CODIGO_ERROR'].isin({'2395','7440'})].head()

,CODIGO_ERROR,DESCRIPCION_ERROR,DETALLE,SOLUCION,SOLUCION_2
10,2395,ERROR DE TASA,TASA,ANALISIS EMISOR,CONFIGURACION SAS
42,7440,ERROR EDAD,EDAD - MANCOMUNO INEXISTENTE,CONFIGURACION SAS,REGLAS POR CAMBIAR

In [186]:
df_errores[df_errores['CODIGO_ERROR']==' '].head()

,CODIGO_ERROR,DESCRIPCION_ERROR,DETALLE,SOLUCION,SOLUCION_2
62,,SIN DETALLE DE ERROR,SIN DETALLE DE ERROR,ANALISIS EMISOR,VOLVER A CARGAR

In [187]:
df_desgravamen[df_desgravamen['CODIGO_ERROR'].isna()].head(10)

,CODIGO_PRODUCTO,LOTES_ANTERIORES,COD_DE_CERTIFICADO,FECINI_ALTA_CERTIFICADO,FECFIN_ALTA_CERTIFICADO,IDEDET,TRAMA,TIPO_MOVIMIENTO,FEC__INICIO,FEC__FIN,...,SUMA_ASEGURADA,TASA,PRIMABRUTACAN,PRIMANETACAN,NOMBRE_DE_ARCHIVO,ORIGEN_ERROR,TIPO_ERROR,CODIGO_ERROR,FECHA_TRAMA,STATUS
12,3070,,00110727584000239265,NaT,NaT,289247736.0,906001107275840002392650011048600020052715501U...,Renovacion,2019-03-29,2019-04-29,...,0.00,0.00,22.77,22.11,20100130204_0157001_20190404_002.TXT,0,NaN,NaN,2019-04-04,Mes corriente
13,3070,,00110252434000017945,NaT,NaT,289244884.0,906001102524340000179450011025248020008135901P...,Renovacion,2019-03-29,2019-04-29,...,0.00,0.00,70.20,68.16,20100130204_0157001_20190404_002.TXT,0,NaN,NaN,2019-04-04,Mes corriente
14,3070,,00110781244000183779,2014-02-27,2027-02-28,289238827.0,903001107812440001837790011014012020049982601P...,Renovacion,2019-03-11,2019-04-11,...,0.00,0.00,191.80,186.21,20100130204_0157001_20190404_002.TXT,0,NaN,NaN,2019-04-04,Mes corriente
26,3827,,00110130284010524337,NaT,NaT,295967400.0,972001101302840105243370011013023969011141601P...,Inclusion,2018-12-13,2021-01-02,...,10378.68,0.48,0.00,0.00,20100130204_0157001_20190311_002.TXT,295967400,Error Rimac,NaN,2019-03-11,Mes corriente
27,3827,,00110130284010524337,NaT,NaT,295967400.0,972001101302840105243370011013023969011141601P...,Inclusion,2018-12-13,2021-01-02,...,10378.68,0.48,0.00,0.00,20100130204_0157001_20190311_002.TXT,295967400,Error Rimac,NaN,2019-03-11,Mes corriente
28,3827,,00110130284010524337,NaT,NaT,295967400.0,972001101302840105243370011013023969011141601P...,Inclusion,2018-12-13,2021-01-02,...,10378.68,0.48,0.00,0.00,20100130204_0157001_20190311_002.TXT,295967400,Error Rimac,NaN,2019-03-11,Mes corriente
29,3827,,00110130284010524337,NaT,NaT,295967400.0,972001101302840105243370011013023969011141601P...,Inclusion,2018-12-13,2021-01-02,...,10378.68,0.48,0.00,0.00,20100130204_0157001_20190311_002.TXT,295967400,Error Rimac,NaN,2019-03-11,Mes corriente
42,3070,,00110252434000017945,NaT,NaT,313042743.0,906001102524340000179450011025248020008135901P...,Renovacion,2019-07-31,2019-08-31,...,0.00,0.00,70.20,68.16,20100130204_0157001_20190806_003.TXT,313042743,Error Rimac,NaN,2019-08-06,Mes corriente
43,3070,,00110252434000017945,NaT,NaT,313042743.0,906001102524340000179450011025248020008135901P...,Renovacion,2019-07-31,2019-08-31,...,0.00,0.00,70.20,68.16,20100130204_0157001_20190806_003.TXT,313042743,Error Rimac,NaN,2019-08-06,Mes corriente
44,3070,,00110252434000017945,NaT,NaT,313042743.0,906001102524340000179450011025248020008135901P...,Renovacion,2019-07-31,2019-08-31,...,0.00,0.00,70.20,68.16,20100130204_0157001_20190806_003.TXT,313042743,Error Rimac,NaN,2019-08-06,Mes corriente

In [188]:
df_desgravamen[df_desgravamen['CODIGO_ERROR']==''].head()

Empty DataFrame
Columns: [CODIGO_PRODUCTO, LOTES_ANTERIORES, COD_DE_CERTIFICADO, FECINI_ALTA_CERTIFICADO, FECFIN_ALTA_CERTIFICADO, IDEDET, TRAMA, TIPO_MOVIMIENTO, FEC__INICIO, FEC__FIN, MONEDA, SUMA_ASEGURADA, TASA, PRIMABRUTACAN, PRIMANETACAN, NOMBRE_DE_ARCHIVO, ORIGEN_ERROR, TIPO_ERROR, CODIGO_ERROR, FECHA_TRAMA, STATUS]
Index: []

[0 rows x 21 columns]

In [189]:
df_errores.info()

<class 'pandas.core.frame.DataFrame'>
Index: 54 entries, 0 to 63
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CODIGO_ERROR       53 non-null     object
 1   DESCRIPCION_ERROR  54 non-null     object
 2   DETALLE            54 non-null     object
 3   SOLUCION           54 non-null     object
 4   SOLUCION_2         54 non-null     object
dtypes: object(5)
memory usage: 2.5+ KB

In [190]:
df= df_desgravamen.merge(df_errores, on='CODIGO_ERROR', how='left')

In [192]:
df.head(3)

,CODIGO_PRODUCTO,LOTES_ANTERIORES,COD_DE_CERTIFICADO,FECINI_ALTA_CERTIFICADO,FECFIN_ALTA_CERTIFICADO,IDEDET,TRAMA,TIPO_MOVIMIENTO,FEC__INICIO,FEC__FIN,...,NOMBRE_DE_ARCHIVO,ORIGEN_ERROR,TIPO_ERROR,CODIGO_ERROR,FECHA_TRAMA,STATUS,DESCRIPCION_ERROR,DETALLE,SOLUCION,SOLUCION_2
0,0,,NaN,NaT,NaT,289236134.0,903001104868240007432580011048681020074429601U...,Sin Movimiento,2019-03-15,2019-04-15,...,20100130204_0157001_20190404_002.TXT,289236134,Error canal,1155,2019-04-04,Mes corriente,TRAMA REPETIDA O DUPLICADA,TRAMA REPETIDA O DUPLICADA,CONFIGURACION SAS,ANULAR MASIVAS
1,0,,NaN,NaT,NaT,289235584.0,903001104264440000623340011042641020015853501P...,Sin Movimiento,2019-03-01,2019-04-01,...,20100130204_0157001_20190404_002.TXT,289235584,Error canal,1155,2019-04-04,Mes corriente,TRAMA REPETIDA O DUPLICADA,TRAMA REPETIDA O DUPLICADA,CONFIGURACION SAS,ANULAR MASIVAS
2,0,,NaN,NaT,NaT,289239811.0,903001108315440008473680011012373020027799501P...,Sin Movimiento,2019-03-01,2019-04-01,...,20100130204_0157001_20190404_002.TXT,289239811,Error canal,1155,2019-04-04,Mes corriente,TRAMA REPETIDA O DUPLICADA,TRAMA REPETIDA O DUPLICADA,CONFIGURACION SAS,ANULAR MASIVAS

In [193]:
df[df['CODIGO_ERROR'].isna()].head(10)

,CODIGO_PRODUCTO,LOTES_ANTERIORES,COD_DE_CERTIFICADO,FECINI_ALTA_CERTIFICADO,FECFIN_ALTA_CERTIFICADO,IDEDET,TRAMA,TIPO_MOVIMIENTO,FEC__INICIO,FEC__FIN,...,NOMBRE_DE_ARCHIVO,ORIGEN_ERROR,TIPO_ERROR,CODIGO_ERROR,FECHA_TRAMA,STATUS,DESCRIPCION_ERROR,DETALLE,SOLUCION,SOLUCION_2
12,3070,,00110727584000239265,NaT,NaT,289247736.0,906001107275840002392650011048600020052715501U...,Renovacion,2019-03-29,2019-04-29,...,20100130204_0157001_20190404_002.TXT,0,NaN,NaN,2019-04-04,Mes corriente,ERROR EN CARGA DE TRAMA,NI ÃXITO NI ERROR,ANALISIS EMISOR,
13,3070,,00110252434000017945,NaT,NaT,289244884.0,906001102524340000179450011025248020008135901P...,Renovacion,2019-03-29,2019-04-29,...,20100130204_0157001_20190404_002.TXT,0,NaN,NaN,2019-04-04,Mes corriente,ERROR EN CARGA DE TRAMA,NI ÃXITO NI ERROR,ANALISIS EMISOR,
14,3070,,00110781244000183779,2014-02-27,2027-02-28,289238827.0,903001107812440001837790011014012020049982601P...,Renovacion,2019-03-11,2019-04-11,...,20100130204_0157001_20190404_002.TXT,0,NaN,NaN,2019-04-04,Mes corriente,ERROR EN CARGA DE TRAMA,NI ÃXITO NI ERROR,ANALISIS EMISOR,
26,3827,,00110130284010524337,NaT,NaT,295967400.0,972001101302840105243370011013023969011141601P...,Inclusion,2018-12-13,2021-01-02,...,20100130204_0157001_20190311_002.TXT,295967400,Error Rimac,NaN,2019-03-11,Mes corriente,ERROR EN CARGA DE TRAMA,NI ÃXITO NI ERROR,ANALISIS EMISOR,
27,3827,,00110130284010524337,NaT,NaT,295967400.0,972001101302840105243370011013023969011141601P...,Inclusion,2018-12-13,2021-01-02,...,20100130204_0157001_20190311_002.TXT,295967400,Error Rimac,NaN,2019-03-11,Mes corriente,ERROR EN CARGA DE TRAMA,NI ÃXITO NI ERROR,ANALISIS EMISOR,
28,3827,,00110130284010524337,NaT,NaT,295967400.0,972001101302840105243370011013023969011141601P...,Inclusion,2018-12-13,2021-01-02,...,20100130204_0157001_20190311_002.TXT,295967400,Error Rimac,NaN,2019-03-11,Mes corriente,ERROR EN CARGA DE TRAMA,NI ÃXITO NI ERROR,ANALISIS EMISOR,
29,3827,,00110130284010524337,NaT,NaT,295967400.0,972001101302840105243370011013023969011141601P...,Inclusion,2018-12-13,2021-01-02,...,20100130204_0157001_20190311_002.TXT,295967400,Error Rimac,NaN,2019-03-11,Mes corriente,ERROR EN CARGA DE TRAMA,NI ÃXITO NI ERROR,ANALISIS EMISOR,
42,3070,,00110252434000017945,NaT,NaT,313042743.0,906001102524340000179450011025248020008135901P...,Renovacion,2019-07-31,2019-08-31,...,20100130204_0157001_20190806_003.TXT,313042743,Error Rimac,NaN,2019-08-06,Mes corriente,ERROR EN CARGA DE TRAMA,NI ÃXITO NI ERROR,ANALISIS EMISOR,
43,3070,,00110252434000017945,NaT,NaT,313042743.0,906001102524340000179450011025248020008135901P...,Renovacion,2019-07-31,2019-08-31,...,20100130204_0157001_20190806_003.TXT,313042743,Error Rimac,NaN,2019-08-06,Mes corriente,ERROR EN CARGA DE TRAMA,NI ÃXITO NI ERROR,ANALISIS EMISOR,
44,3070,,00110252434000017945,NaT,NaT,313042743.0,906001102524340000179450011025248020008135901P...,Renovacion,2019-07-31,2019-08-31,...,20100130204_0157001_20190806_003.TXT,313042743,Error Rimac,NaN,2019-08-06,Mes corriente,ERROR EN CARGA DE TRAMA,NI ÃXITO NI ERROR,ANALISIS EMISOR,

In [194]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42019 entries, 0 to 42018
Data columns (total 25 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   CODIGO_PRODUCTO          42019 non-null  int64
 1   LOTES_ANTERIORES         42019 non-null  object
 2   COD_DE_CERTIFICADO       6959 non-null   object
 3   FECINI_ALTA_CERTIFICADO  2866 non-null   datetime64[ns]
 4   FECFIN_ALTA_CERTIFICADO  2866 non-null   datetime64[ns]
 5   IDEDET                   42007 non-null  float64
 6   TRAMA                    42007 non-null  object
 7   TIPO_MOVIMIENTO          42019 non-null  object
 8   FEC__INICIO              41570 non-null  datetime64[ns]
 9   FEC__FIN                 41544 non-null  datetime64[ns]
 10  MONEDA                   42019 non-null  object
 11  SUMA_ASEGURADA           42005 non-null  float64
 12  TASA                     42019 non-null  float64
 13  PRIMABRUTACAN            42005 non-null  float64
 14  PRIMANETACAN             42019 non-null  float64
 15  NOMBRE_DE_ARCHIVO        42007 non-null  object
 16  ORIGEN_ERROR             42019 non-null  int64
 17  TIPO_ERROR               41310 non-null  object
 18  CODIGO_ERROR             40379 non-null  object
 19  FECHA_TRAMA              42007 non-null  datetime64[ns]
 20  STATUS                   42019 non-null  object
 21  DESCRIPCION_ERROR        2541 non-null   object
 22  DETALLE                  2541 non-null   object
 23  SOLUCION                 2541 non-null   object
 24  SOLUCION_2               2541 non-null   object
dtypes: datetime64[ns](5), float64(5), int64(2), object(13)
memory usage: 8.0+ MB