In [53]:
import pandas as pd
from datetime import datetime
import warnings
warnings.filterwarnings("ignore", category=UserWarning, module="openpyxl")
import os
import numpy as np
pd.set_option('display.max_columns', None)

In [54]:
df_errores= pd.read_excel('c:/data/tabla_errores.xlsx', sheet_name='Sheet1', dtype={'CODIGO_ERROR': str})
df_errores.head(3)

,CODIGO_ERROR,DESCRIPCION_ERROR,DETALLE,SOLUCION,SOLUCION_2
0,1068,YA EXISTE UN PAGO CON LA MISMA FECHA DE INICIO...,YA EXISTE UN PAGO CON LA MISMA FECHA DE INICIO...,CONFIGURACION SAS,ANULAR MASIVAS
1,0003,ERROR EN CARGA DE TRAMA,ERROR EN CARGA DE TRAMA,ANALISIS EMISOR,NaN
2,1155,TRAMA REPETIDA O DUPLICADA,TRAMA REPETIDA O DUPLICADA,CONFIGURACION SAS,ANULAR MASIVAS

In [30]:
df_errores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53 entries, 0 to 52
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CODIGO_ERROR       52 non-null     object
 1   DESCRIPCION_ERROR  53 non-null     object
 2   DETALLE            53 non-null     object
 3   SOLUCION           53 non-null     object
 4   SOLUCION_2         19 non-null     object
dtypes: object(5)
memory usage: 2.2+ KB

In [ ]:
#df_errores.to_excel('c:/data/tabla_errores.xlsx', index=False)

In [55]:
# Se carga el dataset en excel de Accidentes mortales
df_desgravamen= pd.read_excel('C:/data/Reporte de errores/446 - Desgravamen - 03.xlsx', sheet_name='Sheet1', 
                              dtype={'COD DE CERTIFICADO': str, 'DESCRIPCION ERROR': str, 'IDELOTE': str, 'CODIGO ERROR': str})

In [56]:
df_desgravamen.head(2)

,NRO LOTE,LOTES ANTERIORES,FECHA CARGA,CODIGO PRODUCTO,PRODUCTO,CODIGO PLAN,NOMBRE DE PLAN,COD DE CERTIFICADO,fecini_alta_CERTIFICADO,fecfin_alta_CERTIFICADO,IDEDET,TIPO MOVIMIENTO,FEC. INICIO,FEC. FIN,MONEDA,SUMA ASEGURADA,TASA,TASA RECARGO,PRIMABRUTACAN,PRIMANETACAN,NOMCOMPLETO,APEPATERNO,APEMATERNO,FECNACIMIENTO,TIPDOCUMENTO,NUMDOCUMENTO,NOMBRE DE ARCHIVO,LINEA TRAMA,IDELOTE,IDEDET.1,ORIGEN ERROR,CODIGO ERROR,DESCRIPCION ERROR
0,872654,NaN,2022-10-25 17:52:43,3827.0,Desgravamen + Desempleo BBVA,89705.0,Plan Contifacil,00110814174001203143,2019-12-30,2022-12-30,556035505,Exclusion,30/12/2019,30/12/2022,SOL,2800.0,0.35,0.35,0.98,0.95,NEISER,IPARRAGUIRRE,MU?OZ,19880329.0,2.0,44994753,20100130204_0157001_20201122_101.TXT,901001108141740012031430011081410960091807101P...,872654,556035505,Error canal,986,EL NUMERO DE CERTIFICADO [00110814174001203143...
1,872654,NaN,2022-10-25 17:52:43,3827.0,Desgravamen + Desempleo BBVA,89705.0,Plan Contifacil,00110814174001203143,2019-12-30,2022-12-30,556035505,Exclusion,30/12/2019,30/12/2022,SOL,2800.0,0.35,0.35,0.98,0.95,NEISER,IPARRAGUIRRE,MU?OZ,19880329.0,2.0,44994753,20100130204_0157001_20201122_101.TXT,901001108141740012031430011081410960091807101P...,872654,556035505,Error canal,2025,EL CAMPO FECEXCLUSION DEL(A) CERTIFICADO DEBE ...

In [93]:
df_desgravamen.columns = (
    df_desgravamen.columns
    .str.strip()  # quitar espacios al inicio/fin
    .str.upper()  # opcional: todo en mayúsculas
    .str.replace(r'[^A-Za-z0-9]', '_', regex=True)  # reemplazar todo lo que no sea letra/número/_ por _
)

In [94]:
df_desgravamen.drop(['IDELOTE','IDEDET_1','DESCRIPCION_ERROR'], axis=1, inplace=True)

KeyError: "['IDELOTE', 'IDEDET_1', 'DESCRIPCION_ERROR'] not found in axis"

In [ ]:
#df_desgravamen= df_desgravamen.rename(columns={'CODIGO_ERROR': 'TIPO_ERROR',
 #                                              'DESCRIPCION_ERROR': 'CODIGO_ERROR',
  #                                             'IDELOTE': 'TRAMA'}) # cambiar nombre de las columnas

In [ ]:
#df_desgravamen= df_desgravamen[['CODIGO_PRODUCTO', 'LOTES_ANTERIORES','COD_DE_CERTIFICADO', 'FECINI_ALTA_CERTIFICADO', 
 #                               'FECFIN_ALTA_CERTIFICADO','IDEDET', 'TRAMA', 'TIPO_MOVIMIENTO', 'FEC__INICIO', 
  #                              'FEC__FIN', 'MONEDA', 'SUMA_ASEGURADA', 'TASA', 'PRIMABRUTACAN', 'PRIMANETACAN', 
   #                             'NOMBRE_DE_ARCHIVO', 'ORIGEN_ERROR', 'TIPO_ERROR', 'CODIGO_ERROR']]

In [59]:
df_desgravamen.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119541 entries, 0 to 119540
Data columns (total 30 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   NRO_LOTE                 119541 non-null  int64
 1   LOTES_ANTERIORES         876 non-null     object
 2   FECHA_CARGA              119541 non-null  datetime64[ns]
 3   CODIGO_PRODUCTO          119437 non-null  float64
 4   PRODUCTO                 119437 non-null  object
 5   CODIGO_PLAN              119437 non-null  float64
 6   NOMBRE_DE_PLAN           119437 non-null  object
 7   COD_DE_CERTIFICADO       119437 non-null  object
 8   FECINI_ALTA_CERTIFICADO  117979 non-null  datetime64[ns]
 9   FECFIN_ALTA_CERTIFICADO  117979 non-null  datetime64[ns]
 10  IDEDET                   119541 non-null  int64
 11  TIPO_MOVIMIENTO          119541 non-null  object
 12  FEC__INICIO              118964 non-null  object
 13  FEC__FIN                 118964 non-null  object
 14  MONEDA                   119541 non-null  object
 15  SUMA_ASEGURADA           119541 non-null  float64
 16  TASA                     119541 non-null  float64
 17  TASA_RECARGO             119541 non-null  float64
 18  PRIMABRUTACAN            119541 non-null  float64
 19  PRIMANETACAN             119541 non-null  float64
 20  NOMCOMPLETO              118964 non-null  object
 21  APEPATERNO               119541 non-null  object
 22  APEMATERNO               119541 non-null  object
 23  FECNACIMIENTO            118964 non-null  float64
 24  TIPDOCUMENTO             118964 non-null  float64
 25  NUMDOCUMENTO             118964 non-null  object
 26  NOMBRE_DE_ARCHIVO        119541 non-null  object
 27  LINEA_TRAMA              119541 non-null  object
 28  ORIGEN_ERROR             119541 non-null  object
 29  CODIGO_ERROR             119541 non-null  object
dtypes: datetime64[ns](3), float64(9), int64(2), object(16)
memory usage: 27.4+ MB

In [60]:
df_desgravamen[df_desgravamen['CODIGO_ERROR'].isna()].head(3)

Empty DataFrame
Columns: [NRO_LOTE, LOTES_ANTERIORES, FECHA_CARGA, CODIGO_PRODUCTO, PRODUCTO, CODIGO_PLAN, NOMBRE_DE_PLAN, COD_DE_CERTIFICADO, FECINI_ALTA_CERTIFICADO, FECFIN_ALTA_CERTIFICADO, IDEDET, TIPO_MOVIMIENTO, FEC__INICIO, FEC__FIN, MONEDA, SUMA_ASEGURADA, TASA, TASA_RECARGO, PRIMABRUTACAN, PRIMANETACAN, NOMCOMPLETO, APEPATERNO, APEMATERNO, FECNACIMIENTO, TIPDOCUMENTO, NUMDOCUMENTO, NOMBRE_DE_ARCHIVO, LINEA_TRAMA, ORIGEN_ERROR, CODIGO_ERROR]
Index: []

In [61]:
df_desgravamen['MONEDA'].value_counts()

MONEDA
SOL    118616
USD       925
Name: count, dtype: int64

In [ ]:
#df_desgravamen= df_desgravamen.fillna({'LOTES_ANTERIORES':'', 'SUMA_ASEGURADA':0, 'TASA':0, 'PRIMABRUTACAN':0, 'PRIMANETACAN':0,
 #                                      'MONEDA': 'SIN DATO'})

In [62]:
df_desgravamen= df_desgravamen.fillna({'LOTES_ANTERIORES':'', 'MONEDA': 'SIN DATO', 'ORIGEN_ERROR': 'SIN DATO', 'TIPDOCUMENTO':'SIN DATO'})
df_desgravamen.loc[df_desgravamen['MONEDA'] == 'nan', 'MONEDA'] = 'SIN DATO'
df_desgravamen.loc[df_desgravamen['ORIGEN_ERROR'] == 'nan', 'ORIGEN_ERROR'] = 'SIN DATO'

In [63]:
df_desgravamen["LOTES_ANTERIORES"] = df_desgravamen["LOTES_ANTERIORES"].astype(str)
df_desgravamen['FECHA_CARGA'] = pd.to_datetime(df_desgravamen['FECHA_CARGA'], errors='coerce')
df_desgravamen['CODIGO_PRODUCTO'] = df_desgravamen['CODIGO_PRODUCTO'].fillna(0).astype('int')
df_desgravamen["PRODUCTO"] = df_desgravamen["PRODUCTO"].astype(str)
df_desgravamen['CODIGO_PLAN'] = df_desgravamen['CODIGO_PLAN'].fillna(0).astype('int')
df_desgravamen["NOMBRE_DE_PLAN"] = df_desgravamen["NOMBRE_DE_PLAN"].astype(str)
df_desgravamen["COD_DE_CERTIFICADO"] = df_desgravamen["COD_DE_CERTIFICADO"].astype(str)
df_desgravamen['FECINI_ALTA_CERTIFICADO'] = pd.to_datetime(df_desgravamen['FECINI_ALTA_CERTIFICADO'], errors='coerce')
df_desgravamen['FECFIN_ALTA_CERTIFICADO'] = pd.to_datetime(df_desgravamen['FECFIN_ALTA_CERTIFICADO'], errors='coerce')
df_desgravamen["TIPO_MOVIMIENTO"] = df_desgravamen["TIPO_MOVIMIENTO"].astype(str)
df_desgravamen['FEC__INICIO'] = pd.to_datetime(df_desgravamen['FEC__INICIO'], format='%d/%m/%Y', errors='coerce')
df_desgravamen['FEC__FIN'] = pd.to_datetime(df_desgravamen['FEC__FIN'], format='%d/%m/%Y', errors='coerce')
df_desgravamen['MONEDA'] = df_desgravamen['MONEDA'].astype(str)
df_desgravamen['TASA_RECARGO'] = pd.to_numeric(df_desgravamen['TASA_RECARGO'], errors='coerce')
df_desgravamen['NOMCOMPLETO'] = df_desgravamen['NOMCOMPLETO'].astype(str)
df_desgravamen['APEPATERNO'] = df_desgravamen['APEPATERNO'].astype(str)
df_desgravamen['APEMATERNO'] = df_desgravamen['APEMATERNO'].astype(str)
df_desgravamen['FECNACIMIENTO'] = df_desgravamen['FECNACIMIENTO'].astype(str)
df_desgravamen['FECNACIMIENTO'] = pd.to_datetime(df_desgravamen['FECNACIMIENTO'], errors='coerce')
df_desgravamen["TIPDOCUMENTO"] = df_desgravamen["TIPDOCUMENTO"].astype(str)
df_desgravamen['NUMDOCUMENTO'] = df_desgravamen['NUMDOCUMENTO'].astype(str)
df_desgravamen['NOMBRE_DE_ARCHIVO'] = df_desgravamen['NOMBRE_DE_ARCHIVO'].astype(str)
df_desgravamen['LINEA_TRAMA'] = df_desgravamen['LINEA_TRAMA'].astype(str)
df_desgravamen['ORIGEN_ERROR'] = df_desgravamen['ORIGEN_ERROR'].astype(str)
df_desgravamen['CODIGO_ERROR'] = df_desgravamen['CODIGO_ERROR'].apply(lambda x: str(int(x)).zfill(4) if pd.notnull(x) else np.nan)

C:\Users\nvelazco\AppData\Local\Temp\ipykernel_12684\1175641090.py:19: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_desgravamen['FECNACIMIENTO'] = pd.to_datetime(df_desgravamen['FECNACIMIENTO'], errors='coerce')

In [64]:
df_desgravamen.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119541 entries, 0 to 119540
Data columns (total 30 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   NRO_LOTE                 119541 non-null  int64
 1   LOTES_ANTERIORES         119541 non-null  object
 2   FECHA_CARGA              119541 non-null  datetime64[ns]
 3   CODIGO_PRODUCTO          119541 non-null  int64
 4   PRODUCTO                 119541 non-null  object
 5   CODIGO_PLAN              119541 non-null  int64
 6   NOMBRE_DE_PLAN           119541 non-null  object
 7   COD_DE_CERTIFICADO       119541 non-null  object
 8   FECINI_ALTA_CERTIFICADO  117979 non-null  datetime64[ns]
 9   FECFIN_ALTA_CERTIFICADO  117979 non-null  datetime64[ns]
 10  IDEDET                   119541 non-null  int64
 11  TIPO_MOVIMIENTO          119541 non-null  object
 12  FEC__INICIO              118964 non-null  datetime64[ns]
 13  FEC__FIN                 118964 non-null  datetime64[ns]
 14  MONEDA                   119541 non-null  object
 15  SUMA_ASEGURADA           119541 non-null  float64
 16  TASA                     119541 non-null  float64
 17  TASA_RECARGO             119541 non-null  float64
 18  PRIMABRUTACAN            119541 non-null  float64
 19  PRIMANETACAN             119541 non-null  float64
 20  NOMCOMPLETO              119541 non-null  object
 21  APEPATERNO               119541 non-null  object
 22  APEMATERNO               119541 non-null  object
 23  FECNACIMIENTO            0 non-null       datetime64[ns]
 24  TIPDOCUMENTO             119541 non-null  object
 25  NUMDOCUMENTO             119541 non-null  object
 26  NOMBRE_DE_ARCHIVO        119541 non-null  object
 27  LINEA_TRAMA              119541 non-null  object
 28  ORIGEN_ERROR             119541 non-null  object
 29  CODIGO_ERROR             119541 non-null  object
dtypes: datetime64[ns](6), float64(5), int64(4), object(15)
memory usage: 27.4+ MB

In [65]:
df= df_desgravamen.copy()

In [67]:
df_desgravamen[df_desgravamen['LOTES_ANTERIORES']==""].head(3)

,NRO_LOTE,LOTES_ANTERIORES,FECHA_CARGA,CODIGO_PRODUCTO,PRODUCTO,CODIGO_PLAN,NOMBRE_DE_PLAN,COD_DE_CERTIFICADO,FECINI_ALTA_CERTIFICADO,FECFIN_ALTA_CERTIFICADO,IDEDET,TIPO_MOVIMIENTO,FEC__INICIO,FEC__FIN,MONEDA,SUMA_ASEGURADA,TASA,TASA_RECARGO,PRIMABRUTACAN,PRIMANETACAN,NOMCOMPLETO,APEPATERNO,APEMATERNO,FECNACIMIENTO,TIPDOCUMENTO,NUMDOCUMENTO,NOMBRE_DE_ARCHIVO,LINEA_TRAMA,ORIGEN_ERROR,CODIGO_ERROR
0,872654,,2022-10-25 17:52:43,3827,Desgravamen + Desempleo BBVA,89705,Plan Contifacil,00110814174001203143,2019-12-30,2022-12-30,556035505,Exclusion,2019-12-30,2022-12-30,SOL,2800.0,0.35,0.35,0.98,0.95,NEISER,IPARRAGUIRRE,MU?OZ,NaT,2.0,44994753,20100130204_0157001_20201122_101.TXT,901001108141740012031430011081410960091807101P...,Error canal,0986
1,872654,,2022-10-25 17:52:43,3827,Desgravamen + Desempleo BBVA,89705,Plan Contifacil,00110814174001203143,2019-12-30,2022-12-30,556035505,Exclusion,2019-12-30,2022-12-30,SOL,2800.0,0.35,0.35,0.98,0.95,NEISER,IPARRAGUIRRE,MU?OZ,NaT,2.0,44994753,20100130204_0157001_20201122_101.TXT,901001108141740012031430011081410960091807101P...,Error canal,2025
2,872654,,2022-10-25 17:52:43,3827,Desgravamen + Desempleo BBVA,89705,Plan Contifacil,00110814184000055299,2016-09-26,2020-09-28,556035940,Exclusion,2016-09-26,2020-09-28,SOL,6200.0,0.35,0.35,2.17,2.11,JAIRO LUIS,FEIJOO,DEL ROSARIO,NaT,2.0,41618166,20100130204_0157001_20201122_101.TXT,901001108141840000552990011081416960004645701P...,Error canal,0843

In [68]:
df_desgravamen['ORIGEN_ERROR'].value_counts()

ORIGEN_ERROR
Error Rimac    115901
Error canal      3640
Name: count, dtype: int64

In [66]:
df_desgravamen.head(3)

,NRO_LOTE,LOTES_ANTERIORES,FECHA_CARGA,CODIGO_PRODUCTO,PRODUCTO,CODIGO_PLAN,NOMBRE_DE_PLAN,COD_DE_CERTIFICADO,FECINI_ALTA_CERTIFICADO,FECFIN_ALTA_CERTIFICADO,IDEDET,TIPO_MOVIMIENTO,FEC__INICIO,FEC__FIN,MONEDA,SUMA_ASEGURADA,TASA,TASA_RECARGO,PRIMABRUTACAN,PRIMANETACAN,NOMCOMPLETO,APEPATERNO,APEMATERNO,FECNACIMIENTO,TIPDOCUMENTO,NUMDOCUMENTO,NOMBRE_DE_ARCHIVO,LINEA_TRAMA,ORIGEN_ERROR,CODIGO_ERROR
0,872654,,2022-10-25 17:52:43,3827,Desgravamen + Desempleo BBVA,89705,Plan Contifacil,00110814174001203143,2019-12-30,2022-12-30,556035505,Exclusion,2019-12-30,2022-12-30,SOL,2800.0,0.35,0.35,0.98,0.95,NEISER,IPARRAGUIRRE,MU?OZ,NaT,2.0,44994753,20100130204_0157001_20201122_101.TXT,901001108141740012031430011081410960091807101P...,Error canal,0986
1,872654,,2022-10-25 17:52:43,3827,Desgravamen + Desempleo BBVA,89705,Plan Contifacil,00110814174001203143,2019-12-30,2022-12-30,556035505,Exclusion,2019-12-30,2022-12-30,SOL,2800.0,0.35,0.35,0.98,0.95,NEISER,IPARRAGUIRRE,MU?OZ,NaT,2.0,44994753,20100130204_0157001_20201122_101.TXT,901001108141740012031430011081410960091807101P...,Error canal,2025
2,872654,,2022-10-25 17:52:43,3827,Desgravamen + Desempleo BBVA,89705,Plan Contifacil,00110814184000055299,2016-09-26,2020-09-28,556035940,Exclusion,2016-09-26,2020-09-28,SOL,6200.0,0.35,0.35,2.17,2.11,JAIRO LUIS,FEIJOO,DEL ROSARIO,NaT,2.0,41618166,20100130204_0157001_20201122_101.TXT,901001108141840000552990011081416960004645701P...,Error canal,0843

In [192]:
#df_desgravamen['COD_DE_CERTIFICADO'] = df_desgravamen['COD_DE_CERTIFICADO'].apply(lambda x: str(int(x)) if pd.notnull(x) else '0')
"""df_desgravamen['CODIGO_PRODUCTO'] = df_desgravamen['CODIGO_PRODUCTO'].fillna(0).astype('int')
df_desgravamen["LOTES_ANTERIORES"] = df_desgravamen["LOTES_ANTERIORES"].astype(str)

df_desgravamen['FECINI_ALTA_CERTIFICADO'] = pd.to_datetime(df_desgravamen['FECINI_ALTA_CERTIFICADO'], errors='coerce')
df_desgravamen['FECFIN_ALTA_CERTIFICADO'] = pd.to_datetime(df_desgravamen['FECFIN_ALTA_CERTIFICADO'], errors='coerce')
df_desgravamen['TIPO_MOVIMIENTO'] = df_desgravamen['TIPO_MOVIMIENTO'].astype(str)
df_desgravamen['FEC__INICIO'] = pd.to_datetime(df_desgravamen['FEC__INICIO'], format='%d/%m/%Y', errors='coerce')
df_desgravamen['FEC__FIN'] = pd.to_datetime(df_desgravamen['FEC__FIN'], format='%d/%m/%Y', errors='coerce')
df_desgravamen['MONEDA'] = df_desgravamen['MONEDA'].astype(str)
df_desgravamen['SUMA_ASEGURADA']= pd.to_numeric(df_desgravamen['SUMA_ASEGURADA'], errors='coerce')
df_desgravamen['TASA']= pd.to_numeric(df_desgravamen['TASA'], errors='coerce')
df_desgravamen['PRIMABRUTACAN']= pd.to_numeric(df_desgravamen['PRIMABRUTACAN'], errors='coerce')
df_desgravamen['PRIMANETACAN']= pd.to_numeric(df_desgravamen['PRIMANETACAN'], errors='coerce')
df_desgravamen['ORIGEN_ERROR'] = df_desgravamen['ORIGEN_ERROR'].fillna(0).astype('int')
"""

'df_desgravamen[\'CODIGO_PRODUCTO\'] = df_desgravamen[\'CODIGO_PRODUCTO\'].fillna(0).astype(\'int\')\ndf_desgravamen["LOTES_ANTERIORES"] = df_desgravamen["LOTES_ANTERIORES"].astype(str)\n\ndf_desgravamen[\'FECINI_ALTA_CERTIFICADO\'] = pd.to_datetime(df_desgravamen[\'FECINI_ALTA_CERTIFICADO\'], errors=\'coerce\')\ndf_desgravamen[\'FECFIN_ALTA_CERTIFICADO\'] = pd.to_datetime(df_desgravamen[\'FECFIN_ALTA_CERTIFICADO\'], errors=\'coerce\')\ndf_desgravamen[\'TIPO_MOVIMIENTO\'] = df_desgravamen[\'TIPO_MOVIMIENTO\'].astype(str)\ndf_desgravamen[\'FEC__INICIO\'] = pd.to_datetime(df_desgravamen[\'FEC__INICIO\'], format=\'%d/%m/%Y\', errors=\'coerce\')\ndf_desgravamen[\'FEC__FIN\'] = pd.to_datetime(df_desgravamen[\'FEC__FIN\'], format=\'%d/%m/%Y\', errors=\'coerce\')\ndf_desgravamen[\'MONEDA\'] = df_desgravamen[\'MONEDA\'].astype(str)\ndf_desgravamen[\'SUMA_ASEGURADA\']= pd.to_numeric(df_desgravamen[\'SUMA_ASEGURADA\'], errors=\'coerce\')\ndf_desgravamen[\'TASA\']= pd.to_numeric(df_desgravamen[\'TASA\'], errors=\'coerce\')\ndf_desgravamen[\'PRIMABRUTACAN\']= pd.to_numeric(df_desgravamen[\'PRIMABRUTACAN\'], errors=\'coerce\')\ndf_desgravamen[\'PRIMANETACAN\']= pd.to_numeric(df_desgravamen[\'PRIMANETACAN\'], errors=\'coerce\')\ndf_desgravamen[\'ORIGEN_ERROR\'] = df_desgravamen[\'ORIGEN_ERROR\'].fillna(0).astype(\'int\')\n'

In [69]:
#TIPO MOVIMIENTO
df_desgravamen['FECINI_ALTA_CERTIFICADO'].value_counts()  # Counting occurrences of each unique value in the 'TIPO MOVIMIENTO' column

FECINI_ALTA_CERTIFICADO
2019-09-30    480
2019-09-27    460
2019-09-16    432
2017-09-28    348
2021-07-21    344
             ...
2014-06-02      1
2013-11-14      1
2014-11-12      1
2014-09-11      1
2014-10-15      1
Name: count, Length: 2095, dtype: int64

In [38]:
df_desgravamen[df_desgravamen['FEC__INICIO'].isna()].head(3)

,NRO_LOTE,LOTES_ANTERIORES,FECHA_CARGA,CODIGO_PRODUCTO,PRODUCTO,CODIGO_PLAN,NOMBRE_DE_PLAN,COD_DE_CERTIFICADO,FECINI_ALTA_CERTIFICADO,FECFIN_ALTA_CERTIFICADO,IDEDET,TIPO_MOVIMIENTO,FEC__INICIO,FEC__FIN,MONEDA,SUMA_ASEGURADA,TASA,TASA_RECARGO,PRIMABRUTACAN,PRIMANETACAN,NOMCOMPLETO,APEPATERNO,APEMATERNO,FECNACIMIENTO,TIPDOCUMENTO,NUMDOCUMENTO,NOMBRE_DE_ARCHIVO,LINEA_TRAMA,ORIGEN_ERROR,CODIGO_ERROR,DESCRIPCION_ERROR
27604,70140,,2016-05-11 13:00:14,0,nan,0,nan,nan,NaT,NaT,132857441,Sin Movimiento,NaT,NaT,SIN DATO,0.0,0.0,0,0.0,0.0,nan,nan,nan,NaT,NaN,nan,20100130204_0157001_20160511_001.TXT,906001102755540002830710011027558960038589901P...,Error canal,983,"ERROR, Al ser tipo de titular mancomuno debe h..."
27632,73976,,2016-07-06 23:40:21,0,nan,0,nan,nan,NaT,NaT,141432028,Sin Movimiento,NaT,NaT,SOL,NaN,3.5,1503.5,NaN,0.0,MARIA MIRTHA,DEL CASTILLO,PEREZ,1955-01-29,2,980724,20100130204_0157001_20160706_003.TXT,901001102995840000970580011029950960003682801P...,Error canal,76,EL CAMPO Fecha Inicio Vigencia TIENE UN FORMAT...
27633,73976,,2016-07-06 23:40:21,0,nan,0,nan,nan,NaT,NaT,141432028,Sin Movimiento,NaT,NaT,SOL,NaN,3.5,1503.5,NaN,0.0,MARIA MIRTHA,DEL CASTILLO,PEREZ,1955-01-29,2,980724,20100130204_0157001_20160706_003.TXT,901001102995840000970580011029950960003682801P...,Error canal,76,EL CAMPO Fecha Fin Vigencia TIENE UN FORMATO Q...

In [70]:
#MONEDA
df_desgravamen['MONEDA'].value_counts()  # Counting occurrences of each unique value in the 'MONEDA' column

MONEDA
SOL    118616
USD       925
Name: count, dtype: int64

In [71]:
df_desgravamen['TIPO_MOVIMIENTO'].value_counts()

TIPO_MOVIMIENTO
Exclusion         119437
Sin Movimiento       104
Name: count, dtype: int64

In [72]:
df_desgravamen[df_desgravamen['TIPO_MOVIMIENTO'].isna()].head(3)

Empty DataFrame
Columns: [NRO_LOTE, LOTES_ANTERIORES, FECHA_CARGA, CODIGO_PRODUCTO, PRODUCTO, CODIGO_PLAN, NOMBRE_DE_PLAN, COD_DE_CERTIFICADO, FECINI_ALTA_CERTIFICADO, FECFIN_ALTA_CERTIFICADO, IDEDET, TIPO_MOVIMIENTO, FEC__INICIO, FEC__FIN, MONEDA, SUMA_ASEGURADA, TASA, TASA_RECARGO, PRIMABRUTACAN, PRIMANETACAN, NOMCOMPLETO, APEPATERNO, APEMATERNO, FECNACIMIENTO, TIPDOCUMENTO, NUMDOCUMENTO, NOMBRE_DE_ARCHIVO, LINEA_TRAMA, ORIGEN_ERROR, CODIGO_ERROR]
Index: []

In [32]:
df_desgravamen[df_desgravamen['MONEDA']=='SIN DATO'].head()

,NRO_LOTE,LOTES_ANTERIORES,FECHA_CARGA,CODIGO_PRODUCTO,PRODUCTO,CODIGO_PLAN,NOMBRE_DE_PLAN,COD_DE_CERTIFICADO,FECINI_ALTA_CERTIFICADO,FECFIN_ALTA_CERTIFICADO,IDEDET,TIPO_MOVIMIENTO,FEC__INICIO,FEC__FIN,MONEDA,SUMA_ASEGURADA,TASA,TASA_RECARGO,PRIMABRUTACAN,PRIMANETACAN,NOMCOMPLETO,APEPATERNO,APEMATERNO,FECNACIMIENTO,TIPDOCUMENTO,NUMDOCUMENTO,NOMBRE_DE_ARCHIVO,LINEA_TRAMA,ORIGEN_ERROR,CODIGO_ERROR,DESCRIPCION_ERROR
27604,70140,,2016-05-11 13:00:14,0,nan,0,nan,nan,NaT,NaT,132857441,Sin Movimiento,NaT,NaT,SIN DATO,0.0,0.0,0,0.0,0.0,nan,nan,nan,NaT,NaN,nan,20100130204_0157001_20160511_001.TXT,906001102755540002830710011027558960038589901P...,Error canal,983,"ERROR, Al ser tipo de titular mancomuno debe h..."
81303,130634,,2018-04-20 17:54:46,0,nan,0,nan,nan,NaT,NaT,230834148,Sin Movimiento,NaT,NaT,SIN DATO,0.0,0.0,0,0.0,0.0,nan,nan,nan,NaT,NaN,nan,20100130204_0157001_20180420_005.TXT,903001103357340001273260011033574960008761301P...,Error canal,983,"ERROR, Al ser tipo de titular mancomuno debe h..."
125160,285763,,2019-10-29 10:48:36,3827,Desgravamen + Desempleo BBVA,157903,PAN AMERICAN SILVER PERU TS BASE,0,NaT,NaT,335465001,Sin Movimiento,NaT,NaT,SIN DATO,0.0,0.0,0,0.0,0.0,nan,nan,nan,NaT,NaN,nan,20100130204_0157001_20191029_003.TXT,9030,Error canal,12,ERROR EN CAMPO: TIPO MOVIMIENTO DEL(A) DEFECTO...

In [95]:
def extraer_fecha(fecha):
    try:
        fecha_str = fecha.split("_")[2]
        return datetime.strptime(fecha_str, "%Y%m%d").date()
    except Exception:
        return None  # En caso de error

In [96]:
# Aplicar a la columna
df_desgravamen['FECHA_TRAMA'] = df_desgravamen['NOMBRE_DE_ARCHIVO'].apply(extraer_fecha)

In [75]:
df_desgravamen.head(2)

,NRO_LOTE,LOTES_ANTERIORES,FECHA_CARGA,CODIGO_PRODUCTO,PRODUCTO,CODIGO_PLAN,NOMBRE_DE_PLAN,COD_DE_CERTIFICADO,FECINI_ALTA_CERTIFICADO,FECFIN_ALTA_CERTIFICADO,IDEDET,TIPO_MOVIMIENTO,FEC__INICIO,FEC__FIN,MONEDA,SUMA_ASEGURADA,TASA,TASA_RECARGO,PRIMABRUTACAN,PRIMANETACAN,NOMCOMPLETO,APEPATERNO,APEMATERNO,FECNACIMIENTO,TIPDOCUMENTO,NUMDOCUMENTO,NOMBRE_DE_ARCHIVO,LINEA_TRAMA,ORIGEN_ERROR,CODIGO_ERROR,FECHA_TRAMA
0,872654,,2022-10-25 17:52:43,3827,Desgravamen + Desempleo BBVA,89705,Plan Contifacil,00110814174001203143,2019-12-30,2022-12-30,556035505,Exclusion,2019-12-30,2022-12-30,SOL,2800.0,0.35,0.35,0.98,0.95,NEISER,IPARRAGUIRRE,MU?OZ,NaT,2.0,44994753,20100130204_0157001_20201122_101.TXT,901001108141740012031430011081410960091807101P...,Error canal,0986,2020-11-22
1,872654,,2022-10-25 17:52:43,3827,Desgravamen + Desempleo BBVA,89705,Plan Contifacil,00110814174001203143,2019-12-30,2022-12-30,556035505,Exclusion,2019-12-30,2022-12-30,SOL,2800.0,0.35,0.35,0.98,0.95,NEISER,IPARRAGUIRRE,MU?OZ,NaT,2.0,44994753,20100130204_0157001_20201122_101.TXT,901001108141740012031430011081410960091807101P...,Error canal,2025,2020-11-22

In [78]:
df_desgravamen['FECHA_TRAMA'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 119541 entries, 0 to 119540
Series name: FECHA_TRAMA
Non-Null Count   Dtype
--------------   -----
119541 non-null  datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 934.0 KB

In [77]:
df_desgravamen['FECHA_TRAMA']= pd.to_datetime(df_desgravamen['FECHA_TRAMA'], errors='coerce')

In [79]:
def clasificar(row):
    # Si lote no esta vacio
    if str(row['LOTES_ANTERIORES']).strip() != "":
        return 'Regularizacion no Exitosa'
    
    # Si último número del nombre de archivo > 100
    try:
        ultimo_numero = int(row['NOMBRE_DE_ARCHIVO'].split("_")[-1][:-4])
        if ultimo_numero > 100:
            return 'Regularizacion no Exitosa'
    except:
        pass
    
    # Si ninguna condición se cumple
    return 'Mes corriente'

In [80]:
nombre = '20100130204_0157001_20150409_001_41924.TXT'
numero= int(nombre.split("_")[-1][:-4])
print(numero)

41924

In [81]:
#df_desgravamen['REGULARIZACION']= df_desgravamen['LOTES ANTERIORES'].notnull()
df_desgravamen['STATUS']= df_desgravamen.apply(clasificar, axis=1)

In [82]:
df_desgravamen['STATUS'].value_counts()

STATUS
Regularizacion no Exitosa    119541
Name: count, dtype: int64

In [83]:
df_desgravamen.head(10)

,NRO_LOTE,LOTES_ANTERIORES,FECHA_CARGA,CODIGO_PRODUCTO,PRODUCTO,CODIGO_PLAN,NOMBRE_DE_PLAN,COD_DE_CERTIFICADO,FECINI_ALTA_CERTIFICADO,FECFIN_ALTA_CERTIFICADO,IDEDET,TIPO_MOVIMIENTO,FEC__INICIO,FEC__FIN,MONEDA,SUMA_ASEGURADA,TASA,TASA_RECARGO,PRIMABRUTACAN,PRIMANETACAN,NOMCOMPLETO,APEPATERNO,APEMATERNO,FECNACIMIENTO,TIPDOCUMENTO,NUMDOCUMENTO,NOMBRE_DE_ARCHIVO,LINEA_TRAMA,ORIGEN_ERROR,CODIGO_ERROR,FECHA_TRAMA,STATUS
0,872654,,2022-10-25 17:52:43,3827,Desgravamen + Desempleo BBVA,89705,Plan Contifacil,00110814174001203143,2019-12-30,2022-12-30,556035505,Exclusion,2019-12-30,2022-12-30,SOL,2800.0,0.35,0.35,0.98,0.95,NEISER,IPARRAGUIRRE,MU?OZ,NaT,2.0,44994753,20100130204_0157001_20201122_101.TXT,901001108141740012031430011081410960091807101P...,Error canal,0986,2020-11-22,Regularizacion no Exitosa
1,872654,,2022-10-25 17:52:43,3827,Desgravamen + Desempleo BBVA,89705,Plan Contifacil,00110814174001203143,2019-12-30,2022-12-30,556035505,Exclusion,2019-12-30,2022-12-30,SOL,2800.0,0.35,0.35,0.98,0.95,NEISER,IPARRAGUIRRE,MU?OZ,NaT,2.0,44994753,20100130204_0157001_20201122_101.TXT,901001108141740012031430011081410960091807101P...,Error canal,2025,2020-11-22,Regularizacion no Exitosa
2,872654,,2022-10-25 17:52:43,3827,Desgravamen + Desempleo BBVA,89705,Plan Contifacil,00110814184000055299,2016-09-26,2020-09-28,556035940,Exclusion,2016-09-26,2020-09-28,SOL,6200.0,0.35,0.35,2.17,2.11,JAIRO LUIS,FEIJOO,DEL ROSARIO,NaT,2.0,41618166,20100130204_0157001_20201122_101.TXT,901001108141840000552990011081416960004645701P...,Error canal,0843,2020-11-22,Regularizacion no Exitosa
3,872654,,2022-10-25 17:52:43,3827,Desgravamen + Desempleo BBVA,89705,Plan Contifacil,00110814184000055299,2016-09-26,2020-09-28,556035941,Exclusion,2016-09-26,2020-09-28,SOL,6200.0,0.35,0.35,2.17,2.11,JAIRO LUIS,FEIJOO,DEL ROSARIO,NaT,2.0,41618166,20100130204_0157001_20201122_101.TXT,901001108141840000552990011081416960004645701P...,Error canal,0843,2020-11-22,Regularizacion no Exitosa
4,872654,,2022-10-25 17:52:43,3827,Desgravamen + Desempleo BBVA,89705,Plan Contifacil,00110814184000668703,2018-12-30,2022-12-30,556036160,Exclusion,2018-12-30,2022-12-30,SOL,9500.0,0.35,0.35,3.33,3.23,MARIELA,JIMENEZ,QUISPE,NaT,2.0,46058862,20100130204_0157001_20201122_101.TXT,901001108141840006687030011081417960044523801P...,Error canal,0986,2020-11-22,Regularizacion no Exitosa
5,872654,,2022-10-25 17:52:43,3827,Desgravamen + Desempleo BBVA,89705,Plan Contifacil,00110814184000668703,2018-12-30,2022-12-30,556036160,Exclusion,2018-12-30,2022-12-30,SOL,9500.0,0.35,0.35,3.33,3.23,MARIELA,JIMENEZ,QUISPE,NaT,2.0,46058862,20100130204_0157001_20201122_101.TXT,901001108141840006687030011081417960044523801P...,Error canal,2025,2020-11-22,Regularizacion no Exitosa
6,872654,,2022-10-25 17:52:43,3827,Desgravamen + Desempleo BBVA,89705,Plan Contifacil,00110814184000028178,2016-05-18,2020-05-20,556035928,Exclusion,2016-05-18,2020-05-20,SOL,11400.0,0.35,0.35,3.99,3.87,WALTER SULLIVAN,FELIPE,GASPAR,NaT,2.0,45797958,20100130204_0157001_20201122_101.TXT,901001108141840000281780011081419960002644801P...,Error canal,0843,2020-11-22,Regularizacion no Exitosa
7,872654,,2022-10-25 17:52:43,3827,Desgravamen + Desempleo BBVA,89705,Plan Contifacil,00110814184000028178,2016-05-18,2020-05-20,556035929,Exclusion,2016-05-18,2020-05-20,SOL,11400.0,0.35,0.35,3.99,3.87,WALTER SULLIVAN,FELIPE,GASPAR,NaT,2.0,45797958,20100130204_0157001_20201122_101.TXT,901001108141840000281780011081419960002644801P...,Error canal,0843,2020-11-22,Regularizacion no Exitosa
8,872654,,2022-10-25 17:52:43,3827,Desgravamen + Desempleo BBVA,89705,Plan Contifacil,00110814184000113930,2017-03-16,2020-03-16,556035961,Exclusion,2017-03-16,2020-03-16,SOL,1000.0,0.35,0.35,0.35,0.34,FRANK ALEX,SALOME,ARZAPALO,NaT,2.0,42709169,20100130204_0157001_20201122_101.TXT,901001108141840001139300011081412960009387001P...,Error canal,0843,2020-11-22,Regularizacion no Exitosa
9,872654,,2022-10-25 17:52:43,3827,Desgravamen + Desempleo BBVA,89705,Plan Contifacil,00110814184000113930,2017-03-16,2020-03-16,556035962,Exclusion,2017-03-16,2020-03-16,SOL,1000.0,0.35,0.35,0.35,0.34,FRANK ALEX,SALOME,ARZAPALO,NaT,2.0,42709169,20100130204_0157001_20201122_101.TXT,901001108141840001139300011081412960009387001P...,Error canal,0843,2020-11-22,Regularizacion no Exitosa

In [84]:
df_desgravamen[df_desgravamen['STATUS']=='Mes corriente'].head(6)

Empty DataFrame
Columns: [NRO_LOTE, LOTES_ANTERIORES, FECHA_CARGA, CODIGO_PRODUCTO, PRODUCTO, CODIGO_PLAN, NOMBRE_DE_PLAN, COD_DE_CERTIFICADO, FECINI_ALTA_CERTIFICADO, FECFIN_ALTA_CERTIFICADO, IDEDET, TIPO_MOVIMIENTO, FEC__INICIO, FEC__FIN, MONEDA, SUMA_ASEGURADA, TASA, TASA_RECARGO, PRIMABRUTACAN, PRIMANETACAN, NOMCOMPLETO, APEPATERNO, APEMATERNO, FECNACIMIENTO, TIPDOCUMENTO, NUMDOCUMENTO, NOMBRE_DE_ARCHIVO, LINEA_TRAMA, ORIGEN_ERROR, CODIGO_ERROR, FECHA_TRAMA, STATUS]
Index: []

In [85]:
df_errores['CODIGO_ERROR'].value_counts()

CODIGO_ERROR
1068    1
0003    1
1155    1
1150    1
1152    1
1116    1
0114    1
7578    1
0199    1
0011    1
2395    1
1137    1
0163    1
0177    1
1154    1
0155    1
1153    1
1157    1
0117    1
1151    1
9964    1
1608    1
0193    1
0039    1
0034    1
0050    1
0940    1
0035    1
1143    1
9963    1
1045    1
0010    1
9969    1
7460    1
9978    1
7440    1
0130    1
0757    1
0141    1
0317    1
0119    1
1140    1
0852    1
0061    1
1083    1
0022    1
0005    1
1195    1
1135    1
8023    1
1052    1
1136    1
Name: count, dtype: int64

In [56]:
df_errores[df_errores['CODIGO_ERROR'].isna()].head(10)

,CODIGO_ERROR,DESCRIPCION_ERROR,DETALLE,SOLUCION,SOLUCION_2
11,NaN,ERROR EN CARGA DE TRAMA,NI ÉXITO NI ERROR,ANALISIS EMISOR,NaN

In [57]:
df_errores[df_errores['CODIGO_ERROR'].isin({'2395','7440'})].head()

,CODIGO_ERROR,DESCRIPCION_ERROR,DETALLE,SOLUCION,SOLUCION_2
10,2395,ERROR DE TASA,TASA,ANALISIS EMISOR,CONFIGURACION SAS
36,7440,ERROR EDAD,EDAD - MANCOMUNO INEXISTENTE,CONFIGURACION SAS,REGLAS POR CAMBIAR

In [58]:
df_errores[df_errores['CODIGO_ERROR']==' '].head()

Empty DataFrame
Columns: [CODIGO_ERROR, DESCRIPCION_ERROR, DETALLE, SOLUCION, SOLUCION_2]
Index: []

In [59]:
df_desgravamen[df_desgravamen['CODIGO_ERROR'].isna()].head(10)

,NRO_LOTE,LOTES_ANTERIORES,FECHA_CARGA,CODIGO_PRODUCTO,PRODUCTO,CODIGO_PLAN,NOMBRE_DE_PLAN,COD_DE_CERTIFICADO,FECINI_ALTA_CERTIFICADO,FECFIN_ALTA_CERTIFICADO,IDEDET,TIPO_MOVIMIENTO,FEC__INICIO,FEC__FIN,MONEDA,SUMA_ASEGURADA,TASA,TASA_RECARGO,PRIMABRUTACAN,PRIMANETACAN,NOMCOMPLETO,APEPATERNO,APEMATERNO,FECNACIMIENTO,TIPDOCUMENTO,NUMDOCUMENTO,NOMBRE_DE_ARCHIVO,LINEA_TRAMA,ORIGEN_ERROR,CODIGO_ERROR,DESCRIPCION_ERROR,FECHA_TRAMA,STATUS
3713,43803,,2015-06-05,3070,Desgravamen BBVA,60083,Plan Contifacil,00110643424000045901,2014-08-11,2016-08-18,78905682,Exclusion,2014-08-11,2016-08-18,SOL,20000.0,0.35,0.35,7.00,6.80,FREDY ORLANDO,TIPIAN,MATTA,1967-05-27,2,21851276,20100130204_0157001_20150605_003.TXT,901001106434240000459010011064345960002888301P...,SIN DATO,NaN,nan,2015-06-05,Mes corriente
3714,43803,,2015-06-05,3070,Desgravamen BBVA,60083,Plan Contifacil,00110327444000227556,2014-09-02,2018-09-03,78904998,Exclusion,2014-09-02,2018-09-03,SOL,3988.0,0.51,0.51,2.03,1.97,HEDWAR,DELGADO,DEL AGUILA,1971-02-26,2,973227,20100130204_0157001_20150605_003.TXT,901001103274440002275560011032740960020627901P...,SIN DATO,NaN,nan,2015-06-05,Mes corriente
3715,43803,,2015-06-05,3070,Desgravamen BBVA,60083,Plan Contifacil,00110609564000013494,2014-05-26,2015-09-07,78905636,Exclusion,2014-05-26,2015-09-07,SOL,3000.0,0.51,0.51,1.53,1.49,CARLOS EBERT,CHAVEZ,LLERENA,1989-07-18,2,46265415,20100130204_0157001_20150605_003.TXT,901001106095640000134940011060952960000423701P...,SIN DATO,NaN,nan,2015-06-05,Mes corriente
3716,43803,,2015-06-05,3070,Desgravamen BBVA,60083,Plan Contifacil,00110831524000257714,2014-01-25,2017-01-30,78905995,Exclusion,2014-01-25,2017-01-30,SOL,70000.0,0.35,0.35,24.50,23.79,CARLOS,HOYOS,VERTIZ,1957-08-20,2,7787762,20100130204_0157001_20150605_003.TXT,901001108315240002577140011083154960016632301P...,SIN DATO,NaN,nan,2015-06-05,Mes corriente
3717,43803,,2015-06-05,3070,Desgravamen BBVA,60083,Plan Contifacil,00110716874000050235,2014-10-06,2017-10-30,78905738,Exclusion,2014-10-06,2017-10-30,SOL,12000.0,0.51,0.51,6.12,5.94,ANGEL EDUARDO FERNAN,LAMAS,NECIOSUP,1989-02-13,2,45547225,20100130204_0157001_20150605_003.TXT,901001107168740000502350011071681960002604601P...,SIN DATO,NaN,nan,2015-06-05,Mes corriente
3718,43803,,2015-06-05,3070,Desgravamen BBVA,60083,Plan Contifacil,00110249024000812242,2013-11-19,2015-05-04,78903828,Exclusion,2013-11-19,2015-05-04,SOL,5500.0,0.35,0.35,1.93,1.87,EUGENIO SANTIAGO,VALVERDE,LOZANO,1978-12-30,2,40365583,20100130204_0157001_20150605_003.TXT,901001102490240008122420011024904960071496301P...,SIN DATO,NaN,nan,2015-06-05,Mes corriente
3719,43803,,2015-06-05,3070,Desgravamen BBVA,60083,Plan Contifacil,00110323394000172679,2014-06-12,2015-06-22,78904953,Exclusion,2014-06-12,2015-06-22,SOL,5000.0,0.35,0.35,1.75,1.70,IVAN ROGER,ALFARO,REYES,1988-04-09,2,45426481,20100130204_0157001_20150605_003.TXT,901001103233940001726790011032332960010922001P...,SIN DATO,NaN,nan,2015-06-05,Mes corriente
3720,43803,,2015-06-05,3070,Desgravamen BBVA,60083,Plan Contifacil,00110165814000068342,2014-06-23,2017-06-26,78902507,Exclusion,2014-06-23,2017-06-26,SOL,20800.0,0.35,0.35,7.28,7.07,MANUEL ALBERTO,CARAMUTTI,GAMARRA,1988-09-04,2,45451322,20100130204_0157001_20150605_003.TXT,901001101658140000683420011016584960008889601P...,SIN DATO,NaN,nan,2015-06-05,Mes corriente
3721,43803,,2015-06-05,3070,Desgravamen BBVA,60083,Plan Contifacil,00110195574000397854,2014-04-25,2015-10-26,78902844,Exclusion,2014-04-25,2015-10-26,SOL,1500.0,0.35,0.35,0.53,0.51,JORGE VICTOR,ROMERO,ESLAVA,1954-11-02,2,43297740,20100130204_0157001_20150605_003.TXT,901001101955740003978540011019554960013940001P...,SIN DATO,NaN,nan,2015-06-05,Mes corriente
3722,43803,,2015-06-05,3070,Desgravamen BBVA,60083,Plan Contifacil,00110232614000214881,2013-10-30,2016-10-31,78903464,Exclusion,2013-10-30,2016-10-31,SOL,30850.0,0.65,0.65,20.05,19.47,VICTOR AURELIO,GAMARRA,VALDIVIA,1951-04-15,2,4411913,20100130204_0157001_20150605_003.TXT,901001102326140002148810011023267960032666901P...,SIN DATO,NaN,nan,2015-06-05,Mes corriente

In [188]:
df_desgravamen[df_desgravamen['CODIGO_ERROR']==''].head()

Empty DataFrame
Columns: [CODIGO_PRODUCTO, LOTES_ANTERIORES, COD_DE_CERTIFICADO, FECINI_ALTA_CERTIFICADO, FECFIN_ALTA_CERTIFICADO, IDEDET, TRAMA, TIPO_MOVIMIENTO, FEC__INICIO, FEC__FIN, MONEDA, SUMA_ASEGURADA, TASA, PRIMABRUTACAN, PRIMANETACAN, NOMBRE_DE_ARCHIVO, ORIGEN_ERROR, TIPO_ERROR, CODIGO_ERROR, FECHA_TRAMA, STATUS]
Index: []

[0 rows x 21 columns]

In [60]:
df_errores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53 entries, 0 to 52
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CODIGO_ERROR       52 non-null     object
 1   DESCRIPCION_ERROR  53 non-null     object
 2   DETALLE            53 non-null     object
 3   SOLUCION           53 non-null     object
 4   SOLUCION_2         19 non-null     object
dtypes: object(5)
memory usage: 2.2+ KB

In [86]:
df= df_desgravamen.merge(df_errores, on='CODIGO_ERROR', how='left')

In [90]:
df['DESCRIPCION_ERROR'].value_counts()

DESCRIPCION_ERROR
CAMPOS EN BLANCO              253
PAGO PENDIENTE DE CORREGIR     18
Name: count, dtype: int64

In [92]:
df['CODIGO_ERROR'].value_counts()

CODIGO_ERROR
1106    115762
0970      1400
0843       853
0986       327
2025       313
0014       235
0035       233
1201       134
0983       104
0101        91
1092        48
1135        20
1143        18
1200         2
1215         1
Name: count, dtype: int64

In [88]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119541 entries, 0 to 119540
Data columns (total 36 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   NRO_LOTE                 119541 non-null  int64
 1   LOTES_ANTERIORES         119541 non-null  object
 2   FECHA_CARGA              119541 non-null  datetime64[ns]
 3   CODIGO_PRODUCTO          119541 non-null  int64
 4   PRODUCTO                 119541 non-null  object
 5   CODIGO_PLAN              119541 non-null  int64
 6   NOMBRE_DE_PLAN           119541 non-null  object
 7   COD_DE_CERTIFICADO       119541 non-null  object
 8   FECINI_ALTA_CERTIFICADO  117979 non-null  datetime64[ns]
 9   FECFIN_ALTA_CERTIFICADO  117979 non-null  datetime64[ns]
 10  IDEDET                   119541 non-null  int64
 11  TIPO_MOVIMIENTO          119541 non-null  object
 12  FEC__INICIO              118964 non-null  datetime64[ns]
 13  FEC__FIN                 118964 non-null  datetime64[ns]
 14  MONEDA                   119541 non-null  object
 15  SUMA_ASEGURADA           119541 non-null  float64
 16  TASA                     119541 non-null  float64
 17  TASA_RECARGO             119541 non-null  float64
 18  PRIMABRUTACAN            119541 non-null  float64
 19  PRIMANETACAN             119541 non-null  float64
 20  NOMCOMPLETO              119541 non-null  object
 21  APEPATERNO               119541 non-null  object
 22  APEMATERNO               119541 non-null  object
 23  FECNACIMIENTO            0 non-null       datetime64[ns]
 24  TIPDOCUMENTO             119541 non-null  object
 25  NUMDOCUMENTO             119541 non-null  object
 26  NOMBRE_DE_ARCHIVO        119541 non-null  object
 27  LINEA_TRAMA              119541 non-null  object
 28  ORIGEN_ERROR             119541 non-null  object
 29  CODIGO_ERROR             119541 non-null  object
 30  FECHA_TRAMA              119541 non-null  datetime64[ns]
 31  STATUS                   119541 non-null  object
 32  DESCRIPCION_ERROR        271 non-null     object
 33  DETALLE                  271 non-null     object
 34  SOLUCION                 271 non-null     object
 35  SOLUCION_2               0 non-null       object
dtypes: datetime64[ns](7), float64(5), int64(4), object(20)
memory usage: 32.8+ MB