In [1]:
import pandas as pd
from datetime import datetime
import warnings
warnings.filterwarnings("ignore", category=UserWarning, module="openpyxl")
import unicodedata
import os
pd.set_option('display.max_columns', None)

In [35]:
espacios_col = [(0, 3), (3, 23), (23, 43), (43,45), (45, 48), (48, 49), (49, 79), (79, 109), (109, 139),   
                (139, 140), (140, 141), (141, 149), (149, 150), (150, 160), (160, 210), (210, 235),   
                (235, 260), (260, 290), (290, 298), (298, 306), (306, 336), (336, 338), (338, 343),   
                (343, 346), (346, 347), (347, 350), (350, 353), (353, 355), (355, 358), (358, 361), 
                (361, 368), (368, 376), (376, 384), (384, 392), (392, 396), (396, 411), (411, 426),   
                (426, 427), (427, 429), (429, 430), (430, 431), (431, 432), (432, 442), (442, 449),   
                (449, 522), (522, 524), (524, 527), (527, 530), (530, 540), (540, 550), (550,565),
                (565, 635), (635, 637), (637, 639), (639,641)]

column_names = ["Tipo de seguro", "Certificado", "Numero Interno Del Canal", "Tipo de Registro", "Moneda", 
                "Tipo de Movimiento", "Apellido Paterno", "Apellido Materno", "Nombres", "Sexo", "Estado Civil", 
                "Fecha de Nacimiento", "Tipo de Documento de Identidad", "Numero de Documento de Identidad", 
                "Dirección Domiciliaria", "Referencia", "Referencia2", "Urbanización", "Mz/Lte/Nro", "Apto/Int", 
                "Distrito", "Departamento", "Código Postal", "País", "Periodo de pago", "Prefijo Calle,Av,Jr", 
                "Prefijo 2", "Provincia", "Distrito2", "Prefijo Teléfono", "Numero Teléfono", "Fecha de Afiliación", 
                "Fecha de inicio del seguro", "Fecha fin del seguro", "Plazo del seguro", "Monto Asegurado", "Prima", 
                "Período de Gracia", "Código de Beneficiario", "Clase de Prima", "Tipo de Titular", "Mayor a 65 Años", 
                "Tasa sin Recargo", "% de recargo", "Filler", "Tiempo de Periodo de Gracia", "Tipos de Endoso", 
                "Tipos de Extorno", "Tipo de cambio", "Póliza", "Sumatoria de Capital en Cúmulo", "Correo electrónico", 
                "Plan de crédito", "Planes Tipo Desgravamen", "Planes de Seguro (o Modalidad)"
                ]

In [36]:
df_declarado= pd.read_csv('c:/data/declarado TC - enero.csv', sep=',', encoding='latin1', low_memory=False)
df_declarado.head(3)

,trama_original,nombre_archivo_trama,fecha_recepcion
0,918001102292640007816150011022925500195859001P...,RED210125_2201.TXT,2025-01-22
1,918001104082240023821170011040822500720582101P...,RED210125_2201.TXT,2025-01-22
2,918001104868840010438370011050488500114601901P...,RED210125_2201.TXT,2025-01-22

In [37]:

df_declarado['trama_original'].to_csv('solo_tramas.txt', index=False, header=False)

In [38]:
df_declarado = pd.read_fwf('c:/data/solo_tramas.txt', colspecs=espacios_col, names=column_names, encoding='latin1')

In [39]:
df_declarado.head(3)

,Tipo de seguro,Certificado,Numero Interno Del Canal,Tipo de Registro,Moneda,Tipo de Movimiento,Apellido Paterno,Apellido Materno,Nombres,Sexo,Estado Civil,Fecha de Nacimiento,Tipo de Documento de Identidad,Numero de Documento de Identidad,Dirección Domiciliaria,Referencia,Referencia2,Urbanización,Mz/Lte/Nro,Apto/Int,Distrito,Departamento,Código Postal,País,Periodo de pago,"Prefijo Calle,Av,Jr",Prefijo 2,Provincia,Distrito2,Prefijo Teléfono,Numero Teléfono,Fecha de Afiliación,Fecha de inicio del seguro,Fecha fin del seguro,Plazo del seguro,Monto Asegurado,Prima,Período de Gracia,Código de Beneficiario,Clase de Prima,Tipo de Titular,Mayor a 65 Años,Tasa sin Recargo,% de recargo,Filler,Tiempo de Periodo de Gracia,Tipos de Endoso,Tipos de Extorno,Tipo de cambio,Póliza,Sumatoria de Capital en Cúmulo,Correo electrónico,Plan de crédito,Planes Tipo Desgravamen,Planes de Seguro (o Modalidad)
0,918,00110229264000781615,00110229255001958590,1,PEN,4,QUISPE,MOROCO,PATTY LUZMILA,F,S,19940109,L,70290597,NO APLICA,NaN,NaN,NO APLICA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94,0235160,20250121.0,20241220.0,20250120.0,099I,00000000025495F,00000000000086G,NaN,06,I,1,NaN,0003400000,0.0,00000000000000{00000000000086G491914,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
1,918,00110408224002382117,00110408225007205821,1,PEN,4,NORIEGA,MENDOZA,CARLOS ALBERTO,M,S,19650813,L,08457015,NO APLICA,NaN,NaN,NO APLICA,NaN,NaN,NaN,NaN,NaN,PER,NaN,NaN,NaN,NaN,NaN,99,7664576,20250121.0,20241220.0,20250120.0,099I,00000000029354C,00000000000099H,NaN,06,I,1,NaN,0003400000,0.0,00000000000000{00000000000099H491909,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
2,918,00110486884001043837,00110504885001146019,1,PEN,4,URQUIZO,LIMAY,ANTHONY RAFAEL,M,S,19920322,L,46902067,NO APLICA,NaN,NaN,NO APLICA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,91,0752024,20250121.0,20241220.0,20250120.0,099I,00000000073418C,00000000000200{,NaN,06,I,1,NaN,0003400000,0.0,00000000000000{00000000000200{414791,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0

In [40]:
df_declarado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 672945 entries, 0 to 672944
Data columns (total 55 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   Tipo de seguro                    672945 non-null  object
 1   Certificado                       672945 non-null  object
 2   Numero Interno Del Canal          672945 non-null  object
 3   Tipo de Registro                  672945 non-null  int64
 4   Moneda                            672945 non-null  object
 5   Tipo de Movimiento                672945 non-null  object
 6   Apellido Paterno                  672945 non-null  object
 7   Apellido Materno                  672945 non-null  object
 8   Nombres                           672945 non-null  object
 9   Sexo                              663263 non-null  object
 10  Estado Civil                      672936 non-null  object
 11  Fecha de Nacimiento               672945 non-null  object
 12  Tipo de Documento de Identidad    672945 non-null  object
 13  Numero de Documento de Identidad  672945 non-null  object
 14  Dirección Domiciliaria            672292 non-null  object
 15  Referencia                        577161 non-null  object
 16  Referencia2                       87931 non-null   object
 17  Urbanización                      664995 non-null  object
 18  Mz/Lte/Nro                        670695 non-null  object
 19  Apto/Int                          373819 non-null  object
 20  Distrito                          670174 non-null  object
 21  Departamento                      669449 non-null  object
 22  Código Postal                     428668 non-null  object
 23  País                              670269 non-null  object
 24  Periodo de pago                   11104 non-null   object
 25  Prefijo Calle,Av,Jr               637064 non-null  object
 26  Prefijo 2                         369573 non-null  object
 27  Provincia                         670365 non-null  object
 28  Distrito2                         670958 non-null  object
 29  Prefijo Teléfono                  667418 non-null  object
 30  Numero Teléfono                   667295 non-null  object
 31  Fecha de Afiliación               672944 non-null  float64
 32  Fecha de inicio del seguro        672944 non-null  float64
 33  Fecha fin del seguro              672944 non-null  float64
 34  Plazo del seguro                  672944 non-null  object
 35  Monto Asegurado                   672944 non-null  object
 36  Prima                             672944 non-null  object
 37  Período de Gracia                 11139 non-null   object
 38  Código de Beneficiario            672944 non-null  object
 39  Clase de Prima                    671551 non-null  object
 40  Tipo de Titular                   672930 non-null  object
 41  Mayor a 65 Años                   11137 non-null   object
 42  Tasa sin Recargo                  672944 non-null  object
 43  % de recargo                      672944 non-null  float64
 44  Filler                            672944 non-null  object
 45  Tiempo de Periodo de Gracia       0 non-null       float64
 46  Tipos de Endoso                   0 non-null       float64
 47  Tipos de Extorno                  0 non-null       float64
 48  Tipo de cambio                    0 non-null       float64
 49  Póliza                            0 non-null       float64
 50  Sumatoria de Capital en Cúmulo    372287 non-null  object
 51  Correo electrónico                374401 non-null  object
 52  Plan de crédito                   374399 non-null  float64
 53  Planes Tipo Desgravamen           374399 non-null  float64
 54  Planes de Seguro (o Modalidad)    672278 non-null  float64
dtypes: float64(12), int64(1), object(42)
memory usage: 282.4+ MB

In [41]:
df_emitido= pd.read_csv('c:/data/emision TC - enero.csv', sep=',', skiprows=7, encoding='latin1', low_memory=False)
df_emitido.head(3)

,NRO LOTE,NRO LOTES ANTERIORES,FECHA CARGA LOTE,CÓDIGO PRODUCTO,PRODUCTO,PLAN,NOMBRE DE PLAN,CÓD. CERTIFICADO CANAL,TIPO MOVIMIENTO,NOMBRE,APELLIDO PATERNO,APELLIDO MATERNO,FECHA NACIMIENTO,TIPO DOC. ID,DOC. ID.,FEC. INICIO,FEC. FIN,MONEDA,SUMA ASEGURADA,TASA,TASA CON RECARGO,PRIMABRUTACAN,PRIMANETACAN,PLACA,MOTOR,NOMBRE ARCHIVO,LÍNEA DE TRAMA,LINEA TRAMA(TEXTO COMPLETO),ESTADO,DESCRIPCIÓN DE ESTADO,CÓDIGO DE RAMO,CÓDIGO DE PRODUCTO EN CORE,MONEDA.1,PRIMA NETA,DERECHO DE EMISIÓN,IGV,INTERES FINANCIAMIENTO,IGV INTERES_FINANCIAMIENTO,OTROS CONCEPTOS,PRIMA BRUTA,COMISION,NUMERO CERTIFICADO RIMAC,NUMERO DE POLIZA,TIPO DOC EMISIÓN,N. DOC EMISIÓN,FECHA DE EMISIÓN,CONTRATANTE,RESPONSABLE DE PAGO,ESTADO DE DOCUMENTO,IDEREGISTRO,NUMERO DE POLIZA AE,FEC. INICIO AE,FEC. FIN AE,PRIMA BRUTA AE,MONTO COMISIÓN CANAL,FEC. INICIO AX,FEC. FIN AX,PRIMA BRUTA AX,TIPO DOC EMISIÓN ORIGEN,N. DOC EMISIÓN ORIGEN
0,1189525,NaN,04/07/2024 22:47,4046,Desgravamen BBVA - T. Credito + Desempleo,378370,Plan Premier Saldo insoluto soles,C00110087404000562300,Renovacion,CARMEN DE YANIRA,ZAPATA,RUIZ,20/02/1996,2,75517988,10/05/2024,10/06/2024,SOL,66.77,0.256,0.256,0.17,0.17,NaN,NaN,20100130204_0158001_20240701_002.TXT,10367,918001100874040005623000011050489500552331301P...,Terminado,Emitido en A/X,VTHD,158.0,SOL,0.17,0.00,0.0,0.0,0.0,0.0,0.17,0.0,'15801867037-1,'8793500001,LQ,1.671789e+09,23-JAN-25,BANCO BBVA PERU,CARMEN DE YANIRA ZAPATA RUIZ,COB,691738528,8793500001,09/05/2024,19/02/2095,0.17,0.12,NaN,NaN,NaN,NaN,NaN
1,1189525,NaN,04/07/2024 22:47,4046,Desgravamen BBVA - T. Credito + Desempleo,378370,Plan Premier Saldo insoluto soles,C00110087464000562769,Renovacion,ADRIAN ALEXANDER,AYMA,COHAILA,19/01/2000,2,70942251,13/05/2024,10/06/2024,SOL,968.97,0.256,0.256,2.48,2.41,NaN,NaN,20100130204_0158001_20240701_002.TXT,10369,918001100874640005627690011008741500043689101P...,Terminado,Emitido en A/X,VTHD,158.0,SOL,2.41,0.07,0.0,0.0,0.0,0.0,2.48,0.0,'15801856891-1,'8793500001,LQ,1.671789e+09,23-JAN-25,BANCO BBVA PERU,ADRIAN ALEXANDER AYMA COHAILA,COB,691738896,8793500001,13/05/2024,18/01/2099,2.48,1.79,NaN,NaN,NaN,NaN,NaN
2,1189525,NaN,04/07/2024 22:47,4046,Desgravamen BBVA - T. Credito + Desempleo,378370,Plan Premier Saldo insoluto soles,C00110087494000560405,Renovacion,RONNY MARTIN,GARCES,ZAPATA,26/08/1987,2,44661012,10/05/2024,10/06/2024,SOL,877.42,0.256,0.256,2.25,2.18,NaN,NaN,20100130204_0158001_20240701_002.TXT,10360,918001100874940005604050011008740500043503801P...,Terminado,Emitido en A/X,VTHD,158.0,SOL,2.18,0.07,0.0,0.0,0.0,0.0,2.25,0.0,'15801867484-1,'8793500001,LQ,1.671788e+09,23-JAN-25,BANCO BBVA PERU,RONNY MARTIN GARCES ZAPATA,COB,691739066,8793500001,24/04/2024,25/08/2086,2.25,1.62,NaN,NaN,NaN,NaN,NaN

In [42]:
df_emitido['Certificado'] = df_emitido['CÓD. CERTIFICADO CANAL'].str[1:]
df_emitido= df_emitido[['Certificado','NRO LOTE']]

In [43]:
df_emitido.head(3)

            Certificado  NRO LOTE
0  00110087404000562300   1189525
1  00110087464000562769   1189525
2  00110087494000560405   1189525

In [44]:
df_cruce= pd.merge(df_declarado, df_emitido, how='left', on='Certificado')

In [45]:
df_cruce.head(3)

,Tipo de seguro,Certificado,Numero Interno Del Canal,Tipo de Registro,Moneda,Tipo de Movimiento,Apellido Paterno,Apellido Materno,Nombres,Sexo,Estado Civil,Fecha de Nacimiento,Tipo de Documento de Identidad,Numero de Documento de Identidad,Dirección Domiciliaria,Referencia,Referencia2,Urbanización,Mz/Lte/Nro,Apto/Int,Distrito,Departamento,Código Postal,País,Periodo de pago,"Prefijo Calle,Av,Jr",Prefijo 2,Provincia,Distrito2,Prefijo Teléfono,Numero Teléfono,Fecha de Afiliación,Fecha de inicio del seguro,Fecha fin del seguro,Plazo del seguro,Monto Asegurado,Prima,Período de Gracia,Código de Beneficiario,Clase de Prima,Tipo de Titular,Mayor a 65 Años,Tasa sin Recargo,% de recargo,Filler,Tiempo de Periodo de Gracia,Tipos de Endoso,Tipos de Extorno,Tipo de cambio,Póliza,Sumatoria de Capital en Cúmulo,Correo electrónico,Plan de crédito,Planes Tipo Desgravamen,Planes de Seguro (o Modalidad),NRO LOTE
0,918,00110229264000781615,00110229255001958590,1,PEN,4,QUISPE,MOROCO,PATTY LUZMILA,F,S,19940109,L,70290597,NO APLICA,NaN,NaN,NO APLICA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94,0235160,20250121.0,20241220.0,20250120.0,099I,00000000025495F,00000000000086G,NaN,06,I,1,NaN,0003400000,0.0,00000000000000{00000000000086G491914,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1276265.0
1,918,00110408224002382117,00110408225007205821,1,PEN,4,NORIEGA,MENDOZA,CARLOS ALBERTO,M,S,19650813,L,08457015,NO APLICA,NaN,NaN,NO APLICA,NaN,NaN,NaN,NaN,NaN,PER,NaN,NaN,NaN,NaN,NaN,99,7664576,20250121.0,20241220.0,20250120.0,099I,00000000029354C,00000000000099H,NaN,06,I,1,NaN,0003400000,0.0,00000000000000{00000000000099H491909,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1276264.0
2,918,00110486884001043837,00110504885001146019,1,PEN,4,URQUIZO,LIMAY,ANTHONY RAFAEL,M,S,19920322,L,46902067,NO APLICA,NaN,NaN,NO APLICA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,91,0752024,20250121.0,20241220.0,20250120.0,099I,00000000073418C,00000000000200{,NaN,06,I,1,NaN,0003400000,0.0,00000000000000{00000000000200{414791,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1276187.0

In [46]:
df_cruce['Certificado'].value_counts()

Certificado
00110133624000424586    2
00110106204000374441    2
00110053634000240308    2
00110408264004490839    1
00110908144000209939    1
                       ..
00110321724001789962    1
00110486844001964827    1
00110908124000215521    1
00110908104000195326    1
00110220104001551975    1
Name: count, Length: 672945, dtype: int64

In [47]:
df_cruce['NRO LOTE'].isna().value_counts()

NRO LOTE
False    578029
True      94919
Name: count, dtype: int64

In [48]:
df_cruce['EMITIDO'] = df_cruce['NRO LOTE'].notnull()

In [30]:
df_cruce['EMITIDO'].value_counts()

EMITIDO
True     578029
False     94919
Name: count, dtype: int64

In [49]:
df_cruce.head(3)

,Tipo de seguro,Certificado,Numero Interno Del Canal,Tipo de Registro,Moneda,Tipo de Movimiento,Apellido Paterno,Apellido Materno,Nombres,Sexo,Estado Civil,Fecha de Nacimiento,Tipo de Documento de Identidad,Numero de Documento de Identidad,Dirección Domiciliaria,Referencia,Referencia2,Urbanización,Mz/Lte/Nro,Apto/Int,Distrito,Departamento,Código Postal,País,Periodo de pago,"Prefijo Calle,Av,Jr",Prefijo 2,Provincia,Distrito2,Prefijo Teléfono,Numero Teléfono,Fecha de Afiliación,Fecha de inicio del seguro,Fecha fin del seguro,Plazo del seguro,Monto Asegurado,Prima,Período de Gracia,Código de Beneficiario,Clase de Prima,Tipo de Titular,Mayor a 65 Años,Tasa sin Recargo,% de recargo,Filler,Tiempo de Periodo de Gracia,Tipos de Endoso,Tipos de Extorno,Tipo de cambio,Póliza,Sumatoria de Capital en Cúmulo,Correo electrónico,Plan de crédito,Planes Tipo Desgravamen,Planes de Seguro (o Modalidad),NRO LOTE,EMITIDO
0,918,00110229264000781615,00110229255001958590,1,PEN,4,QUISPE,MOROCO,PATTY LUZMILA,F,S,19940109,L,70290597,NO APLICA,NaN,NaN,NO APLICA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94,0235160,20250121.0,20241220.0,20250120.0,099I,00000000025495F,00000000000086G,NaN,06,I,1,NaN,0003400000,0.0,00000000000000{00000000000086G491914,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1276265.0,True
1,918,00110408224002382117,00110408225007205821,1,PEN,4,NORIEGA,MENDOZA,CARLOS ALBERTO,M,S,19650813,L,08457015,NO APLICA,NaN,NaN,NO APLICA,NaN,NaN,NaN,NaN,NaN,PER,NaN,NaN,NaN,NaN,NaN,99,7664576,20250121.0,20241220.0,20250120.0,099I,00000000029354C,00000000000099H,NaN,06,I,1,NaN,0003400000,0.0,00000000000000{00000000000099H491909,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1276264.0,True
2,918,00110486884001043837,00110504885001146019,1,PEN,4,URQUIZO,LIMAY,ANTHONY RAFAEL,M,S,19920322,L,46902067,NO APLICA,NaN,NaN,NO APLICA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,91,0752024,20250121.0,20241220.0,20250120.0,099I,00000000073418C,00000000000200{,NaN,06,I,1,NaN,0003400000,0.0,00000000000000{00000000000200{414791,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1276187.0,True

In [50]:
df_cruce.drop('NRO LOTE', axis=1, inplace=True)

In [51]:
df_cruce.head(3)

,Tipo de seguro,Certificado,Numero Interno Del Canal,Tipo de Registro,Moneda,Tipo de Movimiento,Apellido Paterno,Apellido Materno,Nombres,Sexo,Estado Civil,Fecha de Nacimiento,Tipo de Documento de Identidad,Numero de Documento de Identidad,Dirección Domiciliaria,Referencia,Referencia2,Urbanización,Mz/Lte/Nro,Apto/Int,Distrito,Departamento,Código Postal,País,Periodo de pago,"Prefijo Calle,Av,Jr",Prefijo 2,Provincia,Distrito2,Prefijo Teléfono,Numero Teléfono,Fecha de Afiliación,Fecha de inicio del seguro,Fecha fin del seguro,Plazo del seguro,Monto Asegurado,Prima,Período de Gracia,Código de Beneficiario,Clase de Prima,Tipo de Titular,Mayor a 65 Años,Tasa sin Recargo,% de recargo,Filler,Tiempo de Periodo de Gracia,Tipos de Endoso,Tipos de Extorno,Tipo de cambio,Póliza,Sumatoria de Capital en Cúmulo,Correo electrónico,Plan de crédito,Planes Tipo Desgravamen,Planes de Seguro (o Modalidad),EMITIDO
0,918,00110229264000781615,00110229255001958590,1,PEN,4,QUISPE,MOROCO,PATTY LUZMILA,F,S,19940109,L,70290597,NO APLICA,NaN,NaN,NO APLICA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94,0235160,20250121.0,20241220.0,20250120.0,099I,00000000025495F,00000000000086G,NaN,06,I,1,NaN,0003400000,0.0,00000000000000{00000000000086G491914,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,True
1,918,00110408224002382117,00110408225007205821,1,PEN,4,NORIEGA,MENDOZA,CARLOS ALBERTO,M,S,19650813,L,08457015,NO APLICA,NaN,NaN,NO APLICA,NaN,NaN,NaN,NaN,NaN,PER,NaN,NaN,NaN,NaN,NaN,99,7664576,20250121.0,20241220.0,20250120.0,099I,00000000029354C,00000000000099H,NaN,06,I,1,NaN,0003400000,0.0,00000000000000{00000000000099H491909,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,True
2,918,00110486884001043837,00110504885001146019,1,PEN,4,URQUIZO,LIMAY,ANTHONY RAFAEL,M,S,19920322,L,46902067,NO APLICA,NaN,NaN,NO APLICA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,91,0752024,20250121.0,20241220.0,20250120.0,099I,00000000073418C,00000000000200{,NaN,06,I,1,NaN,0003400000,0.0,00000000000000{00000000000200{414791,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,True

In [80]:
df_cruce[df_cruce['EMITIDO']==False].head()

,Tipo de seguro,Certificado,Numero Interno Del Canal,Tipo de Registro,Moneda,Tipo de Movimiento,Apellido Paterno,Apellido Materno,Nombres,Sexo,Estado Civil,Fecha de Nacimiento,Tipo de Documento de Identidad,Numero de Documento de Identidad,Dirección Domiciliaria,Referencia,Referencia2,Urbanización,Mz/Lte/Nro,Apto/Int,Distrito,Departamento,Código Postal,País,Periodo de pago,"Prefijo Calle,Av,Jr",Prefijo 2,Provincia,Distrito2,Prefijo Teléfono,Numero Teléfono,Fecha de Afiliación,Fecha de inicio del seguro,Fecha fin del seguro,Plazo del seguro,Monto Asegurado,Prima,Período de Gracia,Código de Beneficiario,Clase de Prima,Tipo de Titular,Mayor a 65 Años,Tasa sin Recargo,% de recargo,Filler,Tiempo de Periodo de Gracia,Tipos de Endoso,Tipos de Extorno,Tipo de cambio,Póliza,Sumatoria de Capital en Cúmulo,Correo electrónico,Plan de crédito,Planes Tipo Desgravamen,Planes de Seguro (o Modalidad),EMITIDO
9,918,00110408274001208598,00110408295005995930,1,PEN,4,AGUILAR,MAMANI,CHRISTIAN ANDREW,M,S,19871110,L,45376835,LA CULTURA .,-,DAD DE LOS ANDES,NO APLICA,102,NaN,ABANCAY,05,NaN,PER,NaN,AV.,NaN,01,001,98,3761229,20250121.0,20241220.0,20250120.0,099I,00000000000470D,00000000000001F,NaN,06,I,1,NaN,0003400000,0.0,00000000000000{00000000000001F491914,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,False
56,918,00110408254001334828,00110408265006125611,1,PEN,4,AYALA,MAMANI,JOSE ALFREDO,M,S,19890218,L,45552051,INDEPENDENCIA ZONA B .,CERCA A LA AV ARENAL,NaN,NO APLICA,MZ 26,LT 4,ALTO SELVA ALEGRE,06,NaN,PER,NaN,PSJ,NaN,01,001,91,3301832,20250121.0,20241220.0,20250120.0,099I,00000000067634F,00000000000200{,NaN,06,I,1,NaN,0003400000,0.0,00000000000000{00000000000200{414791,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,False
123,918,00110827394000855474,00110827375000751373,1,PEN,4,ALBORNOZ,JUAN DE DIOS,DELIA SANDY,F,S,19921002,R,1047601222,LOS EUCALIPTOS LOS PORTALES,VIVIENDA DE 4 PISOS,NaN,NO APLICA,MZ F,LOTE 25,AMARILIS,11,NaN,PER,NaN,CAL,NaN,01,007,90,1633958,20250121.0,20241220.0,20250120.0,099I,00000000004172A,00000000000014B,NaN,06,I,1,NaN,0003400000,0.0,00000000000000{00000000000014B491931,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,False
153,918,00110408204005250483,00110408295010807255,1,PEN,4,MITMA,ESPINOZA,DEISY,F,S,19861127,L,44639023,TEOFILO MENACHO,PLAZA DE ARMAS,NaN,NO APLICA,360,SN,ANDAHUAYLAS,05,NaN,PER,NaN,JR.,NaN,02,001,98,3989814,20250121.0,20241220.0,20250120.0,099I,00000000000257G,00000000000000I,NaN,06,I,1,NaN,0003400000,0.0,00000000000000{00000000000000I404293,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,False
171,918,00110220144001250843,00110220195003040850,1,PEN,4,SANCHEZ,SENCIA,OSMAR,M,S,19910122,R,1046815388,ASOC JAVIER HERAUD,PARQUE,NaN,JAVIER HERAUD,MZ J,LT 7,AREQUIPA,06,NaN,PER,NaN,AV.,URB,01,002,98,2000563,20250121.0,20241220.0,20250120.0,099I,00000000001162A,00000000000004{,NaN,06,I,1,NaN,0003400000,0.0,00000000000000{00000000000004{404293,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,False

In [82]:
df_emitido[df_emitido['Certificado']== '00110827394000855474'].head()

Empty DataFrame
Columns: [Certificado, NRO LOTE]
Index: []

In [53]:
df_cruce.to_csv('c:/data/cruce_TC_Enero.csv', index=False, encoding='latin1')

###############################################################################################

In [63]:
df_desgravamen= pd.read_excel('C:/data/01. ENERO - LIQUIDACIONES - TC.xlsx', sheet_name=None)

In [65]:
print(df_desgravamen.keys())

dict_keys(['Hoja2', 'Hoja1'])

In [68]:
df_liquidaciones= df_desgravamen['Hoja1'].copy()

In [69]:
df_liquidaciones.head()

,Desc Canal,Cod Prod,Producto,TipoDoc,NumDoc,Monto,Moneda,Fecha Emisión,Fecha. Inicio Vigencia,Fecha Fin Vigencia,Fecha Vencimiento,Fecha Anulación,Estado,Cert Externo,Nro Póliza RIMAC,Nro Certificado RIMAC,Codigo Usuario,Nombre Usuario
0,BANCO BBVA PERU,8763,DESGRAVAMEN TC BBVA CREDITO,LQ,1671618136,18.68,SOL,2025-01-23,2024-11-08,2024-12-26,2024-11-08,NaT,COB,',NaN,NaN,DT_CULQI,DT_CULQI
1,BANCO BBVA PERU,8763,DESGRAVAMEN TC BBVA CREDITO,LQ,1671618941,0.45,SOL,2025-01-23,2024-11-08,2024-12-08,2024-11-08,NaT,COB,',NaN,NaN,DT_CULQI,DT_CULQI
2,BANCO BBVA PERU,8763,DESGRAVAMEN TC BBVA CREDITO,LQ,1671620580,13.01,SOL,2025-01-23,2024-11-08,2024-12-17,2024-11-08,NaT,COB,',NaN,NaN,DT_CULQI,DT_CULQI
3,BANCO BBVA PERU,8763,DESGRAVAMEN TC BBVA CREDITO,LQ,1671618135,2.86,SOL,2025-01-23,2024-11-08,2024-12-08,2024-11-08,NaT,COB,',NaN,NaN,DT_CULQI,DT_CULQI
4,BANCO BBVA PERU,8763,DESGRAVAMEN TC BBVA CREDITO,LQ,1671620582,19.03,SOL,2025-01-23,2024-11-08,2024-12-10,2024-11-08,NaT,COB,',NaN,NaN,DT_CULQI,DT_CULQI

In [70]:
df_liquidaciones.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 619007 entries, 0 to 619006
Data columns (total 18 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Desc Canal              619007 non-null  object
 1   Cod Prod                619007 non-null  int64
 2   Producto                619007 non-null  object
 3   TipoDoc                 619007 non-null  object
 4   NumDoc                  619007 non-null  int64
 5   Monto                   619007 non-null  float64
 6   Moneda                  619007 non-null  object
 7   Fecha Emisión           619007 non-null  datetime64[ns]
 8   Fecha. Inicio Vigencia  619007 non-null  datetime64[ns]
 9   Fecha Fin Vigencia      619007 non-null  datetime64[ns]
 10  Fecha Vencimiento       619007 non-null  datetime64[ns]
 11  Fecha Anulación         28 non-null      datetime64[ns]
 12  Estado                  619007 non-null  object
 13  Cert Externo            619007 non-null  object
 14  Nro Póliza RIMAC        0 non-null       float64
 15  Nro Certificado RIMAC   0 non-null       float64
 16  Codigo Usuario          619007 non-null  object
 17  Nombre Usuario          619007 non-null  object
dtypes: datetime64[ns](5), float64(3), int64(2), object(8)
memory usage: 85.0+ MB

In [76]:
df_liquidaciones['Moneda'].value_counts()

Moneda
SOL    618338
USD       669
Name: count, dtype: int64