In [2]:
import pandas as pd
from datetime import datetime
import warnings
warnings.filterwarnings("ignore", category=UserWarning, module="openpyxl")
import os
import numpy as np
pd.set_option('display.max_columns', None)
import csv

In [ ]:
#47 columnas  hasta "contratante"

In [39]:
#df_reporte_emision= pd.read_csv('c:/data/VIDRENTADEV - NOVIEMBRE 2025_94910.csv', sep=',', encoding='latin-1', dtype=str, skiprows=7)
df_reporte_emision= pd.read_csv('c:/data/EMI PREST ENE_95566.csv', sep=',', encoding='latin-1', dtype=str, skiprows=7, usecols=range(47))

In [40]:
df_reporte_emision.columns = (df_reporte_emision.columns.str.strip()
                                                    .str.upper()  # opcional: todo en mayúsculas
                                                    .str.replace(r'[^A-Za-z0-9_]', '_', regex=True)  # reemplazar estapacios por _
)

In [41]:
df_reporte_emision.head(3)

,NRO_LOTE,NRO_LOTES_ANTERIORES,FECHA_CARGA_LOTE,C_DIGO_PRODUCTO,PRODUCTO,PLAN,NOMBRE_DE_PLAN,C_D__CERTIFICADO_CANAL,TIPO_MOVIMIENTO,NOMBRE,APELLIDO_PATERNO,APELLIDO_MATERNO,FECHA_NACIMIENTO,TIPO_DOC__ID,DOC__ID_,FEC__INICIO,FEC__FIN,MONEDA,SUMA_ASEGURADA,TASA,TASA_CON_RECARGO,PRIMABRUTACAN,PRIMANETACAN,PLACA,MOTOR,NOMBRE_ARCHIVO,L_NEA_DE_TRAMA,LINEA_TRAMA_TEXTO_COMPLETO_,ESTADO,DESCRIPCI_N_DE_ESTADO,C_DIGO_DE_RAMO,C_DIGO_DE_PRODUCTO_EN_CORE,MONEDA_1,PRIMA_NETA,DERECHO_DE_EMISI_N,IGV,INTERES_FINANCIAMIENTO,IGV_INTERES_FINANCIAMIENTO,OTROS_CONCEPTOS,PRIMA_BRUTA,COMISION,NUMERO_CERTIFICADO_RIMAC,NUMERO_DE_POLIZA,TIPO_DOC_EMISI_N,N__DOC_EMISI_N,FECHA_DE_EMISI_N,CONTRATANTE
0,1367429,NaN,03/01/2026 17:56:16,3827,Desgravamen + Desempleo BBVA,380668,Plan Premier PEN,C00110190674000646636,Renovacion,NaN,NaN,NaN,NaN,NaN,NaN,27/08/2025,05/12/2025,SOL,144282.82,0.28,0.28,40.4,39.22,NaN,NaN,20100130204_0157001_20260101_007.TXT,17698,953001101906740006466360011019975020015984901P...,Terminado,Emitido en A/X,VTHD,0157,SOL,39.22,1.18,0.00,0.00,0.00,0.00,40.40,0.00,'15701729014-1,'8710500001,LQ,1766355506,04-JAN-26,BANCO BBVA PERU
1,1367429,NaN,03/01/2026 17:56:16,3827,Desgravamen + Desempleo BBVA,380668,Plan Premier PEN,C00110249064002688352,Renovacion,NaN,NaN,NaN,NaN,NaN,NaN,10/11/2025,10/12/2025,SOL,23336.02,0.5511,0.5511,12.86,12.49,NaN,NaN,20100130204_0157001_20260101_007.TXT,36782,95800110249064002688352 01P...,Terminado,Emitido en A/X,VTHD,0157,SOL,12.49,0.37,0.00,0.00,0.00,0.00,12.86,0.00,'15701745329-1,'8792500001,LQ,1766405460,04-JAN-26,BANCO BBVA PERU
2,1367433,NaN,03/01/2026 17:56:08,3827,Desgravamen + Desempleo BBVA,380668,Plan Premier PEN,C00110241784001319732,Renovacion,NaN,NaN,NaN,NaN,NaN,NaN,07/08/2025,05/12/2025,SOL,28979.63,0.69,0.69,20,19.42,NaN,NaN,20100130204_0157001_20260101_006.TXT,40842,951001102417840013197320011024172020000359501P...,Terminado,Emitido en A/X,VTHD,0157,SOL,19.42,0.58,0.00,0.00,0.00,0.00,20.00,0.00,'15701719764-1,'8710500001,LQ,1766569822,04-JAN-26,BANCO BBVA PERU

In [43]:
df_reporte_emision.drop(['TASA_CON_RECARGO', 'PRIMABRUTACAN', 'PRIMANETACAN', 
                         'PLACA','MOTOR', 'L_NEA_DE_TRAMA', 'MONEDA_1', 'TASA',                    
                         'IGV','INTERES_FINANCIAMIENTO', 'IGV_INTERES_FINANCIAMIENTO', 
                         'OTROS_CONCEPTOS', 'COMISION','NOMBRE', 'APELLIDO_PATERNO',
                         'APELLIDO_MATERNO','FECHA_NACIMIENTO', 'TIPO_DOC__ID','DOC__ID_'], axis=1, inplace=True)

In [44]:
df_reporte_emision.rename(columns={
    'NRO_LOTES_ANTERIORES': 'LOTES_ANTERIORES',  'C_DIGO_PRODUCTO': 'CODIGO_PRODUCTO',
    'C_D__CERTIFICADO_CANAL': 'CERTIFICADO_CANAL',  'TIPO_DOC__ID': 'TIPO_DOCUMENTO',
    'DOC__ID_': 'ID_DOCUMENTO',  'FEC__INICIO': 'FECHA_INICIO',
    'FEC__FIN': 'FECHA_FIN',  'LINEA_TRAMA_TEXTO_COMPLETO_': 'LINEA_TRAMA',
    'DESCRIPCI_N_DE_ESTADO': 'DESCRIPCION_ESTADO',  'C_DIGO_DE_RAMO': 'CODIGO_RAMO',
    'C_DIGO_DE_PRODUCTO_EN_CORE': 'CODIGO_PROD_CORE',  'DERECHO_DE_EMISI_N': 'DERECHO_EMISION',
    'NUMERO_CERTIFICADO_RIMAC': 'CERTIFICADO_RIMAC',  'TIPO_DOC_EMISI_N': 'TIPO_DOC_EMISION',
    'N__DOC_EMISI_N': 'NRO_DOC_EMISION',  'FECHA_DE_EMISI_N': 'FECHA_EMISION'
}, inplace=True)

In [45]:
df_reporte_emision.head(3)

,NRO_LOTE,LOTES_ANTERIORES,FECHA_CARGA_LOTE,CODIGO_PRODUCTO,PRODUCTO,PLAN,NOMBRE_DE_PLAN,CERTIFICADO_CANAL,TIPO_MOVIMIENTO,FECHA_INICIO,FECHA_FIN,MONEDA,SUMA_ASEGURADA,NOMBRE_ARCHIVO,LINEA_TRAMA,ESTADO,DESCRIPCION_ESTADO,CODIGO_RAMO,CODIGO_PROD_CORE,PRIMA_NETA,DERECHO_EMISION,PRIMA_BRUTA,CERTIFICADO_RIMAC,NUMERO_DE_POLIZA,TIPO_DOC_EMISION,NRO_DOC_EMISION,FECHA_EMISION,CONTRATANTE
0,1367429,NaN,03/01/2026 17:56:16,3827,Desgravamen + Desempleo BBVA,380668,Plan Premier PEN,C00110190674000646636,Renovacion,27/08/2025,05/12/2025,SOL,144282.82,20100130204_0157001_20260101_007.TXT,953001101906740006466360011019975020015984901P...,Terminado,Emitido en A/X,VTHD,0157,39.22,1.18,40.40,'15701729014-1,'8710500001,LQ,1766355506,04-JAN-26,BANCO BBVA PERU
1,1367429,NaN,03/01/2026 17:56:16,3827,Desgravamen + Desempleo BBVA,380668,Plan Premier PEN,C00110249064002688352,Renovacion,10/11/2025,10/12/2025,SOL,23336.02,20100130204_0157001_20260101_007.TXT,95800110249064002688352 01P...,Terminado,Emitido en A/X,VTHD,0157,12.49,0.37,12.86,'15701745329-1,'8792500001,LQ,1766405460,04-JAN-26,BANCO BBVA PERU
2,1367433,NaN,03/01/2026 17:56:08,3827,Desgravamen + Desempleo BBVA,380668,Plan Premier PEN,C00110241784001319732,Renovacion,07/08/2025,05/12/2025,SOL,28979.63,20100130204_0157001_20260101_006.TXT,951001102417840013197320011024172020000359501P...,Terminado,Emitido en A/X,VTHD,0157,19.42,0.58,20.00,'15701719764-1,'8710500001,LQ,1766569822,04-JAN-26,BANCO BBVA PERU

In [46]:

df_reporte_emision= df_reporte_emision.fillna({'LOTES_ANTERIORES':'', 'CODIGO_RAMO': '', 'CODIGO_PROD_CORE':'',
                                               'NRO_DOC_EMISION': '','TIPO_DOC_EMISION': '', 'CONTRATANTE':''})

In [47]:
df_reporte_emision['CERTIFICADO_CANAL']= df_reporte_emision['CERTIFICADO_CANAL'].str[1:]
df_reporte_emision['CERTIFICADO_RIMAC']= df_reporte_emision['CERTIFICADO_RIMAC'].str[1:]
df_reporte_emision['NUMERO_DE_POLIZA']= df_reporte_emision['NUMERO_DE_POLIZA'].str[1:]
df_reporte_emision["MONEDA"] = df_reporte_emision["MONEDA"].replace(r"^\s*$", None, regex=True)
df_reporte_emision["MONEDA"] = df_reporte_emision["MONEDA"].where(df_reporte_emision["MONEDA"].isin(["USD", "SOL"]), "SIN DATO")

In [49]:
df_reporte_emision['NRO_LOTE']= df_reporte_emision['NRO_LOTE'].fillna(0).astype('int')
df_reporte_emision['FECHA_CARGA_LOTE'] = pd.to_datetime(df_reporte_emision['FECHA_CARGA_LOTE'], format="%d/%m/%Y %H:%M:%S", errors='coerce').dt.date
df_reporte_emision["PRODUCTO"] = df_reporte_emision["PRODUCTO"].astype(str).str.upper()
df_reporte_emision["NOMBRE_DE_PLAN"] = df_reporte_emision["NOMBRE_DE_PLAN"].astype(str).str.upper()
df_reporte_emision["TIPO_MOVIMIENTO"] = df_reporte_emision["TIPO_MOVIMIENTO"].astype(str).str.upper()
df_reporte_emision['FECHA_INICIO'] = pd.to_datetime(df_reporte_emision['FECHA_INICIO'], format="%d/%m/%Y", errors='coerce').dt.date
df_reporte_emision['FECHA_FIN'] = pd.to_datetime(df_reporte_emision['FECHA_FIN'], format="%d/%m/%Y", errors='coerce').dt.date
df_reporte_emision['SUMA_ASEGURADA'] = pd.to_numeric(df_reporte_emision['SUMA_ASEGURADA'], errors="coerce").astype('float64')
df_reporte_emision['PRIMA_NETA'] = pd.to_numeric(df_reporte_emision['PRIMA_NETA'], errors="coerce").astype('float64')
df_reporte_emision['DERECHO_EMISION'] = pd.to_numeric(df_reporte_emision['DERECHO_EMISION'], errors="coerce").astype('float64')
df_reporte_emision['PRIMA_BRUTA'] = pd.to_numeric(df_reporte_emision['PRIMA_BRUTA'], errors="coerce").astype('float64')
df_reporte_emision['FECHA_EMISION'] = pd.to_datetime(df_reporte_emision['FECHA_EMISION'], format='%d-%b-%y', errors='coerce').dt.date

In [50]:
df_reporte_emision.head(3)

,NRO_LOTE,LOTES_ANTERIORES,FECHA_CARGA_LOTE,CODIGO_PRODUCTO,PRODUCTO,PLAN,NOMBRE_DE_PLAN,CERTIFICADO_CANAL,TIPO_MOVIMIENTO,FECHA_INICIO,FECHA_FIN,MONEDA,SUMA_ASEGURADA,NOMBRE_ARCHIVO,LINEA_TRAMA,ESTADO,DESCRIPCION_ESTADO,CODIGO_RAMO,CODIGO_PROD_CORE,PRIMA_NETA,DERECHO_EMISION,PRIMA_BRUTA,CERTIFICADO_RIMAC,NUMERO_DE_POLIZA,TIPO_DOC_EMISION,NRO_DOC_EMISION,FECHA_EMISION,CONTRATANTE
0,1367429,,2026-01-03,3827,DESGRAVAMEN + DESEMPLEO BBVA,380668,PLAN PREMIER PEN,00110190674000646636,RENOVACION,2025-08-27,2025-12-05,SOL,144282.82,20100130204_0157001_20260101_007.TXT,953001101906740006466360011019975020015984901P...,Terminado,Emitido en A/X,VTHD,0157,39.22,1.18,40.40,15701729014-1,8710500001,LQ,1766355506,2026-01-04,BANCO BBVA PERU
1,1367429,,2026-01-03,3827,DESGRAVAMEN + DESEMPLEO BBVA,380668,PLAN PREMIER PEN,00110249064002688352,RENOVACION,2025-11-10,2025-12-10,SOL,23336.02,20100130204_0157001_20260101_007.TXT,95800110249064002688352 01P...,Terminado,Emitido en A/X,VTHD,0157,12.49,0.37,12.86,15701745329-1,8792500001,LQ,1766405460,2026-01-04,BANCO BBVA PERU
2,1367433,,2026-01-03,3827,DESGRAVAMEN + DESEMPLEO BBVA,380668,PLAN PREMIER PEN,00110241784001319732,RENOVACION,2025-08-07,2025-12-05,SOL,28979.63,20100130204_0157001_20260101_006.TXT,951001102417840013197320011024172020000359501P...,Terminado,Emitido en A/X,VTHD,0157,19.42,0.58,20.00,15701719764-1,8710500001,LQ,1766569822,2026-01-04,BANCO BBVA PERU

In [52]:
df_reporte_emision['CERTIFICADO_RIMAC'].isna().sum()

np.int64(0)

In [53]:
df_reporte_emision[df_reporte_emision['NRO_DOC_EMISION'].isna()].head()

Empty DataFrame
Columns: [NRO_LOTE, LOTES_ANTERIORES, FECHA_CARGA_LOTE, CODIGO_PRODUCTO, PRODUCTO, PLAN, NOMBRE_DE_PLAN, CERTIFICADO_CANAL, TIPO_MOVIMIENTO, FECHA_INICIO, FECHA_FIN, MONEDA, SUMA_ASEGURADA, NOMBRE_ARCHIVO, LINEA_TRAMA, ESTADO, DESCRIPCION_ESTADO, CODIGO_RAMO, CODIGO_PROD_CORE, PRIMA_NETA, DERECHO_EMISION, PRIMA_BRUTA, CERTIFICADO_RIMAC, NUMERO_DE_POLIZA, TIPO_DOC_EMISION, NRO_DOC_EMISION, FECHA_EMISION, CONTRATANTE]
Index: []

In [54]:
df_reporte_emision.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 428633 entries, 0 to 428632
Data columns (total 28 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   NRO_LOTE            428633 non-null  int64
 1   LOTES_ANTERIORES    428633 non-null  object
 2   FECHA_CARGA_LOTE    428633 non-null  object
 3   CODIGO_PRODUCTO     428633 non-null  object
 4   PRODUCTO            428633 non-null  object
 5   PLAN                428633 non-null  object
 6   NOMBRE_DE_PLAN      428633 non-null  object
 7   CERTIFICADO_CANAL   428633 non-null  object
 8   TIPO_MOVIMIENTO     428633 non-null  object
 9   FECHA_INICIO        428633 non-null  object
 10  FECHA_FIN           428633 non-null  object
 11  MONEDA              428633 non-null  object
 12  SUMA_ASEGURADA      428633 non-null  float64
 13  NOMBRE_ARCHIVO      428633 non-null  object
 14  LINEA_TRAMA         428633 non-null  object
 15  ESTADO              428633 non-null  object
 16  DESCRIPCION_ESTADO  428633 non-null  object
 17  CODIGO_RAMO         428633 non-null  object
 18  CODIGO_PROD_CORE    428633 non-null  object
 19  PRIMA_NETA          427876 non-null  float64
 20  DERECHO_EMISION     428244 non-null  float64
 21  PRIMA_BRUTA         427853 non-null  float64
 22  CERTIFICADO_RIMAC   428633 non-null  object
 23  NUMERO_DE_POLIZA    428633 non-null  object
 24  TIPO_DOC_EMISION    428633 non-null  object
 25  NRO_DOC_EMISION     428633 non-null  object
 26  FECHA_EMISION       428244 non-null  object
 27  CONTRATANTE         428633 non-null  object
dtypes: float64(4), int64(1), object(23)
memory usage: 91.6+ MB