In [1]:
import pandas as pd
from datetime import datetime
import warnings
warnings.filterwarnings("ignore", category=UserWarning, module="openpyxl")
import os
import numpy as np
pd.set_option('display.max_columns', None)

In [2]:
df_tramas= pd.read_excel('c:/data/TRAMAS POR CAMBIAR.xlsx', sheet_name='Hoja1')
df_tramas.head(3)

,TRAMA CONVERTIDA,TRAMA DIARIA
0,959001100023040001360300011000238010000122601P...,959001100023040001360300011000234960003605801P...
1,959001100023240001414170011000238010001013601P...,959001100023240001414170011000239960003696101P...
2,959001100023240001414170011000238010001013601P...,959001100023240001414170011000239960003696101P...

In [3]:
inicio= 376
fin = 392
df_tramas["TRAMA CONVERTIDA2"] = df_tramas.apply(
    lambda x: x['TRAMA CONVERTIDA'][:inicio] + x['TRAMA DIARIA'][inicio:fin] + x['TRAMA CONVERTIDA'][fin:], axis=1)

In [4]:
df_tramas.head(5)

,TRAMA CONVERTIDA,TRAMA DIARIA,TRAMA CONVERTIDA2
0,959001100023040001360300011000238010000122601P...,959001100023040001360300011000234960003605801P...,959001100023040001360300011000238010000122601P...
1,959001100023240001414170011000238010001013601P...,959001100023240001414170011000239960003696101P...,959001100023240001414170011000238010001013601P...
2,959001100023240001414170011000238010001013601P...,959001100023240001414170011000239960003696101P...,959001100023240001414170011000238010001013601P...
3,959001100023240001414170011000238010001013601P...,959001100023240001414170011000239960003696101P...,959001100023240001414170011000238010001013601P...
4,959001100023240001414170011000238010001013601P...,959001100023240001414170011000239960003696101P...,959001100023240001414170011000238010001013601P...

In [5]:
df_tramas.to_excel('c:/data/TRAMAS CAMBIADAS.xlsx', index=False)

Lista de nombre de productos

In [26]:
df_Productos= pd.read_excel('c:/data/Lista de Productos_BBVA 6.xlsx', sheet_name='LISTA', dtype={'COD_TRAMA': str})
df_Productos = df_Productos[['COD_TRAMA','PRODUCTO']]
df_Productos.head(3)

  COD_TRAMA              PRODUCTO
0       805  Continental Empresas
1       800      Continental Vida
2       807  Vida Ahorro Empresas

In [27]:
df_Productos = df_Productos.dropna(subset=['COD_TRAMA'])

In [28]:
df_Productos['PRODUCTO'] = df_Productos['PRODUCTO'].str.upper()

In [29]:
df_Productos.head()

  COD_TRAMA                PRODUCTO
0       805    CONTINENTAL EMPRESAS
1       800        CONTINENTAL VIDA
2       807    VIDA AHORRO EMPRESAS
3       806  VIDA AHORRO INDIVIDUAL
4       803         VIDA PROTECCIÓN

In [31]:
df_Productos.to_csv('c:/data/PRODUCTOS.csv', encoding="utf-8-sig", index=False)